### ISSUE TITLE
CocoaPods 0.36 Beta swift 1.2 does not compile because of "as!" custing

### ISSUE THREAD

**Issue by sergdort** [Quick/Nimble#101]

**Comment by gyemme** [comment]
@sergdort this issue could potentially be a duplicate of this https://github.com/Quick/Nimble/issues/98. Which version of Xcode are you using ?

**Comment by sergdort** [comment]
I'm using Xcode 6.1.1

**Comment by sergdort** [comment]
I've actually replaced all "as!" with "as" and it compiles for now.

**Comment by gyemme** [comment]
That's one way to do it but as @jeffh mentioned in the previous post use swift-1.1 branch for Xcode 6.1.1

**Comment by jeffh** [comment]
Yeah, Nimble v0.3.0 is the latest swift 1.1 release while v0.4.0 is the latest swift 1.2 release. master refers to Swift 1.2 while the `swift-1.1` branch refers to swift-1.1 work.
