### ISSUE TITLE
Version 11.x regression: tuple comparison with `==`

### ISSUE THREAD

**Issue by NachoSoto** [Quick/Nimble#1014]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```swift
expect(tuple) == (a, b)
```

### What did you expect to happen?

This used to compile with Nimble 10.0.0

### What actually happened instead?

> Type '(a: A, b: B)' cannot conform to 'Equatable'

### Environment

List the software versions you're using:

- Quick: 6.0.0
- Nimble: 11.1.0
- Xcode Version: 14.1.0
- Swift Version: 5.7.1

- Carthage: 0.38.0

**Comment by matheusalano** [comment]
I faced this issue too 😕

**Comment by younata** [comment]
I'm going to release 11.1.1 shortly (later tonight). Which will have this fix + the toEventually fix.

Sorry about this!
