### ISSUE TITLE
Cannot specialize protocol type 'Expectation'

### ISSUE THREAD

**Issue by andrrrr** [Quick/Nimble#1016]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Azure pipelines was failing screenshot tests consistently. I updated the libraries to the following versions.
After that I get an error: Cannot specialize protocol type 'Expectation'
<img width="344" alt="Screenshot 2022-11-07 at 14 39 07" src="https://user-images.githubusercontent.com/3891761/200324415-db1a9baa-07d2-4d69-b77c-261bef9ff93a.png">

### What did you expect to happen?

I expected the Nimble-snapshots to work.
### What actually happened instead?

Error, not able to run tests

### Environment
 - Nimble (11.1.0)
 - Nimble-Snapshots (9.4.0):
 - iOSSnapshotTestCase (8.0.0)
 - Quick (5.0.1)
 - Xcode 14.1.0
- Swift Version: Xcode Default (5)
- Cocoapods: 1.11.3

**Comment by younata** [comment]
This is not a bug in Nimble.

Moreover, Nimble-snapshots has [been updated for Nimble 11](https://github.com/ashfurrow/Nimble-Snapshots/pull/253). The next released version of Nimble-Snapshots will support this.

**Comment by ashfurrow** [comment]
The new version of Nimble-Snapshots was just released: `9.5.0`. You should be set 👍
