### ISSUE TITLE
Where to set the global timeout?

### ISSUE THREAD

**Issue by wrightak** [Quick/Nimble#1021]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

I would like to increase the global timeout on CI. Xcode Cloud seems to use slow machines, or at least they seem to perform slowly. I know that I can do this by using this code:

```
// Increase the global timeout to 5 seconds:
Nimble.AsyncDefaults.timeout = .seconds(5)

// Slow the polling interval to 0.1 seconds:
Nimble.AsyncDefaults.pollInterval = .milliseconds(100)
```

My question is: is there a recommendation on where should this be set? If I do it in one of the tests, I don't know that this test will be the first to be executed.

**Comment by younata** [comment]
If you're using Quick, we recommend creating a [QuickConfiguration subclass](https://github.com/Quick/Quick/blob/main/Documentation/en-us/ConfiguringQuick.md) to do this in.

If you're using XCTest, you can create an [XCTestObservation implementation](https://developer.apple.com/documentation/xctest/xctestobservation), and configure your async defaults in `testBundleWillStart(_:)`. You will also need to add that XCTestObservation object to [XCTestObservationCenter](https://developer.apple.com/documentation/xctest/xctestobservationcenter).

Hope that helps!

**Comment by wrightak** [comment]
@younata That helps a lot! Great answer, thank you. Would it be helpful if I created a PR to add this to the README?

**Comment by younata** [comment]
@wrightak Appreciate the offer! I already took care of it, though. https://github.com/Quick/Nimble/pull/1022
