### ISSUE TITLE
Way to use Quick6 Nimble11 with KIF UI testing framework

### ISSUE THREAD

**Issue by blyscuit** [Quick/Nimble#1028]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

- Use [KIF](https://github.com/kif-framework/KIF)
- Upgrade from Quick 5 Nimble 10 to Quick 6 and Nimble 11.
- Add `@MainActor in` to KIF tests.

### What did you expect to happen?

KIF tests should work the same.

### What actually happened instead?

App correctly launches but UI is unable to update its UI.

If remove `@MainActor in` test would work but show error `Main Thread Checker` which sometimes would crash the test.

### Environment

List the software versions you're using:

- Quick: *6.1.0*
- Nimble: *11.2.1*
- Xcode Version: *14.2* (Open Xcode; In menubar: Xcode > About Xcode)
- Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

- Swift Package Manager - Swift 5.7.1

### Project that demonstrates the issue

https://github.com/blyscuit/kif-quick6-nimble11

**Comment by younata** [comment]
My apologies for ignoring this for so long.

You should try the still-in-beta [Quick 7](https://github.com/Quick/Quick/releases/tag/v7.0.0-beta.3). It is much more compatible with the non-async tests and test behaviors. It should work well with KIF.
