### ISSUE TITLE
Is there a technical reason why `expect` doesn't offer `@autoclosure` versions for `async` tests?

### ISSUE THREAD

**Issue by AlexKobachiJP** [Quick/Nimble#1037]
- [x ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Try to add async test following https://github.com/Quick/Nimble/blob/1454547ea836dd852096e47b5eb1425479085880/README.md?plain=1#L308 which makes the async test look simple and clean:

```swift
await expect(await aFunctionReturning1()).to(equal(1))
```

### What did you expect to happen?

I expected it to compile.

### What actually happened instead?

It did not compile:
- 'async' call in an autoclosure that does not support concurrency

While the fixes is simple (wrap async call in closure), I am wondering:
- How come the `async` versions of `expect` don't offer `@autoclosure` varieties? Is there a technical reason?

I guess the main expectation would be for the `Readme` to show compiling code, but want to understand if there's a reason first.

### Environment

List the software versions you're using:

- Nimble: v11.2.1
- Xcode Version: Version 14.2 (14C18)
- Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager v5.7.1

### Project that demonstrates the issue

```swift
private func aFunctionReturning1() async -> Int {
    1
}

final class NimbleAsyncTest: XCTestCase {

    // As per Readme, does not compile.
    func test_NG() async {
        await expect(await aFunctionReturning1()).to(equal(1))
    }

    // Compiles.
    func test_OK() async {
        await expect({ await aFunctionReturning1() }).to(equal(1))
    }

    // Compiles.
    func test_OK_trailingClosure() async {
        await expect { await aFunctionReturning1() }.to(equal(1))
    }
}
```

**Comment by younata** [comment]
[Yes, there is](https://github.com/Quick/Nimble/issues/1035#issuecomment-1484343831).

> use `await expect { await foo.bar() } == "Hello World"` instead. `expect` with async closures does not have a version that uses autoclosures (the compiler would always assume you want the autoclosure is async, and thus raise compiler errors if you use Nimble in a synchronous context - I don't know if this has since been fixed).

**Comment by AlexKobachiJP** [comment]
Got it, thanks! Was about to raise PR but saw you already fixed it.
