### ISSUE TITLE
Podfile require use_frameworks! keyword

### ISSUE THREAD

**Issue by kostiakoval** [Quick/Nimble#104]
When I try to install it with Cocoapods I get an error

[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it.
To fix it I had to add `use_frameworks!` to Podfile

**Comment by jeffh** [comment]
Hey @kostiakoval,

Thanks for letting us know. The documentation needs to be updated to include `use_frameworks!` since it's been changed in a newer beta of cocoapods.
