### ISSUE TITLE
Build error using Xcode 14.3

### ISSUE THREAD

**Issue by JacobAhlberg** [Quick/Nimble#1046]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Upgraded to Xcode 14.3

### What did you expect to happen?

I expected everything to work just like the previous version of Xcode

### What actually happened instead?

Getting following errors when trying to build project:
![image](https://user-images.githubusercontent.com/22389483/229733535-c2033d12-2046-4765-8dd4-ce95aaad7d6c.png)
![image](https://user-images.githubusercontent.com/22389483/229733688-64a33efe-ca91-4910-a93c-d46941a40710.png)

I can reproduce the error in a new project. Just importing Quick + Nimble libraries using Swift Package Manager. And then press build.

### Environment

List the software versions you're using:

- Quick: main (branch)
- Nimble: main (branch)
- Xcode Version: 14.3
- Swift Version: 5

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager: 5.8.0

**Comment by younata** [comment]
This is fixed in Nimble 11.2.2. Sorry for the trouble!
