### ISSUE TITLE
Quick 7.3.0 and Nimble 13.0.0 ERROR : "Instance member 'testVariablesNotNil' cannot be used on type 'ConditionSelectionTests'" 

### ISSUE THREAD

**Issue by sagaguptadeloitte** [Quick/Nimble#1099]
<img width="1161" alt="Screenshot 2023-11-08 at 3 54 07 PM" src="https://github.com/Quick/Nimble/assets/150242062/4f19dfdc-75e4-4bbc-9436-a3f8f3e41ba3">
I am using Quick 7.3.0 and Nimble 13.0.0
getting error "Instance member 'testVariablesNotNil' cannot be used on type 'ConditionSelectionTests'" 

It worked for old version 5.0.1
### Environment

List the software versions you're using:

- Quick: *7.3.0*
- Nimble: *13.0.0*
- Xcode Version: *15.0* (Open Xcode; In menubar: Xcode > About Xcode)
- Swift Version: *5.3* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.16.3* (Use `pod --version` in Terminal)
- Carthage: *?.?* (Use `carthage version` in Terminal)
- Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue
We can not share project
Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by younata** [comment]
[Quick 7](https://github.com/Quick/Quick/releases/tag/v7.0.0) made `spec` a class method, not an instance method. This means that instance methods/properties can no longer be accessed in quick specs.

From Quick 7's release notes:

> ## Migrating Suggestions
> [...]
> If you have any test helpers that exist as properties or methods of your QuickSpec subclasses, the you will need to either move them inside of the spec function, or outside to another scope.

This is expected behavior. My apologies for the migration frustration.
