### ISSUE TITLE
Release 13.2.0 is not available through cocoapods source repo/CDN

### ISSUE THREAD

**Issue by stonko1994** [Quick/Nimble#1115]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Trying to update to 13.2.0 using Cocoapods

### What did you expect to happen?

Please replace this with what you expected to happen.
pod install --repo-update results in an error stating that version 13.2.0 of Nimble does not exist.

```
[!] CocoaPods could not find compatible versions for pod "Nimble":
  In Podfile:
    Nimble (~> 13.2.0)

None of your spec sources contain a spec satisfying the dependency: `Nimble (~> 13.2.0)`.
```

Please replace this with what happened instead.

### Environment

List the software versions you're using:

 - Quick: `N/A`
 - Nimble: `N/A`
 - Xcode Version: `N/A` (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: `N/A` (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.13.0* (Use `pod --version` in Terminal)
 - Carthage: `N/A` (Use `carthage version` in Terminal)
 - Swift Package Manager `N/A` (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by younata** [comment]
That's for the exact same reason Quick 7.4.0 is not available in the cocoapods spec repo. Cocoapods doesn't support visionOS yet, and it errors if you try to push a pod that includes visionOS. https://github.com/CocoaPods/CocoaPods/issues/12118

**Comment by stonko1994** [comment]
Ah that's a pitty 😕

**Comment by younata** [comment]
Update: Cocoapods 1.15 was just released, which adds support for visionOS. Unfortunately, Nimble is blocked until CWLPreconditionTesting releases an update.

On the plus side, Quick 7.4.0 is now available on cocoapods.

**Comment by tommy10344** [comment]
Hello. Are there any updates on this?
It seems that the CwlPreconditionTesting update for Vision OS support has been pushed to CocoaPods specs repo.
https://github.com/CocoaPods/Specs/commit/e5034f3b270f7b08beffb274eda3d857c463c3f6

**Comment by younata** [comment]
Just got around to pushing Nimble 13.2.1 to cocoapods. 13.2.0 will not be uploaded.

Sorry for the delay!

**Comment by tommy10344** [comment]
@younata Thanks!  I was able to install 13.2.1 on my project.
