### ISSUE TITLE
Comparing booleans in obj-c requires NSNumber boxing

### ISSUE THREAD

**Issue by solidcell** [Quick/Nimble#113]
`expect(@YES).to(beTrue());` requires `@YES` instead of just `YES`, otherwise you'll get "Implicit conversion of 'BOOL' (aka 'bool') to 'id' is disallowed with ARC".

**Comment by jeffh** [comment]
Thanks @solidcell. This was definitely a feature I had in mind, but never got around to implementing.

FWIW, this would probably require changing `NMB_expect` to be a [overloaded function](http://nshipster.com/__attribute__/#overloadable) that captures more type information of the boxed value.
