### ISSUE TITLE
When the current main branch will be in a release?

### ISSUE THREAD

**Issue by diogot** [Quick/Nimble#1140]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

On Xcode 15.3 with Strict Concurrency Checking set to Complete we got warnings on `PollingDefaults`. I was looking around and it seems to be already fixed in the main branch. Do you have a guess on we'll have a new release with the code in the main branch?

### Environment

List the software versions you're using:

- Nimble: 13.2.1
- Xcode Version: Xcode 15.3
- Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager 5.10.0-dev

**Comment by younata** [comment]
Oh. Good point. It has been a while.

Well, 13.3.0 is out now, which includes that in the fix.

Note that Nimble 14 will contain the work to get Nimble to work fine with strict concurrency warnings, as described in [this comment](https://github.com/Quick/Nimble/issues/1127#issuecomment-1984967860).

**Comment by diogot** [comment]
Oh, I didn't expect a release so fast, thank you very much!
Nice work!
