### ISSUE TITLE
Attach binaries to releases

### ISSUE THREAD

**Issue by ikesyo** [Quick/Nimble#115]
With Carthage from v0.6, we can create a zip file of a framework: `carthage archive Nimble`. Then if the zip file is attached to its release, Carthage will use the attached binary instead of building it from the source.

Could you please attach the binaries to latest releases, v0.3.1/v0.4.0 for easier use for CI environment?

**Comment by jeffh** [comment]
Hey @ikesyo,

I haven't used carthage so I'm not familiar with the configuration process required for it. Is there a different usability benefit for using pre-built binaries or is it only for faster to compiles for CI?

**Comment by ikesyo** [comment]
Hi @jeffh, sorry for the lack of context.

Assumption: Carthage requires valid certificates, code signing settings in a target project for building, because the tool tries to create a fat binary where device builds, simulator builds with some architectures are in.

The benefit I was considering is not faster compilation, but is that there would be no need to import certificates, set up code signing in CI (e.g. https://github.com/Carthage/Carthage/blob/3a7147897ca7209cbed575b4981f21aa9d98fc2e/script/cibuild#L27-L52).

Those process requires some development certificate (p12 file) and secure environment variable of the password for the certificate from CI's UI. This makes it very difficult for someone to create a pull request  which introducing Nimble (or Quick, or other libraries) for some libraries, because they might not have access rights for the repository.

**Comment by ikesyo** [comment]
[This PR](https://github.com/Hearst-DD/ObjectMapper/pull/89) uses my forked repository of Nimble, which has attached binary for release v0.3.1. It is a example case for the issue.

**Comment by gfontenot** [comment]
:+1: It also seriously speeds up the bootstrapping process. It's also really nice for users that don't want to use a dependency manager at all because they can just download the binaries themselves and integrate on their own. FWIW, Carthage makes it dead simple to create the zip files for releases. I'd be happy to help out here if y'all don't want to manage it.

**Comment by jeffh** [comment]
@gfontenot, I'll take you on that offer since I'm not a user of Carthage (yet). I'm not sure of the code-signing requirements that would be necessary or if that should be something the Quick org should privately own. Thoughts @modocache?

**Comment by gfontenot** [comment]
Carthage signs the binaries when building, but Xcode re-signs them when they are copied into the app bundle, so I'm not sure if it's worthwhile trying to own the signing. Maybe @jspahrsummers has some guidance?

**Comment by jspahrsummers** [comment]
Carthage just uses `xcodebuild`, so it'll sign if that's how you've set up your libraries, or it won't if you've disabled it.

iOS frameworks _require_ code signing, though, so there's really no choice. But @gfontenot is right that Xcode will re-sign them when copied.

**Comment by jeffh** [comment]
Nimble 1.0.0-rc1 now includes pre-built binary. Thanks everyone! Reopen or file more issues if this is still a problem.
