### ISSUE TITLE
CocoaPods v13.4.0

### ISSUE THREAD

**Issue by michaeldclifford** [Quick/Nimble#1152]
The latest version of **Nimble** (13.4.0) doesn't appear to have made it to CocoaPods ([_see CocoaPods > Specs > Nimble_](https://github.com/CocoaPods/Specs/tree/master/Specs/d/c/d/Nimble)).

- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```ruby
  pod 'Nimble', '13.4.0'
```

### What did you expect to happen?

The pod is installed

### What actually happened instead?

```sh
[!] CocoaPods could not find compatible versions for pod "Nimble":
  In Podfile:
    Nimble (= 13.4.0)
```

### Environment

CocoaPods 1.15.2

**Comment by younata** [comment]
It's released now. Thanks for the heads up. I didn't notice that my release script had failed.

**Comment by michaeldclifford** [comment]
Thank you 🙂
