### ISSUE TITLE
Missing required module 'Testing' when trying to run UI Tests

### ISSUE THREAD

**Issue by Ripcord715** [Quick/Nimble#1157]
- [√ ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I tried to run my UI tests.

### What did you expect to happen?

I expected them to run.

### What actually happened instead?

The build fails and tells me "Missing required module 'Testing'". I created a simple UI test for my app not using Nimble matchers, when I run the test without importing Nimble, the test runs and passes as expected. When I import Nimble, it fails with the error above.

### Environment

List the software versions you're using:

- Quick: 7.6.2
- Nimble: 13.5.0
- Xcode Version: Version 16.0 (16A242d)
- Swift Version: 18.0?

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager 6.0.0-dev
We also use CocoaPods, but not for Quick or Nimble, just in case it matters.

### Project that demonstrates the issue

'''
import Nimble
import XCTest

final class NimbleTestUITests: XCTestCase {

    override func setUpWithError() throws {

        continueAfterFailure = false
    }

    @MainActor
    func testExample() throws {

      let app = XCUIApplication()
      app.launch()
    }

}
'''
Thank you for looking at this! I have included a screenshot below as well, from a different project:
<img width="1728" alt="Screenshot 2024-09-23 at 12 13 02 PM" src="https://github.com/user-attachments/assets/a22df8c4-dbc6-42a0-ab95-a3fecd1c58f5">

**Comment by fraune** [comment]
Hello,

I have also experienced this issue.

I have created a new repository to demonstrate the configuration and build error.

https://github.com/fraune/IssueDemo1157

I hope this helps :)

**Comment by Primecutz** [comment]
Hi!

Also ran into this issue. Downgrading to 13.4.0 seems to work for me.

It also looks like this is a similar issue with a possible fix: https://github.com/pointfreeco/swift-snapshot-testing/discussions/901#discussioncomment-10605497

**Comment by fraune** [comment]
I agree with @Primecutz that 13.4.0 is the latest version that works.

**Comment by younata** [comment]
This should now be fixed with the just-released 13.6.0 version of Nimble.
