### ISSUE TITLE
Expect Exceptions

### ISSUE THREAD

**Issue by silkentrance** [Quick/Nimble#117]
Since Swift has no inherent support for dealing with exceptions, I have created a small framework [vibeswift/SXCTAssertions](https://github.com/vibeswift/SXCTAssertions) that adds missing assertions such as SXCTThrows and so on.

How about integrating that one into your framework on an optional basis? I would be willing to implement the required expectations such as expect(expression).to(throw(...)) and so on in order for this to integrate into Nimble.

How about it?

**Comment by silkentrance** [comment]
Arrgh, just forget it, it is already included :grin:

**Comment by modocache** [comment]
Thanks anyway, @silkentrance! :tulip:
