### ISSUE TITLE
Identity checking tests no longer compile on 13.7.0

### ISSUE THREAD

**Issue by stodirascu** [Quick/Nimble#1182]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

Seems the current 13.7.0 made our tests stop building, namely due to these changes:

```
-public func be(_ expected: AnyObject?) -> Matcher<AnyObject> {
+public func be<T: AnyObject>(_ expected: T?) -> Matcher<T> {
```

We have a test checking whether a delegate (of a protocol type) is identical to an expected object:

```swift
protocol OurDelegate: AnyObject { }
...
var delegate: (any OurDelegate)?
...
expect(delegate).to(be(someObject))
```

which is a valid scenario imho.

@younata would it be possible to revert?

**Comment by younata** [comment]
Thanks for catching this! I just put up https://github.com/Quick/Nimble/pull/1183 to address. I'll release Nimble 13.7.1 with it later today.

**Comment by stodirascu** [comment]
Thanks for that 🙌
