### ISSUE TITLE
Problem with beAnInstanceOf matcher

### ISSUE THREAD

**Issue by pfitz** [Quick/Nimble#121]
Hi there. When I try to use the beAnInstanceOf() matcher Xcode always complains

>  Cannot invoke 'it' with an argument list of type '(String, () -> _)'

Here is my simplified spec: 

```swift
class FBLikesSpec: QuickSpec {
    override func spec() {
        describe("FBLikes") {
            context("whein filled with dummy data"){
                var likes: FBLikes!
                beforeEach {
                    likes = FBLikes.dummyLikes()
                }
                it("should have a valid FBPaging property") {
                    expect(likes.paging).to(beAnInstanceOf(FBPaging))
                }
            }
        }
    }
}
```

What am I doing wrong? Any idea how to fix this?

**Comment by jeffh** [comment]
What type is FBLikes? Is it an objective-c based or swift based type?

**Comment by pfitz** [comment]
FBLikes is an swift type. Do I have to implement some special methods?

**Comment by jeffh** [comment]
The Swift compiler ensures proper types that makes beAnInstanceOf redundant. The compiler doesn't give a great error, but Nimble only supports objective-c types for Objective-C based types.

This is a duplication issue of https://github.com/Quick/Nimble/issues/119.

**Comment by pfitz** [comment]
Doh! Guess im a little bit used to Objective-C :) Thanks.

**Comment by jeffh** [comment]
No worries @pfitz.

I think it's worthy to try and surface this more usefully than the current compiler errors Swift is. I've opened that as another issue: #123.
