### ISSUE TITLE
Help ! Test fails because: Stall on main thread

### ISSUE THREAD

**Issue by marciok** [Quick/Nimble#122]
Hello, 
I'm testing a view controller, for eg:
```Objective-C
beforeEach(^{
  navigationController = [storyboard instantiateViewControllerWithIdentifier:@"etc.."];
  navigationContrlller.viewControllers = @[myViewController];

  UIWindow *window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  window.rootViewController = navigationController; // <- The Problem. 
 
  [window makeKeyAndVisible]; 

//... 
})
```
```Objective-C
 it(@"should be a a signing view controller",^{
  expect(navigationController.topViewController).toEventually(beAKindOf([SignInViewController class]));
});
```
But it  fails: `expected to match (Stall on main thread)., got <<SignInViewController: 0x7a7284d0>>`

After some research, I understood that this is happening because I'm [adding too many tasks to the main run loop](https://github.com/jeffh/Nimble/commit/9e01e161e1499029d34ec33815cc525a4dcf87a2) specifically at this line:  `window.rootViewController = navigationController;`  if its removed then I don't get "Stall on main thread" but still fails because I can't push or present any view controller because is not part of the view hierarchy.

Any suggestion on how to make this test work ?

Thanks a lot.

**Comment by jeffh** [comment]
Is your storyboard particularly large?

An alternative is to simply advance the runloop yourself:

```objc
[[NSRunLoop mainLoop] runUntilDate:[NSDate date]]
```

**Comment by marciok** [comment]
Thanks a lot @jeffh ! :star2: 
I moved the view controller out of the storyboard but I was still getting `Stall on main thread`.

I ended up increasing the run time on the mainRunLoop and it worked.

Thanks again. :+1:  :smile:

**Comment by priteshshah1983** [comment]
Can you please share more details? What changes did you exactly make? An example, if possible, would be great!

Thanks in advance!
