### ISSUE TITLE
dyld: Library not loaded: @rpath/Nimble.framework/Nimble

### ISSUE THREAD

**Issue by ypwu1** [Quick/Nimble#128]
When I import the Nimble framework, it crash with this error, 
dyld: Library not loaded: @rpath/Nimble.framework/Nimble
Reason: image not found

I know this bug  has been raised somewhere else, just can't find the solution.

Environment:
yosemite, xcode6.3 swift 1.2
Podfile:

use_frameworks!
# Main target
target 'trimforlife' do
	pod 'Mixpanel', '~> 2.5.4'
	pod 'AFNetworking', '~> 2.4'

end

# Test target
target 'trimforlifeTests', :exclusive => true do
  pod 'Mixpanel', '~> 2.5.4'
  pod 'AFNetworking', '~> 2.4'
  pod 'Nimble', '~> 0.4.0'
  pod 'Quick', '~> 0.3.1'
end

**Comment by marciok** [comment]
Hi,
Did you try to clear your project folder  ```Command + Option + Shift + k``` and reset the simulator (at menu bar ```iOS Simulator -> Reset Content and Settings``` ?

**Comment by manumax** [comment]
I had exactly the same problem with CocoaPods 0.37.1. With CocoaPods 0.36.1 all works fine. I think it's related with https://github.com/CocoaPods/CocoaPods/issues/3440.

**Comment by marciok** [comment]
Strange, I'm using CocoaPods 0.37.1 and it's fine. 

@manumax did you mange to work around this issue or did you rollback to CocoaPods 0.36 ?

**Comment by manumax** [comment]
I spent a full afternoon trying to understand what was going on and eventually I decided to rollback to 0.36. To clarify, it happened on a project of mine that was already using CocoaPods 0.36. When I decided to upgrade to 0.37, I started to get the error (I did the full clear of the project folder and derived data but I didn't reset the simulator). If I'll have some spare time later I could try again on a brand new project.

**Comment by manumax** [comment]
I did a few experiments and you're right, now it seems to work even with CocoaPods 0.37.1. I did reset the simulator, maybe that was the problem.

**Comment by jeffh** [comment]
Hey @ypwu1, did the suggestions discussed here help?

**Comment by jeffh** [comment]
Closed, Please reopen if this is still an issue. Thanks everyone for helping to diagnose. :+1:

**Comment by zbeckman** [comment]
This has popped up again, at least it looks the same to me. It is only happening in a new test target that we added to the project, but no matter what I do... can't seem to get the dyld to load:

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/zbeckman/Library/Developer/CoreSimulator/Devices/FCFAAFBF-1AB4-4223-9BCC-CA91CBDE96DC/data/Containers/Bundle/Application/DB1E94B2-3521-46CA-AB5A-A524BD9E14D6/Glimpulse.app/Frameworks/Nimble.framework/Nimble
  Reason: image not found
