### ISSUE TITLE
raiseException matcher doesn't work with objc code

### ISSUE THREAD

**Issue by gavrix** [Quick/Nimble#134]
Following matcher always fails

```
        expect(^{
            @throw [NSException exceptionWithName:@"" reason:@"" userInfo:nil];
        }).to(raiseException());
```

Either I don't understand something basic here or there's a clear problem with matcher.

**Comment by jeffh** [comment]
Hey @gavrix,

See [Lazily Computed Values](https://github.com/Quick/Nimble#lazily-computed-values), it should be something like this:

```objc
expectAction(@throw [NSException exceptionWithName:@"" reason:@"" userInfo:nil]).to(raiseException());
```

That being said, the example in the "Exceptions" section isn't great and needs to be improved. 
Although I do like the syntax that you're proposing for ObjC ;).

**Comment by gavrix** [comment]
ok, got that. Thanks.
yeah, coming to Nimble from Specta/Expecta background, and they were using that syntax, so I naively tried it without researching the Nimble sources.

**Comment by gavrix** [comment]
BTW, having `@throw` inside `expectAction` macro breaks it, doesn't compile. Definitely makes sense to migrate to evaluate given blocks instead.

**Comment by gavrix** [comment]
by replacing 
```
#define expectAction(...) NMB_expect(^id{ (__VA_ARGS__); return nil; }, __FILE__, __LINE__)
```
with 
```
#define expectAction(x) NMB_expect(^id{ x(); return nil; }, __FILE__, __LINE__)
```

you can have that kind of syntax
```
expectAction(^{
    @throw [NSException exceptionWithName:@"" reason:@"" userInfo:nil];
}).toEventually(raiseException());
```
