### ISSUE TITLE
The commit matching v1.0.0-rc.1 got also tagged with version 2.0.0-rc.1

### ISSUE THREAD

**Issue by sync** [Quick/Nimble#135]
please remove tag 2.0.0-rc.1 from dc7c527de09228aaa231108e9e3e17f46cdb71ff, if not Carthage will always fetch version 2.0.0 instead of 1.0.0 causing compile error with Xcode 6

see https://github.com/Quick/Nimble/commit/dc7c527de09228aaa231108e9e3e17f46cdb71ff

![screen shot 2015-06-12 at 10 51 49 am](https://cloud.githubusercontent.com/assets/21725/8121609/45a9f0aa-10f1-11e5-82fe-94bcca07cb95.png)

**Comment by joshuatbrown** [comment]
I'm having the same issue and would love to help if I can.

**Comment by modocache** [comment]
I don't get it. Locally, the tag is pointing to fa73feeb156d8af7f47ae94dde07f1f7847bb1a3, which is the correct commit. Why does dc7c527de09228aaa231108e9e3e17f46cdb71ff also appear as if it's tagged with [v2.0.0-rc.1](https://github.com/Quick/Nimble/releases/tag/v2.0.0-rc.1) in the GitHub UI?

https://github.com/Quick/Nimble/releases/tag/v2.0.0-rc.1 itself on the GitHub UI shows that it's pointing to fa73feeb156d8af7f47ae94dde07f1f7847bb1a3.

Perhaps someone can reach out to GitHub for support? Locally, Git behaves as expected.

**Comment by paulyoung** [comment]
I'll email GitHub support on this one.

**Comment by modocache** [comment]
Thanks, @paulyoung! That'll probably be more effective than [my 140 characters](https://twitter.com/modocache/status/609478612824268800). :wink:

**Comment by jspahrsummers** [comment]
This isn't an issue with GitHub, Quick, or Nimble. See https://github.com/Carthage/Carthage/issues/544#issuecomment-111757571.

**Comment by paulyoung** [comment]
@jspahrsummers thanks for clearing that up!

> Why does dc7c527 also appear as if it's tagged with [v2.0.0-rc.1](https://github.com/Quick/Nimble/releases/tag/v2.0.0-rc.1) in the GitHub UI?

Can you offer any insight on that? I think that only added to the confusion here.

**Comment by modocache** [comment]
I believe that's explained by https://twitter.com/jspahrsummers/status/609547269533097984.

It's unfortunate that Carthage doesn't handle trailing characters, although not doing so makes a lot of sense to me. I'm actually not a fan of "RC" versions, but I figured a Swift 2.0-compatible version of Nimble v1.0.0-rc.1 should be v2.0.0-rc.1.

In any case, this seems like a non-issue from Nimble's point of view, so I'm closing this. Thanks anyway, @sync! :+1:
