### ISSUE TITLE
Release Notes for v1.0.0-rc.1 have incorrect installation instructions for Carthage

### ISSUE THREAD

**Issue by joshuatbrown** [Quick/Nimble#137]
The Release Notes for v1.0.0-rc.1 contain the following note:

> **Note to Carthage Users:** You must explicitly give this version for Carthage to install.
github "Quick/Nimble" == 1.0.0

This is incorrect, per [Carthage issue 544](https://github.com/Carthage/Carthage/issues/544#issuecomment-111757571). It should say the following:

> **Note to Carthage Users:** You must explicitly give this version for Carthage to install.
github "Quick/Nimble" "v1.0.0-rc.1"

This was confusing to me as a Nimble and Carthage user - I couldn't figure out why Carthage was fetching and building the wrong version of Nimble.

**Comment by jeffh** [comment]
Thanks @joshuatbrown, I've updated the releases with the new changes :+1:
