### ISSUE TITLE
Using Nimble without XCTest

### ISSUE THREAD

**Issue by tjarratt** [Quick/Nimble#144]
I'm trying to use Nimble to write some tests in swift without Quick or XCTest. Currently I'm using [Cedar](https://github.com/pivotal/cedar/tree/swift-spec-runner) to run my tests as a "spec application target", so I don't have a test bundle, and I don't use XCTest at all.

We have [an example project](https://github.com/Jdavid1001/swift_cedar) that has a Spec target using Cedar and Nimble, but it currently needs to link against and load XCTest, because using Nimble as a dynamic framework requires us to load XCTest as well.

We wrote our own [Nimble assertion handler to interop with Cedar](https://github.com/Jdavid1001/swift_cedar/blob/master/Specs/NimbleCedarAssertionHandler.swift), which replaces the default assertion handler `NimbleXCTestHandler`. It seems that this is the only place in Nimble where XCTest is used, and I'm curious if it would even be possible to decouple Nimble further from XCTest, given that we don't even want to use the XCTest assertion handler.

Is that even remotely possible, or is that a pipe dream?

**Comment by briancroom** [comment]
Another interesting use case for this would be the ability to use Nimble matchers in a playground as a lightweight TDD environment. Continuous feedback!

**Comment by jeffh** [comment]
Hey guys,

I haven't looked much into making it completely devoid from XCTest, but it's linked to support the primary use case of making test writing for apps easier. I do want to eventually divorce from explicit XCTest linkage before open source swift is released, so it's on the horizon.

There are some avenue of options that I haven't tried yet, but it might be worth exploring:

- Using Weak Linking to refer to XCTest. This might require breaking some initialization / bootstrap work for Nimble. That is acceptable if it means XCTest can be optionally linked.
- Use C-styled runtime magic to load/lookup the XCTest function at runtime. I'm not too thrilled about this option TBH.
- Separate the XCTest integration to a separate library. I rather have the Nimble project (or at least preserve the way people install Nimble) integrate with XCTest and separate out the "core" to a separate project. Although this creates ongoing managerial burden I'd like to avoid with the first option if possible.

**Comment by tjarratt** [comment]
Thanks for sharing your thoughts, @jeffh. I share the same feelings about runtime magic and want to preserve the existing use-case for 99.999999% of Nimble users.

I'll have to take a look at what Weak Linking against XCTest would look like from Swift, since that sounds like the best option, although my gut tells me that option 3 (breaking out a "Nimble-core", and keeping the existing Nimble integrated with XCTest) will probably be the most likely to succeed, given what I know about XCTest today.

**Comment by modocache** [comment]
This is something I'm very interested in accomplishing, both for Nimble and Quick. Thanks for the discussion, everyone! :heartbeat: 

> Separate the XCTest integration to a separate library. I rather have the Nimble project (or at least preserve the way people install Nimble) integrate with XCTest and separate out the "core" to a separate project.

I believe https://github.com/Quick/Quick/pull/287 is along the lines of what @jeffh and @tjarratt are proposing here. I may be mistaken, but wouldn't users interested in XCTest integration have to import both Nimble.framework and NimbleCore.framework in this case? If not, I think this is a great direction to go in.

> Using Weak Linking to refer to XCTest. This might require breaking some initialization / bootstrap work for Nimble. That is acceptable if it means XCTest can be optionally linked.

It looks like #146 is weak linking, right? I'll read through what's going on there, but could you explain what you mean by "acceptable", @jeffh?

> - Use C-styled runtime magic to load/lookup the XCTest function at runtime. I'm not too thrilled about this option TBH.

Honestly this option is out of my depth. Could you explain what this would look like, or link to some resources to learn more?

**Comment by jeffh** [comment]
@modocache,

[Weak linking](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html) is the best option simply because it covers both cases without having restore to making another framework. Recent Xcode betas seem to better support weak linking swift code.

At worse, existing users of Nimble with a weakly linked XCTest only need to explicitly link XCTest.
#146 is acceptable if there is minimal intrusive change for existing users (aka - having to explicitly linking to XCTest) and supports the case @tjarratt and @briancroom intend - using Nimble without having to link to XCTest.

>> Use C-styled runtime magic to load/lookup the XCTest function at runtime. I'm not too thrilled about this option TBH.

> Honestly this option is out of my depth. Could you explain what this would look like, or link to some resources to learn more?

Using [dlopen](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html) and it's family of c functions allows you to manually invoke the dynamic linker/loader. This technically allows us to emulate weak linking via code. But `dlopen` may not be supported / allowed by the simulator or actual devices on iOS, since it's a load-level api. I haven't really tried.

**Comment by jeffh** [comment]
This should be already implemented since Nimble 2.0.0. Closing. Thanks guys for all the hard work!
