### ISSUE TITLE
Expectations should allow specifying a custom failure message

### ISSUE THREAD

**Issue by jeffh** [Quick/Nimble#148]
A test writer should be able to override expectation failure messages. This is more useful for E2E / integration test where an expectation is usually more indicative of a larger failure.

```swift
// Xcode inlines "Failure - Hey these aren't equal!"
// instead of the matcher's "Failure - Expected to equal <2>, got <1>"
expect(1).to(equal(2), description: "Hey these aren't equal!")
```

**The matcher's original failure message should be a second line in the failure**. This allows users to view the original matcher's message by viewing test run logs. The full error message should look like:

```
Hey these aren't equal!
Expected to equal <2>, got <1>
```

This feature should be added to all assertion methods:

- to()
- toNot()
- notTo()
- toEventually()
- toEventuallyNot()
- toNotEventually()

For Objective-C, this requires adding new property-blocks with a postfix:

- toWithDescription()
- toNotWithDescription()
- notToWithDescription()
- toEventuallyWithDescription()
- toEventuallyNotWithDescription()
- toNotEventuallyWithDescription()

Checklist:

- [ ] Swift
  - [ ] to()
  - [ ] toNot()
  - [ ] notTo()
  - [ ] toEventually()
  - [ ] toEventuallyNot()
  - [ ] toNotEventually()
  - [ ] Update README
- [ ] Objective-C
  - [ ] toWithDescription()
  - [ ] toNotWithDescription()
  - [ ] notToWithDescription()
  - [ ] toEventuallyWithDescription()
  - [ ] toEventuallyNotWithDescription()
  - [ ] toNotEventuallyWithDescription()
  - [ ] Update README

**Comment by abbeycode** [comment]
This would be super useful!

**Comment by abbeycode** [comment]
I'm taking a look at implementing this. Should the pull request go to the `swift-2.0` branch?

**Comment by jeffh** [comment]
Yes! :+1:
