### ISSUE TITLE
Add failWithMessage() for Objective-C

### ISSUE THREAD

**Issue by jeffh** [Quick/Nimble#150]
Objective-C should support failing with a message like the Swift API:

```objc
failWithMessage(@"This always fails");
```

**Bonus Credit**: Instead of `failWithMessage` macro, overload the `fail` macro to optionally accept a message:

```objc
// bonus: both of these lines should work.
fail(@"The always fails");
fail();
```

**Comment by romankl** [comment]
PR #163 added this macro.

**Comment by jeffh** [comment]
Thanks again @romanki
