### ISSUE TITLE
Cannot find an overload for 'equal' that accepts an argument list of type '([String?])'

### ISSUE THREAD

**Issue by ratkins** [Quick/Nimble#152]
![nimble](https://cloud.githubusercontent.com/assets/528356/8797467/7ee5f48e-2f93-11e5-8cdc-12cbb24e532f.png)

Nimble doesn't seem to support matching Arrays (Sequences?) of optional types. contains() isn't what I want here, my intention is to match on the exact items in the exact order. Am I missing something?

**Comment by jeffh** [comment]
Hey @ratkins. Nope, you're not missing anything. Nimble doesn't currently add any extra `==` implementations for types not owned by Nimble. Swift's stdlib doesn't support equality of arrays of optionals. It would be good to file a radar for this.

Secondarily, we could add equality. Investigation is required to see if implementing `==` for array of optionals causes problems when other libraries / applications also implement it. Alternatively, an nimble-specific overload could be defined.

**Comment by ratkins** [comment]
I would think a Nimble-specific overload would be safer?

**Comment by jeffh** [comment]
Yes, a Nimble-specific one is preferred.

**Comment by abbeycode** [comment]
I'm hitting a need for this too now. +1

**Comment by jeffh** [comment]
Closing. This is now in v3.1.0. Thanks everyone!
