### ISSUE TITLE
New Release for Xcode 7b4

### ISSUE THREAD

**Issue by dduan** [Quick/Nimble#156]
It seems that Xcode 7 beta 4 compatibility has been merged from Quick/Nimble#153. Perhaps it's time to release 2.0.0-rc.2, so that Carthage users can build with the latest Xcode.

**Comment by jeffh** [comment]
Hey @dduan,

Thanks for reminding me to push another release. I'll cut a release once I fix my CI builds.

**Comment by jeffh** [comment]
Release cut. Closing
