### ISSUE TITLE
Add 'haveCountOf' matcher

### ISSUE THREAD

**Issue by fatuhoku** [Quick/Nimble#158]
With Expecta, I used to write:

```objc
expect(array).to.haveCount(2);
```

But with Nimble you're forced to say:

```objc
expect(@([array count])).to(equal(@2));
```

A bit more cumbersome. Who else wants something like this?

**Comment by jeffh** [comment]
Good idea :+1:.

I tend to use the latter form because I personally see it as less implementation magic, but I don't really have strong opinions either way.

**Comment by jeffh** [comment]
Feature was merged sometime ago, and I forgot about this cross-project issue. Closing. Thanks for filing an issue!

**Comment by fatuhoku** [comment]
:+1:
