### ISSUE TITLE
Changelog v2.0.0-rc.2: throwError syntax

### ISSUE THREAD

**Issue by mrackwitz** [Quick/Nimble#159]
The syntax in the [changelog](https://github.com/Quick/Nimble/releases/tag/v2.0.0-rc.2) for the `throwError` command doesn't match the actual syntax:

>    swift: Added throwAnError() matcher for verifying the behavior of closures that throw an error:
>
> ```
> expect { try somethingDangerous() }.to(throwAnError())
> ```

**Comment by jeffh** [comment]
Sorry about that. Still had the old syntax stuck in my head. Updated! Thanks for filling an issue @mrackwitz! :smile:

**Comment by ikesyo** [comment]
This is re-raised in final [v2.0.0](https://github.com/Quick/Nimble/releases/tag/v2.0.0) release.

**Comment by jeffh** [comment]
Updated. Thanks @ikesyo, I can't seem to not cause this error :cry:.
