### ISSUE TITLE
"Could not build module 'Nimble'" when linking Nimble from Cocoapods... but tests pass

### ISSUE THREAD

**Issue by fatuhoku** [Quick/Nimble#161]
Really confused about this one... :S

![screen shot 2015-07-28 at 16 57 41](https://cloud.githubusercontent.com/assets/430233/8936436/2b9b1ca2-354a-11e5-97ac-74748850ba20.png)

**Comment by brentleyjones** [comment]
Is this Xcode 7? I've noticed it in Xcode 7, in my Swift tests. If I move a different module above it, like the module I'm testing, it errors there instead.

**Comment by brentleyjones** [comment]
Also, I don't use CocoaPods, I have Nimble in my workspace as a project.

**Comment by fatuhoku** [comment]
No this is Xcode 6. I use Cocoapods.

**Comment by jeffh** [comment]
@fatuhoku Did you try full cleaning the project? Xcode is inconsistent with modules and tends to persist these errors longer than it should.

**Comment by tomomura** [comment]
I face same problem.

Also, I use Xcode6 and CocoaPods.

**Comment by fatuhoku** [comment]
@jeffh I'm pretty sure I tried cleaning and rebuilding before writing this issue. The error exists only for Nimble repeatedly, and not other modules if I remember. It's been a while since I've had the need.

**Comment by programmerdave** [comment]
I got it to sort of work by setting the EMBEDDED_CONTENT_CONTAINS_SWIFT to YES directly on the Pod Target for Nimble. @fatuhoku  Can you try that?

**Comment by appleios** [comment]
I've tried setting EMBEDDED_CONTENT_CONTAINS_SWIFT to YES, but it doesn't solve the problem.

**Comment by briancroom** [comment]
This issue is pretty stale now, and I'm not observing the problem. I'm going to close it, but feel free to reopen it @fatuhoku if you are still running into it!
