### ISSUE TITLE
Add "throws" matcher

### ISSUE THREAD

**Issue by modocache** [Quick/Nimble#162]
Prior art: https://realm.io/news/testing-swift-error-type/ :wink: -- thanks, @mrackwitz!

Nimble should provide a built-in matcher that allows me to write:

```swift
expect(try somethingThatThrows()).to(throw())
expect(try somethingThatThrows()).to(throw(error: MyErrorEnum.SpecificErrorCase))
```

**Comment by mrackwitz** [comment]
What exactly are you missing from the new [`throwError` matcher](https://github.com/Quick/Nimble#swift-error-handling)? (see #143)

**Comment by modocache** [comment]
Oops! Sorry, hadn't noticed that one.
