### ISSUE TITLE
XCTest.framework/XCTest' does not contain bitcode

### ISSUE THREAD

**Issue by akhilsuri** [Quick/Nimble#170]
Relates to : https://github.com/Quick/Nimble/issues/165

Using Nimble (2.0.0-rc.2)
Using Quick (0.5.1)

The xcode project is not working as it throws error -
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Also check the attached image for more reference.
![screen shot 2015-08-24 at 8 07 00 pm](https://cloud.githubusercontent.com/assets/7919804/9443024/776cf9c2-4a9c-11e5-9391-bb236eb08f03.png)

**Comment by akhilsuri** [comment]
@jeffh Need help

**Comment by romankl** [comment]
Hi @akhilsuri, bitcode should be disabled since d551d29, but it's not released using cocoa pods. You could include the nimble/ quick branch swift-2.0 branch as a sub module to get rid of the error. 

@jeffh  time for a new rc?

**Comment by akhilsuri** [comment]
@romankl Thanks for update.

**Comment by jeffh** [comment]
Thanks for the discussion, Nimble hasn't cut a new release since Nimble's test suite currently fails in Xcode 6 beta 6. I'll get around to addressing it in the next few days when I have time before cutting a release.

**Comment by akhilsuri** [comment]
@jeffh Thanks for replying, Nimble has build issues on Xcode 7 beta6 as I checked on them yesterday. Will be looking forward for a new release.

**Comment by akhilsuri** [comment]
@jeffh The build is not executing when I try to build the app on iphone 6 iOS 8.2 for debugging. It is throwing the same error as stated above. Reopening the ticket and will wait for new release. Thanks

**Comment by jeffh** [comment]
@akhilsuri, are you having this issue on Nimble's `swift-2.0` branch? I don't see this issue on my machine on my machine.

**Comment by zbeckman** [comment]
@jeffh I'm seeing this too... but only on deployment to a device. The problem is occurring on the swift-2.0 branch but only when trying to build for a device. This is on Xcode 7 beta 6, with the latest pull from the swift-2.0 branch. (eg., when I try to build for my iPhone 6, I get the following error):

Ld /Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphoneos/Nimble.build/Objects-normal/armv7/Nimble normal armv7
    cd /Users/zbeckman/Projects/XXX/iOS/project/XXX/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Products/QA\ 1-iphoneos -F/Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Products/QA\ 1-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -filelist /Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphoneos/Nimble.build/Objects-normal/armv7/Nimble.LinkFileList -install_name @rpath/Nimble.framework/Nimble -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -fembed-bitcode-marker -framework XCTest -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphoneos/Nimble.build/Objects-normal/armv7/Nimble.swiftmodule -framework Foundation -framework XCTest -single_module -compatibility_version 2 -current_version 2.0.0 -Xlinker -dependency_info -Xlinker /Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphoneos/Nimble.build/Objects-normal/armv7/Nimble_dependency_info.dat -o /Users/zbeckman/Library/Developer/Xcode/DerivedData/XXX-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/Pods.build/QA\ 1-iphoneos/Nimble.build/Objects-normal/armv7/Nimble

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jeffh** [comment]
Thanks @zbeckman, I was able to reproduce. I'll get a fix in soon

**Comment by zbeckman** [comment]
Awesome – Looking forward to the update. Our app is camera heavy which makes it impossible to test in the simulator. :)

**Comment by deemadden** [comment]
Thanks for this @jeffh .  Nice to see you in the group here, @zbeckman !  Hope you are doing well.

**Comment by c0diq** [comment]
It's still an issue for Carthage. Why is Bitcode simply disabled at the project level?

**Comment by ikesyo** [comment]
No, this is  already addressed in Carthage [0.17](https://github.com/Carthage/Carthage/releases/tag/0.17)

> Frameworks will be built for the simulator only on platforms that require bitcode when bitcode is disabled

and Nimble [v4.1.0](https://github.com/Quick/Nimble/releases/tag/v4.1.0)

> Bitcode is now disabled for the tvOS platform

**Comment by c0diq** [comment]
ah thanks!
