### ISSUE TITLE
Using beCloseTo with NSDate

### ISSUE THREAD

**Issue by abbeycode** [Quick/Nimble#171]
I would like to be able to write the following (Swift):

``` Swift
expect(aDateObject).to(beCloseTo(NSDate())
```

But, it looks like there is no overload that handles dates. I get this compiler error:

> Cannot invoke 'to' with an argument list of type ''NMBObjCBeCloseToMatcher!)'

Instead, I have to write this, which is much more difficult to read:

``` Swift
expect(aDateObject.timeIntervalSinceReferenceDate).to(beCloseTo(NSDate().timeIntervalSinceReferenceDate))
```

It looks like the easiest way to solve this would be to add an extension to `NSDate` that implements `NMBDoubleConvertible` by calling `timeIntervalSinceReferenceDate`.

**Comment by abbeycode** [comment]
I tried this out in my own code, and it did the trick:

``` Swift
extension NSDate: NMBDoubleConvertible {
    public var doubleValue: CDouble {
        get {
            return self.timeIntervalSinceReferenceDate
        }
    }
}
```

**Comment by jeffh** [comment]
Could you submit a PR with tests? Sounds great!

**Comment by abbeycode** [comment]
I committed a solution, but I wish the reported failure had formatted dates, instead of the opaque NSTimeInterval:

> expected to not be close to <462296591.0000> (within 10.0000), got <462296580.0000>

What's the easiest way to achieve that? Should I overlose the `beCloseTo` matcher with explicit date support that formats the message appropriately?

**Comment by jeffh** [comment]
Yeah, although it might be better to improve the 'NMBDoubleConvertible' protocol to support this. Although I don't remember if nsdate printouts are as precise to the millisecond. Nothing is more annoying than hiding the source of the inequality.





—

**Comment by abbeycode** [comment]
Ah, that makes sense. I'll look into it (and make sure I include the fractional seconds)
