### ISSUE TITLE
How to perform structural matching?

### ISSUE THREAD

**Issue by angerman** [Quick/Nimble#173]
Given a more complex object graph, that could be walked recursively, how would one write a matcher for this?
Right now I'm walking within the `NonNilMatcherFunc` the evaluated `actualExpression` and the `expectedValue`, setting the `failureMessage`, but this ends up with errors like:

`expected to <failureMessage.postfixMessage>, got <expectedValue.description>`

hence if I choose `failureMessage.postfixMessage` to be `expect identical some.key.path: <expected.value>, got: <found.value>`, this turns out to look very confusing.

**Comment by jeffh** [comment]
I'm not sure what you're trying to get at. Do you have an short example?

If you're just concerned about how to print the error message, you can also completely override the error message using [failureMessage.stringValue](https://github.com/Quick/Nimble/blob/swift-2.0/Nimble/FailureMessage.swift#L14-L25).

**Comment by angerman** [comment]
Ok. Sorry for not being clear. Let's assume the following code: (basically building a bunch of product and sum types)

```
enum E1 {
    case E1A, E1B, E1C, E1D
}
enum E2 {
    case E2A, E2B
}
struct A {
    var e1 : E1
    var e2 : E2
}
struct B {
    var e1 : E1
}
struct C {
    var s1 : A
    var s2 : B
    var e2 : E2
}

let c1 = C(s1: A(e1: .E1A, e2: .E2B), s2: B(e1: .E1D), e2: .E2B)
let c2 = C(s1: A(e1: .E1B, e2: .E2B), s2: B(e1: .E1A), e2: .E2A)
```

now, I'd like to create an equality matcher `==` for `C`. So I can run
```expect(c1) == c2```.

Within the matcher I'd basically prefer to say:
```
expect(expectedValue.s1) == actualValue.s1
expect(expectedValue.s2) == actualValue.s2
```
in the equality matcher for `A`, I'd like to say:
```
expect(expectedValue.e1) == actualValue.e1
expect(expectedValue.e2) == actualValue.e2
```
and so on. 

e.g. basically breaking down the equality of the structure recursively
into each part, but still be able to write at a high level: `expect(c1) == c2` and then have that fail.
Best case would obviously be if one could hand down the actual compared name, to produce something like a keypath in the failure.

I'm just not sure how to this could be implemented.

Hope this makes more explanation makes it clearer.

**Comment by jeffh** [comment]
Thanks for the clarification.

It depends on what test you're writing: for testing equality for test types or to simply test value equality only for tests.

If you're testing equality, you'll need to either write a matcher, define a helper function, or compare exhaustively for each leaf-value you have.

Otherwise, your options are to implement the `==` operator. You can keep them high-level if you implement `Equatable` for all your own types.

If you want to be explicit that it should only be available for tests, overload Nimble's `==` and `equals` matcher functions. I encourage you to see the [Nimble's equals source](https://github.com/Quick/Nimble/blob/swift-2.0/Nimble/Matchers/Equal.swift#L126-L132) for examples.

**Comment by angerman** [comment]
I did write a matcher similar to the following:
```
public func equalC(expectedValue: C) -> NonNilMatcherFunc<C> {
    return NonNilMatcherFunc { actualExpression, failureMessage in
        if let actualValue = try actualExpression.evaluate() {
             // Ideally I'd like to write:
             //   expect(expectedValue.e2) == actualValue.e2 // given that E2 implementes Equatable.
             //
             // right now the only option I see is:
             if !(expectedValue.e2 == actualValue.e2) {
                 failureMessage.postfixMessage = "expected e2 to match: <\(expectedValue.e2)>, got <\(actualValue.e2)>"
             }
             // more structural equality tests here...
        }
    }
}
```

Idieally I'd write the tests the other way around. So that I have equality matcher for each leaf, and can compose them to build up a matcher for the whole structure.

What I fail to see is how one would compose matchers.

**Comment by ikesyo** [comment]
Closing this due to inactiviy.
