### ISSUE TITLE
XCode 7 Beta 6 Compile Issues

### ISSUE THREAD

**Issue by michaelfransen** [Quick/Nimble#175]
I'm wondering when the cocoapods will be updated with the latest code so there aren't compile issues. I notice that the commits are already there for disabling bitcode (https://github.com/Quick/Nimble/commit/852b38820dda24fd7114622f3bd423979c0226a3) and the joinWithSeperator issue (https://github.com/Quick/Nimble/commit/852b38820dda24fd7114622f3bd423979c0226a3).

**Comment by jeffh** [comment]
When Nimble's test suite actually passes, there are currently some issues related to iOS that my Xcode Server is experience. But since there seems to be an increase in server hanging, it taking a bit longer than normal to troubleshoot.

**Comment by jeffh** [comment]
Closing, I've pushed v2.0.0 RC 3.
