### ISSUE TITLE
This or that

### ISSUE THREAD

**Issue by zbeckman** [Quick/Nimble#176]
It would be incredibly helpful to be able to write:
```
expect(someThing).to(startWith("https://")).or(startWith("http://"))
```
I'm not aware of any way to model `or` conditions in Nimble as it stands now.

**Comment by jeffh** [comment]
Hey @zbeckman,

I'd like to understand more context behind `or`. Normally, it's preferred for tests to be explicit about what it's comparing against. In your example above, I'd expect `someThing` to be one of the given values.

**Comment by zbeckman** [comment]
The example I gave is something we have to deal with since our testing framework uses HTTPS for many transactions, but uses HTTP for some transactions.

However, here is one that's a bit more tricky (less predictable). Depending on the device being used, we might be dealing with an IPv4 or an IPv6 address. We use two different regular expressions to validate each one:
```
let IPv4Pattern = "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}(:[0-9]{0,3}){0,1}$"
let IPv6Pattern = "^(?:[A-Fa-f0-9]{0,4}:){7}[A-Fa-f0-9]{0,4}(:[0-9]{0,3}){0,1}$"
```
The easiest solution is to query the device information, and make sure it matches one of these two patterns (this would require adding a `matches` handle that compares to a regular expression, which would also be incredibly useful):
```
expect(deviceIP).to(match(IPv4Pattern)).or(match(IPv6Pattern))
```
Right now we do something like this instead (not exactly, I'm simplifying, but you get the idea)... This can work fine but is a little bit less elegant and readable:
```
expect(deviceIP.rangeOfString(IPv4Pattern, options: .RegularExpressionSearch) || deviceIP.rangeOfString(IPv6Pattern, options: .RegularExpressSearch)).to(beTruthy())
```

**Comment by jeffh** [comment]
You've convinced me, the alternatives are less ideal. I'm just not sure how the DSL should look. Some random ideas to ponder over:

```swift
// or on expectation
expect(value).to(equal(2)).or(equal(3))
// operator ?
expect(value).to(equal(2)) || equal(3)
```

```swift
// or matcher combinator ?
expect(value).to(or(equal(2), equal(3))
// looks better as an operator
expect(value).to(equal(2) || equal(3))
```

```swift
// or as a wrapper around expect
anyOf(
    expect(value).to(equal(2)),
    expect(value).to(equal(3))
)
// operator ?
expect(value).to(equal(2)) || expect(value).to(equal(3))
```

Something to sleep on.

**Comment by zbeckman** [comment]
My first instinct was to try this:
```
expect(value).to(equal(2) || equal(3))
```
Which didn't work, so I looked at if with a functional perspective, and tried this:
```
expect(value).to(equal(2)).or(equal(3))
```
I like the latter much more, I think. I'm not sure why. Probably because it does open up some interesting possibilities:
```
expect(value).to(match("\\w")).andNotTo(match("\\w{3}"))
```
And being a Scala/functional programmer at heart I tend to expect every function to return something I can operate on. The very last example (with `anyOf`) is interesting too.

Just more food for thought. I've written a short regular expression matching class, and added an infix `=~` operator, so that now our test looks like this:

```
it("matches correctly on an IP address") {
	expect(ip =~ RegularExpressions.IPv4Pattern).to(beTrue())
}

it("returns a good IP address") {
	expect((device.primaryIPAddress =~ RegularExpressions.IPv4Pattern) || (device.primaryIPAddress =~ RegularExpressions.IPv6Pattern)).to(beTruthy())
}
```
Of course the limitation here is that the failed case will report something like "expected X to beTrue()" which really doesn't tell me much. It would be great if we got back "expected X to match pattern '...'" but of course that would mean adding some kind of regex pattern matching to the expectations. Happy to share my regex class if interested (it's pretty trivial).

**Comment by zbeckman** [comment]
Just threw up a short gist so you can grab what you want from the regex class, if you want to create a similar matcher... https://gist.github.com/zbeckman/ef7ea36d70186e4dfdc5

**Comment by modocache** [comment]
Gomega, a matcher library for Go, added support for this in https://github.com/onsi/gomega/pull/108.

**Comment by jeffh** [comment]
This is now in v3.1.0. Closed. Thanks everyone for the contributions!
