### ISSUE TITLE
Make Async Expectations more deterministic

### ISSUE THREAD

**Issue by jeffh** [Quick/Nimble#177]
Nimble has flaky tests on slower machines :cry:.

It's related to the `pollBlock` abort feature when the main thread is backlogged with deferred messages that take a while to compute. This causes `NSRunLoop.runUntilDate` to run longer than expected. Nimble currently tries to stop the runloop if it's taking too long from another thread.

This sometimes occurs on travis but can be reliably reproduced on a mac mini that runs Xcode Server + all simulator devices.

This causes failures in `AsynchronousTest.swift`:

![screen shot 2015-08-30 at 7 29 28 pm](https://cloud.githubusercontent.com/assets/68616/9571115/85fa6078-4f4d-11e5-9f51-8a498d0310e8.png)

![screen shot 2015-08-30 at 7 29 23 pm](https://cloud.githubusercontent.com/assets/68616/9571116/881d31fa-4f4d-11e5-9b24-e366989deca6.png)

These are two separate builds on Xcode Server reports as failed. Most Xcode Server builds tend to alternate between these two sets of failures.

More investigation is required.

**Comment by ashfurrow** [comment]
I'm seeing something similar – initially thought it was related to #180, but this sounds like it could be it. I'm on a fast machine, Xcode 7, but sometimes specific tests take a number of seconds to pass. Adding a higher timeout would work, but I'd have to do that for every test :sweat_smile: 

This is the code that fails:

```swift
waitUntil(timeout: 10) { (done) in
    dispatch_async(dispatch_get_main_queue()) {
        done()
    }
}
```

Let me know if I can help or provide any more details.

**Comment by jeffh** [comment]
Hey @ashfurrow,

Sorry for the long turn around. Do you still get this issue? Do you still get this issue if you remove the guard clause in `pollBlock` of Nimble?

```swift
// Try this implementation
internal func pollBlock(pollInterval pollInterval: NSTimeInterval, timeoutInterval: NSTimeInterval, expression: () throws -> Bool) -> PollResult {
    let runLoop = NSRunLoop.mainRunLoop()
    let startDate = NSDate()
    runLoop.runUntilDate(startDate)
    var pass = false
    do {
        repeat {
            pass = try expression()
            if pass {
                break
            }
            let runDate = NSDate().dateByAddingTimeInterval(pollInterval)
            runLoop.runUntilDate(runDate)
        } while(NSDate().timeIntervalSinceDate(startDate) < timeoutInterval)
    } catch let error {
        return .ErrorThrown(error)
    }

    return pass ? .Success : .Failure
}
```

**Comment by ashfurrow** [comment]
Hey, no problem! Still having the issue – I'll try to update it and let you know.

**Comment by ashfurrow** [comment]
Hard to reproduce reliably – mostly this occurs on CI. I've updated to 2.0.0 and hopefully we see it happen less :(

**Comment by ashfurrow** [comment]
Still seeing this on the latest release.

**Comment by jeffh** [comment]
Random question: do you tests that use WebKit?

**Comment by ashfurrow** [comment]
Negativo.

**Comment by jeffh** [comment]
This will require more investigation into what is being stuck on the run loop when this error occurs.




—

**Comment by ashfurrow** [comment]
I'll see what detail I can get you – probably later this week or next week.

**Comment by ashfurrow** [comment]
The builds ([example](https://travis-ci.org/artsy/eidolon/builds/85557412)) are failing consistently on a single test, but only on Travis. Investigating now.

**Comment by ashfurrow** [comment]
Alright, documenting this all, mostly for my own benefit.

The test itself looks like the following:

```swift
kioskWaitUntil { done -> Void in
    subject.updatedContentsSignal.take(1).subscribeCompleted {
        done()
    }
}
```

The `updatedContentsSignal` is a `RACSignal` instance (still haven't upgraded away from the ObjC interface :grimacing:). The property is computed with the following definition:

```swift
var updatedContentsSignal: RACSignal! {
    return RACObserve(self, "sortedSaleArtworks").distinctUntilChanged().mapArrayLengthExistenceToBool().ignore(false).map { _ -> AnyObject! in NSDate() }
}
```

It's a `RACObserve` of a (private) dynamic property called `sortedSaleArtworks`. We use a RAC operator `distinctUntilChanged` to ignore subsequence identical property values, and map the array into a bool which is true iff the array is not `nil` and contains at least one value. We ignore `false`, then map into `NSDate()` so that the caller subscribing to the signal gets the date/time that the content was updated. 

So I think the issue is that `sortedSaleArtworks` isn't getting set to a non-empty array, so let's look at how that is set. `sortedSaleArtworks` is bound to a signal that maps `saleArtworks` to be sorted. So how does _that_ property get set? It is bound to `recurringListingsRequestSignal()`. 

This is a recurring signal that starts immediately and maps to a sequence of network requests, which are stubbed. The logic here is complex, and if something is putting too much on the main thread, it's likely here. 

I'll keep investigating.

**Comment by ashfurrow** [comment]
In the course of https://github.com/artsy/eidolon/pull/539 I found that our test subject was outliving its intended lifetime and continuing to enqueue things onto the main thread. I've removed it but things are still failing; I suspect there may be something else in our code that's the problem. Continuing to investigate.

**Comment by jeffh** [comment]
Not being familiar with your codebase, but how many timers do you have when you print out the run loop around the failure?

```swift
print(NSRunLoop.mainRunLoop().getCFRunLoop())
```

It should give you a rough guess how much is enqueued. Note that timers will include long-deferred timers too (eg - 5 years in the future).

If you want to look deeper, you'll probably have to do some trickery on the `CFRunLoop`. A place for inspiration is my defuncted [Robot](https://github.com/jeffh/Robot/blob/819cb72bb6c1f4ddc7eb8c723bed3af63929cbeb/Robot/Public/RBTimeLapse.m) project which set all timer fire dates to now. (aka - use `CFRunLoopTimerGetNextFireDate`)

**Comment by ashfurrow** [comment]
Thanks for the kind advice – appreciated! :cake:

**Comment by ashfurrow** [comment]
Oh my – the `print` yielded 157 lines of description :see_no_evil: Looks like I know where to start. Thanks again Jeff!

**Comment by jeffh** [comment]
Hey @ashfurrow, I don't know if you still have a case to reproduce, but could you try PR #224? It's a rewritten async code that hopefully addresses flaky issues.

**Comment by ashfurrow** [comment]
OK, will do. I should have commented here earlier that I've not seen the problem in some time – your suggestions helped me identify some runaway timers.

**Comment by jeffh** [comment]
Fix is on master. Closing. Thanks for the help @ashfurrow.
