### ISSUE TITLE
How to fetch value from text fields, labels and static labels

### ISSUE THREAD

**Issue by bhawna08** [Quick/Nimble#178]
How to fetch value from text field, labels and static labels
(i.e.) I have a email text field and i entered my email address in the text field, now i have to fetch the displayed value from the text field and match with my expected result, which function i can use to perform ? please reply

**Comment by jeffh** [comment]
Hey @bhawna08,

It's a pretty broad question that depends on how you're building your application:

- Is it iOS / OS X?
- Are you using Storyboards, Nibs/Xibs, or just in code?

I think the [Quick Documentation](https://github.com/Quick/Quick/blob/swift-2.0/Documentation/TestingApps.md) can be useful to learn how to test in views.

**Comment by bhawna08** [comment]
Thanks jeffh, i got succeed in fetching the value from static text, by setting accessibility value of labels and alerts:)
