### ISSUE TITLE
Tests not executing in Xcode 7 beta 6

### ISSUE THREAD

**Issue by zbeckman** [Quick/Nimble#179]
We are seeing a very reproducible problem (not 100%, I would estimate around 50-70%) where Xcode 7 beta 6 fails to detect and execute tests. Instead, it seems that the test spec is detected, but none of the tests defined within the spec (e.g., with `context` and `it`, etc.) are actually run.

The result is that the test "runs," and is "successful," but it never actually executes any tests... so we are getting a false positive. Here's a screenshot that demonstrates the problem:

<img width="1920" alt="testdevicevalidation_swift" src="https://cloud.githubusercontent.com/assets/5351337/9588373/b9d700ec-4fdc-11e5-8cc4-48c9be3aa901.png">

It seems to *temporarily* reset if we clean the build directory and clean derived data... but, the problem usually returns as soon as we execute the tests more than once, or if we change the test (and require a recompile). Based on these observations, I'll say the problem crops up every time we compile a test... and only stays away if we get it working, and don't touch the compiled tests. Just guessing at this point, but that seems to be the behavior.

**Comment by zbeckman** [comment]
Darn it. Sorry, this belongs in Quick. Will recreate over there – please close this issue.

**Comment by jeffh** [comment]
No worries, closed. I've replied on that thread too. :+1:
