### ISSUE TITLE
Can we verify the background color of controls or text in xcode 7?

### ISSUE THREAD

**Issue by bhawna08** [Quick/Nimble#181]
Can we verify the color of controls or text in xcode 7?

**Comment by jeffh** [comment]
I don't know the context but could you read from the properties?

```swift
expect(myController.myTextLabel.textColor).to(equal(UIColor.redColor()))
```

**Comment by jeffh** [comment]
Closing for idle activity, please reopen if you're still having problems or confusion. Thanks!
