### ISSUE TITLE
Whenever using @testable import in UI test cases files, getting issue failed to import bridging header

### ISSUE THREAD

**Issue by bhawna08** [Quick/Nimble#189]
Whenever using @testable import in UI test cases files, getting issue "failed to import bridging header"

**Comment by jeffh** [comment]
Hey @bhawna08,

I don't see this issue when I'm trying to reproduce on my own machine. I'll need some details of your setup:

- Does this error exist without Nimble?
- Are you installing via cocoapods, carthage, or manually?
- Version of Xcode?
- Version of Nimble?
- Is your project a hybrid Objective-C / Swift project?

If you can, if you have a sample project that can reproduce the behavior that's ideal.

- Jeff

**Comment by jeffh** [comment]
I'm closing this issue. @bhawna08, please reopen with more information if your problem isn't resolved.
