### ISSUE TITLE
Install using carthage yields "Unsupported architecture"

### ISSUE THREAD

**Issue by aexmachina** [Quick/Nimble#191]
In a fresh Xcode project, if I add `github "Quick/Nimble" "swift-2.0"` to my Cartfile then run `carthage update` I get `Unsupported architecture` errors.

**Comment by jeffh** [comment]
Hey @aexmachina,

Do you get this when using `master`? `swift-2.0` was merged into master a bit time ago. It's been deleted now. What Xcode versions and platforms are you using carthage for? You might need to specify a platform with carthage: (eg - `--platform tvOS`)

I don't actively use carthage so I'm not sure what's the best way to troubleshoot this.

**Comment by aexmachina** [comment]
Yes, still happening when I specify master. I'm running Xcode 7.0:

```
$ cat Cartfile | grep Nimble
github "Quick/Nimble" "master"
$ carthage version
0.8.0
$ carthage update --platform iOS | pbcopy
...
The following build commands failed:
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Matchers/BeCloseTo.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Wrappers/MatcherFunc.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Expectation.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Adapters/NimbleXCTestHandler.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Utils/Stringers.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Utils/SourceLocation.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Matchers/BeLessThanOrEqual.swift
	CompileSwift normal arm64 /Users/simonwade/dev/Workspace/nxgen-ios/Carthage/Checkouts/Nimble/Nimble/Adapters/AssertionDispatcher.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)
```

**Comment by jeffh** [comment]
Hey @aexmachina,

The errors seem to indicate that Darwin headers are missing. Does your project build without Nimble and when you use the `Darwin` module? I can't reproduce locally.

Also, could you try running [NATs](https://github.com/jeffh/NATs) to see if this fails for you too?

- Jeff

**Comment by hectormatos2011** [comment]
I'm not terribly sure what this issue could be but I've had these Darwin errors before in one of my projects. It may not be related to Nimble but are there any Swift Scripts ANYWHERE in your project @aexmachina?

**Comment by hectormatos2011** [comment]
^^^This is also in any pods, run script build phases, maybe Carthage uses them (dunno I've never used Carthage)

**Comment by aexmachina** [comment]
Thanks for responding. We've just switched to using CocoaPods for these dependencies, so this isn't a priority for me any more. Happy to help though.

Here's the output of running NATs:

```
$ rake
-> Testing iOS-Cocoapods
   OK
-> Testing iOS-Carthage
   OK
-> Testing OSX-Carthage
   OK
-> Testing OSX-Cocoapods
   OK
```

The project does build without Nimble (if we remove the code that uses it). Not sure what you mean by "when you use the `Darwin` module".

**Comment by aexmachina** [comment]
FWIW I eventually resolved this issue using [these instructions](https://github.com/Carthage/Carthage/issues/424#issuecomment-93434921) to scorched-earth nuke Xcode. Go figure.

**Comment by jeffh** [comment]
Do you have a sample project that demonstrate this failure. I'd like to know the issue with setting up via Carthage




—

**Comment by aexmachina** [comment]
No I think the issue was caused by some bizarre issue with the Xcode install on my machine. Now that I've nuked all my Xcodes, restarted and reinstalled it's all working again.
