### ISSUE TITLE
Custom matcher for UIColor does not build

### ISSUE THREAD

**Issue by jschmid** [Quick/Nimble#207]
I am trying to build a matcher that will check if a `UIColor` resembles to another one. I want a very simple code that takes every color component and checks if they are similar (like `beCloseTo`)

Here is a code sample that compiles and works:

```swift
override func spec() {
    fdescribe("Color serialization") {
        it("is handling strings") {
            let myColor = UIColor.colorFromRGBA("rgba(1, 200, 125, 0.820)") // Custom extension

            var r: CGFloat = 0
            var g: CGFloat = 0
            var b: CGFloat = 0
            var a: CGFloat = 0

            myColor.getRed(&r, green: &g, blue: &b, alpha: &a)

            expect(r).to(beCloseTo(  1.0 / 255))
            expect(g).to(beCloseTo(200.0 / 255))
            expect(b).to(beCloseTo(125.0 / 255))
            expect(a).to(beCloseTo(0.820))
        }
    }
}
```

But now if I try to make it as a matcher (because I want to make many checks), it fails:

```swift
class ColorExtensionsSpec: QuickSpec {
    override func spec() {
        fdescribe("Color serialization") {
            it("is handling strings") {
                let myColor = UIColor.colorFromRGBA("rgba(1, 200, 125, 0.820)")
                let colorCheck = UIColor(red: 1.0 / 255, green: 200.0 / 255, blue: 125.0 / 255, alpha: 0.820)
                expect(myColor).to(equalColor(colorCheck))
            }
        }
    }
}

public func equalColor<UIColor>(expectedValue: UIColor) -> NonNilMatcherFunc<UIColor> {
    return NonNilMatcherFunc { actualExpression, failureMessage in
        guard let actualColor = try actualExpression.evaluate() else {
            return false
        }

        var r: CGFloat = 0
        var g: CGFloat = 0
        var b: CGFloat = 0
        var a: CGFloat = 0

        actualColor.getRed(&r, green: &g, blue: &b, alpha: &a)

        return true
    }
}
```

The `getRed` method cannot be found for some reason:

<img width="831" alt="screen shot 2015-10-21 at 10 02 45" src="https://cloud.githubusercontent.com/assets/574168/10630978/f7210b0c-77da-11e5-93c0-726e29e03940.png">

I may not understand exactly how the matchers are built. I find it weird that some methods are not found.  Does someone see where the code fails to work?

**Comment by jeffh** [comment]
You're replacing `UIColor` type to a generic type in the scope of the function.

Change this line: 

```swift
public func equalColor<UIColor>(expectedValue: UIColor) -> NonNilMatcherFunc<UIColor> {
```

To this:

```swift
public func equalColor(expectedValue: UIColor) -> NonNilMatcherFunc<UIColor> {
```

Cheers,
Jeff

**Comment by jschmid** [comment]
Oh right...  Thanks @jeffh 

Would be be interested in a PR adding this matcher?

**Comment by jeffh** [comment]
Sure, although it should be called `beCloseTo` and work for OSX and iOS.

I'll close this issue since it's not a direct Nimble bug. Please open a new issue or create a PR for that change.

Thanks,
Jeff
