### ISSUE TITLE
Xcode 7.1 GM Build Error: iOS framework contains tvOS platforms

### ISSUE THREAD

**Issue by nanoxd** [Quick/Nimble#208]
I attempted to use the `xcode7.1` branch to build with Carthage and received: 
```
Nimble/Nimble/Adapters/AssertionRecorder.swift:48:20: Use of unresolved identifier 'NMBExceptionCapture'

Nimble/Nimble/Matchers/RaisesException.swift:20:27: Use of unresolved identifier 'NMBExceptionCapture'

/Nimble/<module-includes>:1:1: Umbrella header for module 'Nimble' does not include header 'Nimble/Nimble/objc/DSL.h'
/Nimble/<module-includes>:1:1: Umbrella header for module 'Nimble' does not include header '/Nimble/Nimble/objc/NMBExceptionCapture.h'
```

Adding the following the umbrella header fixed the issue: 
```
#import <Nimble/DSL.h>
#import <Nimble/NMBExceptionCapture.h>
```

I'm not sure if this is the only way to fix it, I can submit a PR if you'd like to go this route.

Thanks :confetti_ball:!

**Comment by nanoxd** [comment]
Upon further digging, the error stems from having bit code disabled for the tvOS slice. 

![nano tmux 2015-10-21 14-20-51](https://cloud.githubusercontent.com/assets/1889575/10650775/21270bac-7800-11e5-839d-5739f5f52425.png)
The interesting part is that I'm not building all platforms (using `carthage update --platform iOS`) but the `Supported Platforms` contains references to the Apple TV

![nimble xcodeproj 2015-10-21 14-29-37](https://cloud.githubusercontent.com/assets/1889575/10650791/3b9db5f8-7800-11e5-9adc-403ff595ef03.png)

**Comment by eimantas** [comment]
I've forked quick/Nimble and updated the settings and the code base to compile under Xcode 7.1. You can check it out at walkingsmarts/Nimble (same branch: xcode7.1)

**Comment by AnthonyMDev** [comment]
When is a new version going to be released with the `xcode7.1` branch merged?

**Comment by RohanNagar** [comment]
+1 to this issue. This is currently broken for me and I can't run my tests :(

**Comment by jeffh** [comment]
Hey guys,

Sorry for the slow turnaround, most of the current contributors to Quick are currently not active and I can only guarantee a few hours a week.

I would be more comfortable releasing if I didn't receive conflicting results of enabling and disabling bitcode for tvOS. I think I'll just bite the bullet and release with bitcode enabled and see if there's any fallout for that.

Thanks,
Jeff

**Comment by jeffh** [comment]
I've cut [v3.0.0](https://github.com/Quick/Nimble/releases/tag/v3.0.0).

Please let me know if you're having any issues.

**Comment by RohanNagar** [comment]
@jeffh Appreciate it, everything seems to be working after the upgrade.
