### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by LukeDefeo** [Quick/Nimble#211]
I get the following error

Failed to write to /Users/luked/Git/iOS/Trainline/iOSApp/Carthage/Build/Mac/Nimble.framework: Error Domain=NSCocoaErrorDomain Code=4 "The file “Nimble.framework” doesn’t exist." UserInfo=0x7fe0d4104960 {NSSourceFilePathErrorKey=/private/var/folders/wl/y9791wh568jcphhq_sx_zmrskgs4x4/T/carthage-archive.3J6XcF/Carthage/Build/iOS/Nimble.framework, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/luked/Git/iOS/Trainline/iOSApp/Carthage/Build/Mac/Nimble.framework, NSFilePath=/private/var/folders/wl/y9791wh568jcphhq_sx_zmrskgs4x4/T/carthage-archive.3J6XcF/Carthage/Build/iOS/Nimble.framework, NSUnderlyingError=0x7fe0d410fd70 "The operation couldn’t be completed. No such file or directory"}
ttl001527:iOSApp luked$

**Comment by yoichitgy** [comment]
You can get more information with `--verbose` option to `carthage` command to solve the problem or get help.

**Comment by LukeDefeo** [comment]
Yeah I managed to fix it with no-use-binaries flag. I guess that means there's something up with your pre cooked binary
