### ISSUE TITLE
Cannot compare swift enums

### ISSUE THREAD

**Issue by LukeDefeo** [Quick/Nimble#212]
I have the following enum:

```swift
enum JourneyResultsViewModelState {
	case Initialised
	case FetchingData
	case NetworkError(String)
	case SearchError(String)
	case JourneysLoaded
}
```

But i cannot use equals with this type

```swift
let state1 = JourneyResultsViewModelState.Initialised
let state2 = JourneyResultsViewModelState.JourneysLoaded
expect(state1.rawValue).to(equal(state2))
```

does not compile " Cannot invoke 'equal' with an argument list of type '(JourneyResultsViewModelState)'"

Am i missing something?

**Comment by jeffh** [comment]
Hey @LukeDefeo,

You'll need to get your enum to implement equality: either as an `Equatable`, `RawRepresentable`, or `OptionSetType`. `rawValue` is not native to enum types without inherited one of those types (or inheriting a type that implements one of those)

Alternatively, you can also override Nimble's `equal` operator to support your enum type.

**Comment by jeffh** [comment]
@LukeDefeo,

Did you solve your problem or is this still an issue?

**Comment by LukeDefeo** [comment]
Yeah all good thank you
