### ISSUE TITLE
Matcher operator overloads for nil(-like) literals

### ISSUE THREAD

**Issue by jmper1** [Quick/Nimble#214]
How about if we define a constant (global only to Nimble):

``` swift
let Nil: NilLiteralType = NilLiteral()
```

where `NilLiteralType` and `NilLiteral` are defined as:

``` swift
protocol NilLiteralType {}
struct NilLiteral: NilLiteralType {}
```

and override the equality operators:

``` swift
func ==<T>(lhs: Expectation<T>, nilLiteral: NilLiteralType)
{
  lhs.to(beNil())
}

func !=<T>(lhs: Expectation<T>, nilLiteral: NilLiteralType)
{
  lhs.toNot(beNil())
}
```

so that expressions like the following are possible:

``` swift
expect(foo) == Nil
expect(bar) != Nil
```

I can create a PR if you don't think this is a stupid idea.

**Comment by jeffh** [comment]
That sounds good to me. Just make sure it honors Nimble's accidental nil-ness behavior for all other equalities.

- Jeff
