### ISSUE TITLE
Nimble v3.0 binary is missing device architectures

### ISSUE THREAD

**Issue by roman-dzieciol** [Quick/Nimble#215]
The v3.0 binary does not include arm architectures for testing on device. Is this intentional?

**Comment by jeffh** [comment]
Nope, my cert expired and carthage didn't error when I auto-uploaded it. I'll push a new one later tonight. Thanks for reporting this @roman-dzieciol!

**Comment by jeffh** [comment]
Ok, I've uploaded it. Note that it currently does not include tvos (there are current pending issues with it).
