### ISSUE TITLE
Stall on main thread error

### ISSUE THREAD

**Issue by mfclarke** [Quick/Nimble#216]
Hi guys, I'm seeing this error with some fairly vanilla tests when run on a Bot on our Xcode Server. It only happens for tests which use the waitUntil function, testing some functions that use AlamoFire and checking the right data is returned in the callback. I'm stubbing the requests with Nocilla, but the issue still occurs if I don't stub and increase timeouts to accomodate for network latency.

Strangely, it only crops up when the tests are run by an Xcode Bot. If I run the tests manually in Xcode on the Xcode Server and of course on my MacbookPro they run fine. 

I have tried using NSRunLoop.mainRunLoop().runUntilDate(NSDate()) just before the waitUntil as mentioned in #122 but this doesn't entirely fix the problem. I have to also increase the timeouts of my waitUntils to 10+ seconds, but even then some tests fail with the stall error. The file of 20 tests normally executes in about 2 seconds or less normally.

OSX Server 10.11.1, Xcode Server 5.0.15, Xcode 7.1. Running on iPhone 6 iOS9.1 simulator.
Installed as a git submodule on at 2.0.0-rc.3. But we use cocoapods for other dependencies (0.38.2)

**Comment by mfclarke** [comment]
I have just checked with the Quick + Nimble submodules on master and I still have the same behaviour.

**Comment by jeffh** [comment]
Hey @mfclarke, how many timers do you have when you print `CFRunLoop` near point where you get the main thread stall?

```swift
print(NSRunLoop.mainRunLoop().getCFRunLoop())
```

**Comment by alessandroorru** [comment]
I am experiencing the same issue.
I have temporary worked around this with the following code (I'm relying on XCTest expectations)

```swift
extension XCTestCase {
    func waitExpectation(timeout timeout: Double = 1, caller: String = __FUNCTION__, action: (done: () -> Void ) -> Void) {
        
        let expectation = expectationWithDescription(caller)
        
        action { done in
            expectation.fulfill()
        }
        
        waitForExpectationsWithTimeout(timeout) { (error) -> Void in
            if let error = error {
                print("Error fulfilling expectation: \(error)")
            }
        }
    }
}
```

**Comment by vburojevic** [comment]
I'm having the same issue. Local tests run and pass just fine, but Travis tests fail because of a stall on a test that adds objects to core data synchronously.

**Comment by MattesGroeger** [comment]
+1 Also facing the same problem now, also locally.

**Comment by nerd0geek1** [comment]
:+1: 
I also facing the same issue on CircleCI, also locally.

**Comment by nordfogel** [comment]
+1 here
local tests pass but not executed via teamcity ci

**Comment by PatrykKaczmarek** [comment]
+1 Same for me.
 Local tests always pass. On CI (Bitrise) fail randomly.

**Comment by attheodo** [comment]
+1, local always pass, Bitrise mostly fail. `NSRunLoop` works for local env but doesn't do the job on CI.

**Comment by jeffh** [comment]
Hey all,

I merged a fix on `master`, if if you can confirm that would be great! I'll try to get a release out soon.

**Comment by mfclarke** [comment]
Many thanks @jeffh, I will check this today

**Comment by jeffh** [comment]
Closing. This is now in v3.1.0. Thanks everyone!

**Comment by attheodo** [comment]
Runs ok on local, getting lots of `failed - expected to eventually match (timed out, but main thread was unresponsive)` on Bitrise CI

cc @jeffh

**Comment by mfclarke** [comment]
+1, issue still persists with Xcode Server for me too

**Comment by jeffh** [comment]
Do you have a example test case?

**Comment by anas10** [comment]
I still have this issue quite often. It's quite random because when I relaunch it happens again but on other tests and not the previous one anymore.

**Comment by maqoo** [comment]
+1
Im experiencing the same issue :( 
.toEventually() fails at random on Bitrise CI

**Comment by mjgaylord** [comment]
+1
I am getting failures for `toEventually` and `waitUntil` when running my tests using `fastlane scan` or `xcodebuild` on my local machine and on CircleCI.
