### ISSUE TITLE
EXC_BAD_INSERUCTION(code=EXC_1386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by rasool310** [Quick/Nimble#219]
Hi,
I am using Xcode 7.0 and using libraries 
    pod 'Quick', '~> 0.8.0’
    pod 'Nimble', ‘3.0.0’

I am able to test with expect  "expect(1+10).to(equal(2))" and i am getting correct out put. 
But when i am using "describe" keyword then i am getting EXC_BAD_INSERUCTION(code=EXC_1386_INVOP, subcode=0x0) exception. i am writing below code
describe("comparision of two numbers") { () -> Void in
            expect(1+10).to(equal(2))
        }
This is the code which i am writing
![screen shot 2015-11-30 at 4 13 06 pm](https://cloud.githubusercontent.com/assets/5829004/11469835/4f06a28c-977f-11e5-8936-8af6cfcc7a2c.png)

and i am getting the exception code
![screen shot 2015-11-30 at 4 12 41 pm](https://cloud.githubusercontent.com/assets/5829004/11469845/63f85ac8-977f-11e5-9021-3c64f90ee454.png)

i am not using any flags..
Thanks in advance.

**Comment by morganchen12** [comment]
Looks like this is a [Quick](https://github.com/Quick/Quick/)-related issue. `describe` can only be used with the `QuickSpec` class, or the context required by `describe` will never be set up.

To clarify further, Nimble is a replacement for `XCTAssert`ions; Quick is a replacement for XCTest. Nimble can be used within an `XCTestCase`, but Quick cannot.

Maybe a more informative error would be helpful in this case, though.

**Comment by jeffh** [comment]
Closing issue. Thanks @morganchen12 for the PR.

@rasool310, if you're still not clear on what to do, please reopen this issue. Thanks!
