### ISSUE TITLE
Async expectation inside waitUntil always fails

### ISSUE THREAD

**Issue by tmandry** [Quick/Nimble#223]
The following code always fails on my (fast) machine:

```swift
class Spec: QuickSpec {
  override func spec() {
    fit("dispatch_async inside waitUntil") {
      waitUntil(timeout: 2.0) { done in
        var protected: Int = 0
        dispatch_async(dispatch_get_main_queue()) {
          protected = 1
        }

        expect(protected).toEventually(equal(1))
        done()
      }
    }
  }
}
```

This might fall into the category of "why would you do that?", but I ran into (a more complex version of) this situation while doing some tests involving promise chains. While there is a workaround, it took quite a bit of time to debug and wasn't expected behavior.

The workaround is to move the _either_ the `dispatch_async` _or_ the async promise (or both) outside the `waitUntil`.

**Comment by jeffh** [comment]
Thanks @tmandry, I can confirm the issue. This definitely requires more investigation.

**Comment by jeffh** [comment]
Hey @tmandry,

This issue has to do with both implementations assuming control of the run loop to process async dispatches to the main thread. For now, I've provided a more explicit error message.

These changes are currently only on `master`.

Thanks for filing the bug! I'll close this issue once this change is in a release.

**Comment by tmandry** [comment]
An error message helps, thanks!

**Comment by jeffh** [comment]
Closed. This is now in v3.1.0.
