### ISSUE TITLE
Add ability to compare tuples

### ISSUE THREAD

**Issue by abbeycode** [Quick/Nimble#227]
I have test code like this:

``` swift
let listOfTuples = //...
expect(listOfTuples).to(equal([
    (name: "Name", description: "Description")
]))
```

I get a compiler error:

> Cannot invoke 'equal' with an argument list of type '([(name: String, description: String)])'

I tried removing the labels in the tuple, and I get the same error (but without the labels in the type the error prints). Is there a way to accomplish this type of matching with Nimble?

**Comment by wizzardchao** [comment]
It seems it's a swift compiler's bug to support array of tuple. I can also not append an element to an array of tuple.

**Comment by jeffh** [comment]
Unfortunately, swift currently doesn't have a clean way of representing arbitrary tuples for Nimble to perform equality against. There only way is to implement it for each tuple of a given size (unlabeled).

For now, you'll have to compare each element in the tuple manually.

**Comment by abbeycode** [comment]
It looks like this is coming in Swift 2.2: https://github.com/apple/swift-evolution/blob/master/proposals/0015-tuple-comparison-operators.md

**Comment by briancroom** [comment]
That feature from that proposal is now available in the latest Xcode, however it doesn't do much to help with @abbeycode's original feature request.

Specifically, the standard library now provides additional overloads of `==` and the comparison operators that accept tuples as their `lhs` and `rhs` arguments, however the tuples themselves aren't made `Equatable` or `Comparable`. This means that the new functionality is not automatically made available to Nimble's matchers, and it also means that comparing arrays of tuples hasn't gotten any less painful.

```swift
let tuple = (1, 2)
tuple == tuple // This works now!
expect(tuple).to(equal(tuple)) // Error: Cannot invoke 'equal' with an argument list of type '(Int, Int)'

let tuples = [(1, 2)]
tuples == tuples // Error: Binary operator '==' cannot be applied to two '[(Int, Int)]' operands
```

**Comment by jonnolen** [comment]
in this case:  `expect(tuple == tuple2).to(beTrue())` is what I ended up falling back to.  still won't handle arrays but solves the expected type issue.

**Comment by ikesyo** [comment]
ref: https://github.com/apple/swift-evolution/pull/1109

**Comment by wearhere** [comment]
Looks like the proposal was accepted and is now being implemented 🎉 https://github.com/apple/swift/pull/28833

**Comment by revolter** [comment]
It was merged but then it was reverted :(

**Comment by ikesyo** [comment]
Implemented `equal` overloads for tuples of up to 6 elements in #880.

For arrays of tuples, you can use `elementsEqual` instead:

```swift
expect([(1, "2"), (3, "4")]).to(elementsEqual([(1, "2"), (3, "4")], by: ==))
```
