### ISSUE TITLE
Shorten beIdenticalTo to be

### ISSUE THREAD

**Issue by jcampbell05** [Quick/Nimble#230]
I'm used to RSpec and think it would be more concise for `beIdenticalTo` to be `be`

**Comment by jeffh** [comment]
Sounds good to me.

I don't particular mind either - `beIdenticalTo` maps to my head more readily than `be`.

**Comment by jwfriese** [comment]
@jeffh - I agree with your sentiment -- ```beIdenticalTo``` for some reason is quicker to mind for me too. But then, I'm not super experienced in RSpec.

What would you think about aliasing this and having both around? I can see where it might be needless bloat, but the thought crossed my mind when I first looked at this issue.

**Comment by jcampbell05** [comment]
An alias would be great :) :+1:

**Comment by jeffh** [comment]
An alias works for me.

**Comment by jwfriese** [comment]
@jeffh @jcampbell05 
Is this completed with #241?

**Comment by jeffh** [comment]
Yes, my bad. Closing now :smile:
