### ISSUE TITLE
Is there a decent way to compare NSRanges in Objective-C

### ISSUE THREAD

**Issue by fatuhoku** [Quick/Nimble#254]
Currently you have to write something super clumsy like:

`expect([NSValue valueWithRange:feature.range]).to(equal([NSValue valueWithRange:NSMakeRange(3, 5)]));`

Is there a better way?

**Comment by briancroom** [comment]
Hey @fatuhoku, Nimble's Objective-C matchers only work with objects, so there's no way for them to work directly with NSRange structs. It is, however, possible to use the preprocessor to make this case less cumbersome. For example:

```
#define valueOf(VAL) ({ __typeof__((VAL)) val = (VAL); [NSValue valueWithBytes:&val objCType:@encode(__typeof__((VAL)))]; })

NSRange range = NSMakeRange(3, 5);
expect(valueOf(range)).to(equal(valueOf(NSMakeRange(3, 5))));
```

**Comment by jeffh** [comment]
Agreed with @briancroom. That being said, it would be nice to have support for this.

Related issue: https://github.com/Quick/Nimble/issues/113. Using overloadable would be a nice way to improve Nimble's Objective-C's interface.
