### ISSUE TITLE
Make `stringify` public?

### ISSUE THREAD

**Issue by briancroom** [Quick/Nimble#258]
When writing custom matchers (which people should do more often!) I frequently find myself wanting to output values the same way that the built-in matchers do, which would require using Nimble's `stringify` function(s), but that only has `internal` visibility. Would it make sense to expose these as `public` for the benefit of custom matcher implementations?

**Comment by jeffh** [comment]
Agreed. I originally wanted to make this public, but I don't like the current state that `stringify` exists as. It needs some more refactoring before made available.

That most of that code existed before the ability to dynamically type check swift-only types: (eg - generic `T` or even `AnyObject`).

I was thinking perhaps a more protocol-extension based approach, but we would need to dynamically check if the type supported the protocol and not require all types implement it.

But I'm open to other kinds of refactors to improve that the state it currently is in.

**Comment by briancroom** [comment]
Resolved by #264. Thanks @morganchen12!
