### ISSUE TITLE
Subject action?

### ISSUE THREAD

**Issue by jmejiaa** [Quick/Nimble#266]
Cedar has a very useful "subject action" which runs after every before each within a block.. Could this be an enhancement to Quick?

Description from Cedar's documentation:
Generally you want each top-level describe block to describe a single method or action. Often you end up calling this action in multiple places at multiple levels of nesting after various amounts of setup. In this case you can use a subject action block to simply your specs. A subject action block differs from a before each block because you may have only one for any given example group (if multiple levels define a subject action block Cedar will throw an exception), and it will run after all before each blocks for a given example.

**Comment by jeffh** [comment]
Hey John,

I’ve been thinking about this feature, but I’m not sure where I stand on this. It’s a more polarizing feature. Do you prefer Cedar’s incantation or Gomega’s `JustBeforeEach`?

Of course, this is much more of a Quick feature than a Nimble one. Please file the issue on Quick and we can continue the discussion there.

Thanks,
- Jeff

**Comment by jeffh** [comment]
Actually, searching on this on Quick resulted in this: https://github.com/Quick/Quick/issues/209.

Feel free to expand the discussion there if you prefer. Closing this issue. Thanks for filing an issue: @jmejiaa! :smile:

**Comment by jmejiaa** [comment]
Thanks @jeffh sorry for the late reply. I meant to add it to Quick. The thread suggests using a function in the beforeEach , which I guess would work just as well
