### ISSUE TITLE
Comparing a CAShapeLayer.fillColor to a UIColor.CGColor?

### ISSUE THREAD

**Issue by jeffscaturro-wf** [Quick/Nimble#290]
I am attempting to test equivalence of a `fillColor` on a variable of type `CAShapeLayer` to a `CGColor` on type of `UIColor` like so: 
```
let backgroundLayer = view.backgroundLayer // Type of CAShapeLayer non-optional
expect(backgroundLayer.fillColor) == UIColor.clearColor().CGColor
```
but am receiving an unusual error of: 
```
error: binary operator '==' cannot be applied to operands of type 'Expectation<CGColor>' and 'CGColor'
                                  expect(backgroundLayer.fillColor) == UIColor.clearColor().CGColor
```

The same thing happens with comparing a `CGPath` to a `UIBezierPath.CGPath`:
```
error: binary operator '==' cannot be applied to operands of type 'Expectation<CGPath>' and 'CGPath'
                    expect(backgroundLayer.path) == UIBezierPath(arcCenter: CGPointMake(0, 0), radius: 0, startAngle: 0, endAngle: 0, clockwise: true).CGPath
```

Currently, we are managing to test equivalence by doing:
```
let convertedColor: UIColor = UIColor(CGColor: backgroundLayer.fillColor!)
expect(convertedColor) == UIColor.clearColor()
``` 

Any ideas?

**Comment by morganchen12** [comment]
My initial thought is that `CGColor` doesn't conform to `Equatable`. You
could then fix this by extending `CGColor` to conform to `Equatable`.

```
extension CGColor: Equatable {}
public func ==(l: CGColor, r: CGColor) -> Bool {
return CGColorEqualToColor(l, r)
}
```

If this doesn't work I can take a closer look later in a few hours.

**Comment by morganchen12** [comment]
The overloaded `==` operator expects the types it's comparing to conform to `Equatable`. While `CGContext` and `CGPath` provide equivalence functions, they're plain C types bridged to Swift and therefore don't adopt the `Equatable` protocol by default. Extending these types to conform to `Equatable` should fix your problem.

```
extension CGColor: Equatable {}
public func ==(lhs: CGColor, rhs: CGColor) -> Bool {
    return CGColorEqualToColor(lhs, rhs)
}

extension CGPath: Equatable {}
public func ==(lhs: CGPath, rhs: CGPath) -> Bool {
    return CGPathEqualToPath(lhs, rhs)
}
```

Then you should be able to do

```
let color = UIColor.whiteColor().CGColor
expect(color) == UIColor.whiteColor().CGColor

expect(backgroundLayer.path) == UIBezierPath(arcCenter: CGPointMake(0, 0), 
    radius: 0, startAngle: 0, endAngle: 0, clockwise: true).CGPath
```

**Comment by jeffscaturro-wf** [comment]
I thought it may be something like that but we could not narrow it down. @morganchen12 - thank you for your explanation as well as solution, just verified it works. Appreciate it!
