### ISSUE TITLE
throwError() doesn't work ?

### ISSUE THREAD

**Issue by denis631** [Quick/Nimble#294]
I'm using Quick/Nimble for testing my game app.

Example that works:
```
it("shouldn't work out, if intersection is owned by another player") {
    do {
        try game.playerWantsToPutStoneAtIndexPath(indexPath)
        try game.playerWantsToPutStoneAtIndexPath(indexPath)
    } catch {
        expect(error as? GameRulesError) == GameRulesError.intersectionIsAlreadyOwnedBy(playerA)
    }
}
```

But I don't use the new expect(...).to(throwError())

I wanted to use it to make the code more elegant, but it doesn't work:

<img width="1419" alt="screen shot 2016-05-13 at 10 02 44" src="https://cloud.githubusercontent.com/assets/6100421/15241735/43647522-18f2-11e6-9bb3-d2f4c8f48eb8.png">

It tells me, that the the it closure throws an error, that I don't catch ...

Well, if I force the try, I get an runtime exception:
<img width="1400" alt="screen shot 2016-05-13 at 10 03 11" src="https://cloud.githubusercontent.com/assets/6100421/15241776/8a21e4f4-18f2-11e6-98ed-2b50f37d3016.png">

How can I use the new throwError construct ?

**Comment by ikesyo** [comment]
As written in [README](https://github.com/Quick/Nimble/blob/42e9bfd0ee784de3363f8e1c6709bc5bf9906da2/README.md#swift-error-handling), I think you need to do as follows: 

```swift
expect{ try game.playerWantsToPutStoneAtIndexPath(indexPath) }.to(throwError())
```

**Comment by denis631** [comment]
I haven't seen the curly braces... Sorry.
