### ISSUE TITLE
Quick and nimble not getting installed in my project

### ISSUE THREAD

**Issue by priyapy** [Quick/Nimble#301]
Hi ,

I am using Quick/Nimble in my framework project for writing testcases. I tried to install Quick into my project test case target through pods. Its getting installed as well. But I am not getting access to it quick and nimble from my testclasses.

Xcode version : 7.3.1
Swift 2.0
pods  : 
```

> platform :ios, '8.0'
> target 'TestFramework' do
>   use_frameworks!
>   pod 'ObjectMapper', '~> 1.3'
>   pod 'Alamofire', '~> 3.4'
>   pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
>   pod 'CryptoSwift'
>   pod 'IDZSwiftCommonCrypto'
>   pod 'Fabric'
>   pod 'Crashlytics'
>   pod 'SwiftMoment'
>   target TestFrameworkTests' do
>     inherit! :search_paths
>     pod 'Quick'
>     pod 'Nimble'
>   end
> end

```

**Comment by ashfurrow** [comment]
Hmm, interesting. You say the problem is you can't access Quick or Nimble? Could you post an example test file that's presenting the problem? Is there a compiler or other error you can provide?

**Comment by priyapy** [comment]
Thank you for the response. In test file Quick or nimble is not compiling. its not giving me provision to use any of the builtin methods in it. Rather i am not getting the quick or nimble in autofilling while trying to import

**Comment by modocache** [comment]
@priyapy Is the problem that autocomplete doesn't work? Or is it a build error?

I think a specific compiler error would help here, or even a screenshot of the error you're seeing. Something like this:

```
QuickFocused-iOSTests Group
/Users/bgesiak/GitHub/modocache/Quick/Sources/QuickFocusedTests/FocusedTests.swift
/Users/bgesiak/GitHub/modocache/Quick/Sources/QuickFocusedTests/FocusedTests.swift:1:8: No such module 'Quick'
```

Or this:

![screen shot 2016-06-03 at 2 48 39 pm](https://cloud.githubusercontent.com/assets/552921/15789464/56bc5a64-299a-11e6-95e0-ba92488bc380.png)

Thanks!

**Comment by priyapy** [comment]
@modocache  yes, this is the error i am facing.

**Comment by modocache** [comment]
@priyapy You mean "No such module 'Quick'"?

**Comment by jeffh** [comment]
Hey @priyapy, could you elaborate on the specific error you're having or a sample project that is showing the error?
