### ISSUE TITLE
Nimble 4.1.0

### ISSUE THREAD

**Issue by sharplet** [Quick/Nimble#307]
I'd like to release 4.1.0. I've written some release notes: https://gist.github.com/sharplet/052919c21425b922cc8a066a8979939e.

Could a verified contributor create the release for me? I don't have the time to set up PGP right now. Thanks!

**Comment by ashfurrow** [comment]
Looks good, I'll take care of it 👍

**Comment by ashfurrow** [comment]
Done: https://github.com/Quick/Nimble/releases/tag/v4.1.0 Also: https://twitter.com/ashcommits/status/744301119728394244

**Comment by sharplet** [comment]
Awesome, thanks!!
