### ISSUE TITLE
Examples using `evaluate` in README need update

### ISSUE THREAD

**Issue by dlo** [Quick/Nimble#311]
The following example, from [this page](https://github.com/Quick/Nimble#writing-your-own-matchers) on the README fails with a compile-time error, since `actionExpression.evaluate` can throw but is not caught.

Full error: "Call can throw, but it is not marked with 'try' and the error is not handled"

```swift
public func equals<T: Equatable>(expectedValue: T?) -> MatcherFunc<T?> {
    return MatcherFunc { actionExpression, failureMessage in
        failureMessage.postfixMessage = "equal <\(expectedValue)>"
        return actionExpression.evaluate() == expectedValue
    }
}
```

**Comment by jeffh** [comment]
Thanks @wongzigii and @dlo! The README has been updated. 👍
