### ISSUE TITLE
Nimble causing error in travis CI builds

### ISSUE THREAD

**Issue by RonanMcH** [Quick/Nimble#312]
Keep getting this issue failing our "Tests" build on Travis CI:
```
❌  /Users/travis/Library/Developer/Xcode/DerivedData/ZendeskSDK-hkgxqiyiffwqpzbshugkdluampes/Build/Intermediates/Pods.build/Debug-iphonesimulator/Nimble.build/unextended-module.modulemap:7:18: header 'CurrentTestCaseTracker.h' not found

  private header "CurrentTestCaseTracker.h"

                 ^

2016-06-28 14:46:07.966 xcodebuild[3755:9082] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fb4f48bb1b0>

Testing failed:

	Header 'CurrentTestCaseTracker.h' not found

	Could not build Objective-C module 'Nimble'

** TEST FAILED **
```
Can you help us please?

**Comment by briancroom** [comment]
Can you provide some additional details about your environment? Is this with a Nimble release, or `master`? It looks like you're using Cocoapods - which version are you running?

**Comment by RonanMcH** [comment]
We are using cocoapods to integrate. We are on version 4.1.0. Pre this version we never experienced this error.

**Comment by RafaelPlantard** [comment]
I'm facing this same issue...

**Comment by jeffh** [comment]
Hey @RonanMcH, what version of Xcode, Cocoapods, & Nimble are you using?

**Comment by RonanMcH** [comment]
Hi @jeffh ,
We resolved this issue a long time ago on our own and long since upgraded on Xcode, Cocoapods and Nimble. I cannot recall what versions we were on. Feel free to close this issue but I don't wanna speak for @RafaelPlantard .
Thanks,
Ronan.

**Comment by jeffh** [comment]
Closing, thanks for following up @RonanMcH! 🎉

**Comment by RafaelPlantard** [comment]
You are right I'm not facing this problem more.
