### ISSUE TITLE
Do we have a way to strongly assert on method call with parameters like in cedar

### ISSUE THREAD

**Issue by repl-ullas-ml** [Quick/Nimble#313]
I'm taking first steps in adopting Nimbe/Quick and struggled to find in documentation if we have a way to strongly assert and find if a method is called with right parameters.

Cedar gives assertion 
someclass **should have_received**(@selector(somemethod)).**with**(someparameters); 

Do we already have something in Nimble ? If not is there any other way we could test such a use case?

**Comment by modocache** [comment]
Hello, @repl-ullas-ml! Great question. I agree that it's sometimes very useful to assert things like this. In Objective-C, I'd typically use [OCMock](http://ocmock.org/) to make such an assertion:

```objc
OCMVerify([mockObject someMethod:someParameters]);
```

It's not possible to do this for Swift objects that don't inherit from `NSObject`. For testing approaches in Swift, I'd instead recommend watching this video, by Jeff Hui: https://realm.io/news/testing-in-swift/.

Using the techniques from that video and OCMock, I think, provide all the functionality you'll need. As for your question of whether *Nimble itself* provides this functionality, the answer is "no". You could probably write a custom matcher for OCMock, such as the following:

```swift
expect(mockObject).to(receiveMessage(#selector(someMethod), withParameters:someParameters))
```

But I think that's actually less readable than using OCMock directly. OCMock is also a third-party dependency that not everyone uses, so we wouldn't include such a matcher in Nimble itself -- it belongs in a separate repository (which you're free to make, and I'd be happy to provide feedback on!).

Hope that answers your question! :)

**Comment by modocache** [comment]
It's also worth noting that [Kiwi](https://github.com/kiwi-bdd/Kiwi/) made the following possible:

```objc
[[myObject should] receive:@selector(someMethod)];
```

This is because Kiwi was both a testing framework (like Quick or Specta) and a mocking framework (like OCMock). Quick and Nimble do not couple these two things -- instead, they encourage users to use both Quick/Nimble *and* OCMock, as separate dependencies.

**Comment by repl-ullas-ml** [comment]
@modocache Oh i see. Thanks for your insights. Will probably stick with OCMock for now.
