### ISSUE TITLE
pod install not working for Nimble 4.1.0

### ISSUE THREAD

**Issue by RafaelPlantard** [Quick/Nimble#315]
[!] Unable to read the license file `/Users/rafael/Documents/GitHub/ShopBackBR/iShopSDK/Example/Pods/Nimble/LICENSE.md` for the spec `Nimble (4.1.0)`

[!] Unable to read the license file `/Users/rafael/Documents/GitHub/ShopBackBR/iShopSDK/Example/Pods/Nimble/LICENSE.md` for the spec `Nimble (4.1.0)`

**Comment by wongzigii** [comment]
Try clearing CocoaPods cache to see if it works: https://gist.github.com/mbinna/4202236
