### ISSUE TITLE
`toNotEventually` is misleading

### ISSUE THREAD

**Issue by Reflejo** [Quick/Nimble#322]
I might be missing something here but the docstrings of this method says: 

> Tests the actual value using a matcher to not match by checking
> continuously at each pollInterval until the timeout is reached.

Which means that by doing

``` swift
var something: Int = 0
// (.. do stuff async ..)
expect(counter).toNotEventually(beGreaterThan(1), timeout: 60)
```

I'd expect this test to take 1 minute (or up to the point `something > 1`) but that doesn't seem to be what's happening; what happens is: the test passes in 0.001 seconds.

Is this expected? If so is there a way to make sure something _doesn't_ "ever" happens?.

To clarify: I would expect `toNotEventually` to make sure that the condition is not met for the entire timeout interval.

**Comment by modocache** [comment]
I agree it's confusing. Perhaps this would be clearer as `toEventuallyNot()`? If you were to tell me "I expect this counter to eventually not be greater than one", I would interpret that as "I expect this counter to eventually be less than or equal to one". And if it was immediately less than or equal to one, I would tell you your condition has been met!

Also, thanks for the follow-up matcher in #323. I'll look at that now.

**Comment by jeffh** [comment]
Closing for idleness - feel free to reopen if you're still interested in this issue. While I agree there's ambiguity, the full waiting behavior can also be considered misleading.
