### ISSUE TITLE
matchError(errorType: T) is always matching

### ISSUE THREAD

**Issue by ndelitski** [Quick/Nimble#324]
see example below:
```swift
enum FooError: ErrorType {
    case ValuableReason
}

enum BarError: ErrorType {
}

expect(FooError.ValuableReason).to(matchError(BarError.self))
```

nimble v4.1.0

**Comment by wongzigii** [comment]
@ndelitski Using `BarError.self` in matchError is comparing `errorType`, actually. 
See https://github.com/Quick/Nimble/blob/master/Sources/Nimble/Matchers/MatchError.swift#L19

**Comment by jeffh** [comment]
I don't think it's desirable behavior. We should probably fix this.
