### ISSUE TITLE
Xcode 8 Beta 6 unable to build

### ISSUE THREAD

**Issue by zachlucas** [Quick/Nimble#325]
Using Nimble 4.1.0 installed via CocoaPods, I'm unable to build in Xcode 8 Beta 6.  At first I see:  “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift, then when I specify either `YES` or `NO`, `CurrentTestCaseTracker.h` can't find `Nimble/Nimble-Swift.h`.

**Comment by modocache** [comment]
Thanks for the report! Do you happen to know if it worked in your project using Xcode 8 beta 5 or earlier? I'm wondering whether this is an Xcode 8 beta 6 issue.

Has anyone in @Quick/core tried to use Nimble in Xcode 8 beta 6?

**Comment by ikesyo** [comment]
See #277.

**Comment by zachlucas** [comment]
@ikesyo I should've specified that I'm using Swift 2.3, not 3.  I've tried pointing to your PR in #321 via CocoaPods, same build issue there.

**Comment by ikesyo** [comment]
You should use CocoaPods 1.1.0.beta.1 to use Xcode 8.

**Comment by zachlucas** [comment]
@ikesyo that was it, thank you.
