### ISSUE TITLE
Carthage issue with Nimble

### ISSUE THREAD

**Issue by GregoryMaks** [Quick/Nimble#329]
Hi, when trying to build Nimble for [Kiwi](https://github.com/kiwi-bdd/Kiwi) project I faced the next issue.

## Output from Carthage:

*** Building scheme "Nimble-OSX" in Nimble.xcodeproj
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Volumes/Data/Development/Test/KiwiIssueTest/Subrepos/Kiwi/Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-tvOS -configuration Release -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

## Output from xcodebuild:

=== CLEAN TARGET Nimble-tvOS OF PROJECT Nimble WITH CONFIGURATION Release ===

Check dependencies
target 'Nimble-tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET Nimble-tvOS OF PROJECT Nimble WITH CONFIGURATION Release ===

Check dependencies
target 'Nimble-tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform

** BUILD FAILED **

## Suggestion

Maybe enabling bitcode is a fix for the issue, but it requires more deep analysis

**Comment by wongzigii** [comment]
Hi @GregoryMaks.
Good catch! I just try `carthage update` and got the same issue. It seems that Kiwi has disable bitcode for all targets. See https://github.com/kiwi-bdd/Kiwi/pull/661.

**Comment by jeffh** [comment]
@GregoryMaks: What version of carthage & xcode are you using?

This is an ongoing issue, maybe the latest releases of Xcode has resolved this, but it requires more investigation to figure out if setting `ENABLE_BITCODE=YES` fixes it.

Historical Context:

- Carthage required a fat binary (simulator + device) for tvOS (until [v0.17](https://github.com/Carthage/Carthage/releases/tag/0.17))
- tvOS requires bitcode enabled except XCTest in simulator (see https://github.com/Quick/Nimble/issues/170 & https://github.com/Quick/Nimble/issues/213)
- the toolchain (historically) incorrectly assumes XCTest requires bitcode if linked via another framework (see https://github.com/Quick/Nimble/issues/165)
- Cocoapods (historically) didn't work with bitcode enabled for tvOS (see https://github.com/Quick/Nimble/issues/196).

Nimble has historically swapped between both enabling and disabling bitcode to no avail in an attempt to cover all cases.

The easiest, immediate fix is to do one of the following:

- upgrade to carthage 0.17+ as it should have resolved this issue. Although, I haven't personally verified that.
- use git submodules (carthage: `--use-submodules`) and add `Nimble.xcodeproj` manually
- use `--platform` flag to exclude tvOS

**Comment by kkrawczynski** [comment]
@GregoryMaks i had the same problem after i upgraded xcode to 8 here's what i did:

- carthage update --platform [your_pick]

- went into Carthage\Checkouts for Nimble & Quick

- manually opened xcodeproj, declined conversion, set Legacy Swift Language Version to Yes in all platform projects 

- carthage build --platform [your_pick]

**Comment by jeffh** [comment]
Any update @GregoryMaks?

**Comment by GregoryMaks** [comment]
Good news.
Checked it now with XCode 8.0 and Carthage 0.17.2.

```carthage update``` went fine this time, for all platforms.

The only thing that needed to be changed is setting the SWIFT_VERSION in Kiwi, because it seems that Nimble already utilizes Swift 3.0 which is great.

I think it means that the issue can be closed for now. 
Thanks everyone.

**Comment by Happy1983** [comment]
in cartfile:
github "Quick/Quick"
github "Quick/Nimble"


in build settingL
Scroll down – It is right near the bottom and look for **Use Legacy Swift Language** Version. To the Right, there are three options when you click:

Unspecified
Yes
No

set YES qorked for me
