### ISSUE TITLE
pod create lib, compilation errors

### ISSUE THREAD

**Issue by fmaxx** [Quick/Nimble#335]
I've tried to create own pod library with "pod lib create [name]" with Quick/Nimble.
After that, I'm getting errors in DSL.swift (XCode7, swift2):

![image](https://cloud.githubusercontent.com/assets/1931657/18523693/c21a7766-7ace-11e6-8c5b-62cc71cc5493.png)

**Comment by fmaxx** [comment]
![image](https://cloud.githubusercontent.com/assets/1931657/18523717/dec8f1a8-7ace-11e6-8170-b33b8a492df8.png)

**Comment by jeffh** [comment]
Hey @fmaxx, what does you Podfile look like? What version of Nimble are you using?

**Comment by fmaxx** [comment]
@jeffh seems like my mistake, I've checked XCode (7.0) and I tested with Swift1.
