### ISSUE TITLE
Swift 3 issues

### ISSUE THREAD

**Issue by tlandsmancars** [Quick/Nimble#338]
Hi I converted to Swift 3 last week. 
I'm using versions:
Using Nimble (4.1.0)
Using Quick (0.9.3)

Are these the latest versions?  Have they been converted to support Swift 3? 
Because currently I running into compile issues:

![screen shot 2016-09-19 at 9 27 14 am](https://cloud.githubusercontent.com/assets/17576176/18635622/45745116-7e4b-11e6-8ce6-626c8c1ea0c3.png)

**Comment by wongzigii** [comment]
Hi @tlandsmancars 
Nimble with Swift 3 support will be released in the next few days. 

You can change your podfile to latest commit if you need a workaround :

`pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :commit => 'db706fc'`

**Comment by thinkrad** [comment]
Hey @wongzigii,

Will the Swift 3 Nimble release coincide with a Swift 3 release for Quick?

**Comment by wongzigii** [comment]
@thinkrad See https://github.com/Quick/Quick/pull/601
