### ISSUE TITLE
Release new version to CocoaPods

### ISSUE THREAD

**Issue by wongzigii** [Quick/Nimble#339]
We are reaching v5.0.0.! 
Should we release a new version and push Nimble to CocoaPods? 😃

**Comment by AnthonyMDev** [comment]
I would really like to see this happen soon. I'm having to depend directly on the master branch from all my pod files right now.

**Comment by jeffh** [comment]
I'm looking into cutting a release tonight when I get free time. I just need to verify the release will work in the various setups we support.

**Comment by wongzigii** [comment]
Nimble has been updated to v5.0.0 🎉
