### ISSUE TITLE
Argument type `NMBMatcher` does not conform to expected type `Matcher`

### ISSUE THREAD

**Issue by ksm** [Quick/Nimble#356]
Migrating my test suite to Swift 3 now, and have gotten a ton of these errors:

<img width="733" alt="screen shot 2016-10-21 at 16 33 51" src="https://cloud.githubusercontent.com/assets/747910/19593897/e43bd790-97ac-11e6-9ca3-d95cda6650a2.png">

The only way I figured out to fix this is to change to e.g.:
`expect(loadedSecret).to(beNil())`

Was I doing it wrong all the time? What changed?

**Comment by jeffh** [comment]
Hey @ksm, what version of Swift and Nimble are you using?

**Comment by lauracalinoiu** [comment]
I have those kind of errors too:

<img width="866" alt="screen shot 2016-10-24 at 11 14 55" src="https://cloud.githubusercontent.com/assets/948556/19634768/32c20da0-99db-11e6-9e93-4d2c7732c4d3.png">

My Swift version is 3.0 and Nimble 5.0.0
Thanks

**Comment by wongzigii** [comment]
@lauracalinoiu @ksm Have you try the latest Nimble v5.1.0 ?

**Comment by jeffh** [comment]
Hey @lauracalinoiu,

Did you perform a clean build? What's the type definition of `viewModel.wikiURL`?

**Comment by ksm** [comment]
@jeffh Swift 3 (Xcode 8.0 8A218a) and Nimble v5.0.0. 

I ended up fixing all specs by replacing any `beFalsy()` or `beTruthy()` matcher that SourceKit didn't like with `to(beNil())` or `toNot(beNil())`.

**Comment by lauracalinoiu** [comment]
I did a clean build. `viewModel.wikiURL` definition is `var imageURL: URL? `

**Comment by lauracalinoiu** [comment]
Ok, my mistake was that I compared a `NSURL` versus a `URL`:

`expect(viewModel.wikiURL).to(equal(url))`, type of `wikiURL` was `URL?`, while `url` is a `NSURL`

Thanks for the help, guys. @jeffh your question was a real help.

**Comment by darrarski** [comment]
I have very similar problem when comparing two generic enums:
```swift
enum MyEnum<T> {
    case aCase(value: T)
}

extension MyEnum where T: Equatable {
    static func ==(lhs: MyEnum<T>, rhs: MyEnum<T>) -> Bool {
        switch (lhs, rhs) {
        case (.aCase(let lValue), .aCase(let rValue)):
            return lValue == rValue
        }
    }
}
```

For given two variables:
```swift
let case1: MyEnum<String> = .aCase(value: "a")
let case2: MyEnum<String> = .aCase(value: "a")
```

This code works correctly:
```swift
expect(case1 == case2).to(beTrue())
```

But this code is not compiling:
```swift
expect(case1).to(equal(case2))
```

With Nimble 5.0.0, it produces compile-time error:
> Argument type 'NMBMatcher!' does not conform to expected type 'Matcher'

With Nimble 5.1.0, it produces compile-time error:
> Cannot invoke 'to' with an argument list of type '(NMBMatcher)'

Any ideas what's wrong?

I am using Quick 0.10.0

**Comment by wongzigii** [comment]
Hey @darrarski ,  I believe your issue is related to #173 .

Since `case1` and `case2` is `MyEnum` type so it will make sense to  implement Equatable for MyEnum. 

````swift
enum MyEnum<T> {
    case aCase(value: T)
}

extension MyEnum: Equatable {
    static func ==<T>(lhs: MyEnum<T>, rhs: MyEnum<T>) -> Bool {
        switch (lhs, rhs) {
        case (.aCase(let lvalue), .aCase(let rvalue)):
            if lvalue is String && rvalue is String {
                return lvalue as! String == rvalue as! String
            }
        }
        return false
    }
}
````

then you got:

````swift
expect(case1).to(equal(case2))
````

**Comment by darrarski** [comment]
@wongzigii I already did it, but I only make the `Equatable` extension valid for `MyEnum` that has equatable `T`, otherwise it makes no sense to compare them. Am I right?

If you look at my previous comment, you will see that I included my implementation of `MyEnum` `Equatable` extension.

**Comment by ikesyo** [comment]
> I assume it's just a workaround, I wonder if it's possible to improve Nimble, so it handles such matching automatically?

@darrarski  This is a limitation of current Swift version unfortunately. We should wait for the [conditional conformance](https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md#conditional-conformances-) feature of Swift generics.

**Comment by wongzigii** [comment]
Hm, I miss your previous comment above, and the link from @ikesyo is totally the feature what I've looking for ! .

I was trying to use `extension MyEnum: Equatable where T: Equatable` and got this error: 

> extension of type 'MyEnum' with constraints cannot have an inheritance clause

Since that feature is still on the way, here is a workaround for this, just FYI @darrarski  , you might need to  combine your extension and enum definition :

````swift
enum MyEnum<T: Equatable>: Equatable {
    case aCase(value: T)
    
    static func ==<T: Equatable>(lhs: MyEnum<T>, rhs: MyEnum<T>) -> Bool {
        switch (lhs, rhs) {
        case (.aCase(let lValue), .aCase(let rValue)):
            return lValue == rValue
        }
    }
}
````
