### ISSUE TITLE
Combining assertions

### ISSUE THREAD

**Issue by jeffh** [Quick/Nimble#369]
From: https://github.com/Quick/Quick/issues/432

It would seem to be useful to be able to generate two tests by eg:

```swift
expect { try someFunc() }.toNot(throwError()).to(equal(5))
```

This form doesn't work, I don't see any docs about how to achieve the same thing, or is there some reason that eludes me that this isn't a good idea?

**Comment by sigito** [comment]
Since the Expectation is an immutable structure, is there any reason why we cannot just extend its methods with an additional result returning `self`?

**Comment by jeffh** [comment]
I don’t think so. Old versions of Swift had issues with return values and closures. I think there just needs to be a test / verification that something like this works:

it(“should work”) {
    expect { try someFunc() }.toNot(throwError()).to(equal(5))
}

The swift compiler couldn’t figure out that `it` only accepted `Void` as a return value and incorrectly inferred the closure to have a return value. I’m pretty sure that has been fixed in recent Swift versions.

- Jeff
