### ISSUE TITLE
Swift 3 XCode 8 Error.

### ISSUE THREAD

**Issue by rlam3** [Quick/Nimble#373]
I'm getting the following error: 

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Is there a workaround or specific versions of quick and nimble i'm supposed to configure to?
I'm already on 1.0.0 on Quick and 5.1.1 on Nimble

**Comment by jeffh** [comment]
Hey @rlam3,

 - What version of Xcode version are you using?
 - Are you using a package manager (Carthage, Cocoapods, SwiftPM)? What version are they?

**Comment by rlam3** [comment]
I'm using 

cocoapods 1.1.1
Xcode 8.1

**Comment by jeffh** [comment]
Closing. This seems to be a cocoapods issue (see https://github.com/CocoaPods/CocoaPods/issues/5521). You'll need the following in your Podfile until cocoapods fixes it:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # to whatever swift version you're using
    end
  end
end
```
