### ISSUE TITLE
Compile error using "allPass" matcher using Quick/Nimble

### ISSUE THREAD

**Issue by jraldrin** [Quick/Nimble#375]
Hi,

I get the following error message when trying to use the "allPass" matcher(I think thats the correct term).
Cannot invoke 'to' with an argument list of type '(NMBMatcher)'

I created a xcode project with a unit tests project.
Edited Embed Swift std lib build option
created podfile
installed pods w/no warnings/errors

I added the following test 

class SpikeTests: QuickSpec {
    override func spec() {
        it("") {
              expect([1,2,3,4]).to(allPass({$0 < 5}))  // took this line from Nimble project
        }
    }
}

I'm using XCode 8.1 with Swift 3
PODS:
  - Nimble (5.1.1)
  - Quick (1.0.0)
COCOAPODS: 1.1.1

Contents of podfile

ef testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'SpikeSetupQuickNimble' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpikeSetupQuickNimble

  target 'SpikeSetupQuickNimbleTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

end

Selecting "Jump To Definition" leads me to the following signiture

public func allPass(_ matcher: Any) -> NMBMatcher

located in what I think is a generated file/artifact named "Nimble.DSL"

Weird, If I "clean" the project "Jump to Definition" takes me to:

NIMBLE_SHORT(id<NMBMatcher> allPass(id matcher),
             NMB_allPass(matcher));

located in Nimble.DSL.h 

Thanx for any help, hope this makes sense.

jra

**Comment by ikesyo** [comment]
That is because `<` operator which takes optional values is removed in Swift 3: [SE-0121](https://github.com/apple/swift-evolution/blob/master/proposals/0121-remove-optional-comparison-operators.md)

The operator is re-defined in Nimble just for testing purpose here: https://github.com/Quick/Nimble/blob/v5.1.1/Tests/NimbleTests/Matchers/AllPassTest.swift#L6

So what you should do is using forced unwrapping or optional binding in the closure:

```swift
// Forced unwrapping
expect([1,2,3,4]).to(allPass {$0! < 5})
// Optional binding
expect([1,2,3,4]).to(allPass { x in
    if let x = x {
        return x < 5
    }
    return false
})
```
