### ISSUE TITLE
Nimble fails to compile on latest Swift 3.1 snapshot

### ISSUE THREAD

**Issue by sharplet** [Quick/Nimble#387]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Download the [latest Swift 3.1 development snapshot](https://swift.org/download/#snapshots) and tried to compile Nimble.

### What did you expect to happen?

It compiles.

### What actually happened instead?

A number of build errors occur, also relating to conditional compilation directives used inside closures. I reproduced this outside of Nimble and raised a bug on bugs.swift.org: https://bugs.swift.org/browse/SR-3612.

### Environment

List the software versions you're using:

 - Quick: n/a
 - Nimble: master
 - Xcode Version: n/a
 - Swift Version: DEVELOPMENT-SNAPSHOT-2017-01-05-a

Please also mention which package manager you used and its version.

n/a

### Project that demonstrates the issue

https://bugs.swift.org/browse/SR-3612

**Comment by modocache** [comment]
Thanks for the report, @sharplet! I assume this should be fixed in [apple/swift](https://github.com/apple/swift), is that what you had in mind as well?

**Comment by sharplet** [comment]
Yep, this seems like a pretty clear regression to me. I mainly raised it here for visibility. It would be possible to work around this by extracting the conditionally compiled code out of the closure expressions and into separate functions, but that doesn't seem worthwhile to me.

**Comment by jeffh** [comment]
Hey @sharplet,

According to the JIRA issue, it seems like it's fixed on latest snapshots. Is that correct?

**Comment by sharplet** [comment]
Seems to be working 👍

**Comment by jeffh** [comment]
Thanks for following up @sharplet! 👍
