### ISSUE TITLE
Float / Double matchers should use FloatingPoint protocol

### ISSUE THREAD

**Issue by jeffh** [Quick/Nimble#394]
Since Swift has simplified the crazy protocol change for numerics, Nimble should switch to use the new protocol instead of simplifying it down to `Double` types.

`beCloseTo` matcher is the obvious one that needs fixing, but others that explicitly use `Double` should be updated as needed.

**Comment by ikesyo** [comment]
> `beCloseTo`

The problem here is that we can't provide `DefaultDelta` value naturally since that must be a generic value of `T: FloatingPoint`.
