### ISSUE TITLE
Build Fails: `setjmp` in CwlCatchBadInstructionPOSIX no longer available. 

### ISSUE THREAD

**Issue by aaroncrespo** [Quick/Nimble#395]
- [x ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Compile under Xcode 8.3 beta2

### What did you expect to happen?

Successfully compile

### What actually happened instead?

```
/Users/***/src/apple-networking/Carthage/Checkouts/apple-nimble/Sources/Lib/CwlPreconditionTesting/CwlPreconditionTesting/CwlCatchBadInstructionPOSIX.swift:89:5: error: 'setjmp' is unavailable: Functions that may return more than one time (annotated with the 'returns_twice' attribute) are unavailable in Swift
A shell task (/usr/bin/xcrun xcodebuild -project /Users/***/src/apple-networking/Carthage/Checkouts/apple-nimble/Nimble.xcodeproj -scheme Nimble-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,id=8487929D-D93C-495E-BB53-E8B0FBD57385" -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

### Environment
Xcode 8.3 beta 2

List the software versions you're using:

 - Quick: *?.?.?*
 - Nimble: *?.?.?*
 - Xcode Version: Version 8.3 beta 2 (8W120l)
 `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Carthage building from source

### Project that demonstrates the issue

Nimble Project  itself and ⌘ + B in the given environment error doesn't progress past x86_64 arch.

**Comment by aaroncrespo** [comment]
https://github.com/mattgallagher/CwlPreconditionTesting/issues/7

**Comment by aaroncrespo** [comment]
Barring an upstream fix to the approach CwlPreconditionTesting uses I think the fix is unfortunately getting rid of support for precondition expectations via CwlPreconditionTesting.

**Comment by modocache** [comment]
I wonder how many people use precondition testing? (It's times like this I wish we had analytics of some kind.) Could we simply remove it and bump Nimble's major version, at least for now?

**Comment by aaroncrespo** [comment]
I use it, but I'm not married to it and only in a few places. Would like to hear what other users are thinking... Might also be interesting to see if people would want to keep the feature for obj-c but not for swift.  I don't know the maintainer thoughts on cross language feature parity.

**Comment by jeffh** [comment]
IMO, issues is probably not the best place to poll users (agreed, analytics would be nice). We could bump major versions, but I’d be more hesitant to add this feature back in. Features that come in-and-out are features probably not worth having (imagine an API feature that was only available every other quarter).

Since it’s to support a swift-specific feature, is having it in Objective-C only isn’t particularly useful? Or did you mean just when the Objective-C runtime is available? In general, we usually skew to Swift-only features than ObjC-only features, but I’m certainly not against any ObjC only features.

- Jeff

**Comment by modocache** [comment]
It looks like there may not be cause to take it out anyway: https://github.com/mattgallagher/CwlPreconditionTesting/commit/e11db1661274909fb820a2bff57f4effb578bf9d

**Comment by aaroncrespo** [comment]
@modocache @jeffh  checkout #397 Cocoapods CI tasks is failing due to conditional imports that exclude required headers on tvOS. Not familiar with the rationale for that and if I was over broad in updating the Cwl code on various platforms.

**Comment by jeffh** [comment]
Thanks, I've merged this into master. Closing! 🙌

**Comment by NachoSoto** [comment]
Any chance you could make a release with this fix? 🙏

**Comment by jeffh** [comment]
Hey Nacho, I forgot getting around to notify this thread, but this has been fixed in the latest release.

Cheers,
Jeff
