### ISSUE TITLE
toEventually bad access

### ISSUE THREAD

**Issue by szweier** [Quick/Nimble#396]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Used toEventually with the following line of code.

```
expect(view!.alpha).toEventually(equal(1.0))
```

### What did you expect to happen?

I expected the command to run successfully and validate the test.

### What actually happened instead?

Instead the tests crashed at the following code

```            
while self.promise.asyncResult.isIncomplete() {
  // Stopping the run loop does not work unless we run only 1 mode
  _ = RunLoop.current.run(mode: .defaultRunLoopMode, before: .distantFuture)
}
``` 
specifically the _ = RunLoop line.

### Environment

 - Quick: *1.0.0*
 - Nimble: *6.0.1*
 - Xcode Version: *8.2.1 (8C1002)*
 - Swift Version: *3.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.1.1*
 - Swift Package Manager *3.0.2 (swiftpm-11750)*

**Comment by jeffh** [comment]
Hey @szweier,

How are you managing the `view`? Could you provide more code context for the view lifecycle during the test run?

**Comment by szweier** [comment]
After some more digging it looks like there's likely an issue in the overall setup of the tests I currently have.  A small scale test has shown that toEventually is working.  Will do more digging and open again if it proves necessary.

**Comment by jeffh** [comment]
Thanks for follow following up!
