### ISSUE TITLE
Use of throwAssertion causing Segmentation Fault 11

### ISSUE THREAD

**Issue by abbeycode** [Quick/Nimble#404]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Compile unit tests against an iOS simulator

### What did you expect to happen?

Unit tests compile

### What actually happened instead?

The following compiler error:

```
Segmentation fault: 11
```

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 6.0.1
 - Xcode Version: 8.2.1
 - Swift Version: `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.2.0

### Project that demonstrates the issue

I didn't create a sample project yet, in case I was doing something obviously wrong. I will follow up with one if it's warranted.

The line causing the `segfault` (it compiles fine when I remove it) is:

``` Swift
#if arch(x86_64)
expect{ try StatementThatThrowsFatalError() }.to(throwAssertion())
#endif
```

**Comment by ikesyo** [comment]
Seems that `throwAssertion` only works on x86_64 with Objective-C runtime: https://github.com/Quick/Nimble/blob/v6.0.1/Sources/Nimble/Matchers/ThrowAssertion.swift#L50-L52

        fatalError("The throwAssertion Nimble matcher can only run on x86_64 platforms with " +
            "Objective-C (e.g. Mac, iPhone 5s or later simulators). You can silence this error " +
            "by placing the test case inside an #if arch(x86_64) or _runtime(_ObjC) conditional statement")

**Comment by abbeycode** [comment]
@ikesyo Yes, sorry, I added the `#if` I'm using to the issue

**Comment by jeffh** [comment]
Hey @abbeycode,

Do you think this related to #400 and #406? If so, then PR https://github.com/Quick/Nimble/pull/407 may help.

**Comment by abbeycode** [comment]
@jeffh It could be related. I'll see if that PR fixes it.

**Comment by jeffh** [comment]
I've merged the PR on master. So I'm closing this issue now. Feel free to reopen it if it's still a problem

**Comment by abbeycode** [comment]
Sounds good. Do you plan to cut a release soon?

**Comment by jeffh** [comment]
Yep, when I get a good block of time to verify master in the various build configurations.
