### ISSUE TITLE
memory leak with toEventually

### ISSUE THREAD

**Issue by ryanfitz** [Quick/Nimble#405]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Created a test using a `toEventually` block. I've found that this retains the object being tested for the entire test suite.

### What did you expect to happen?

I expect that the object under test would be released after the specific test function finished executing.

### What actually happened instead?

The object remained in memory for the entire test suite run, well after the specific test had finished running.

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 6.0.1
 - Xcode Version: 8.2.1
 - Swift Version: 3

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.2.0

### Project that demonstrates the issue

```swift
import XCTest
import Quick
import Nimble

@testable import NimbleExample

var allocations = 0

class Foo {
  var count = 0

  init() {
    allocations += 1
  }

  deinit {
    print("foo dealloced")
    allocations -= 1
  }
}

class NimbleMemoryLeakExampleSpec: QuickSpec {
  override func spec() {
    describe("memory leak") {
      it("allocates object") {
        let foo = Foo()
        expect(allocations).to(equal(1))

        expect(foo.count).toEventually(equal(0))
      }

      it("but is never released") {
        expect(allocations).toEventually(equal(0)) // This will fail and foo is being retained by AwaitPromiseBuilder<Bool>
      }
    }
  }
}
```

**Comment by jeffh** [comment]
Hey Ryan, thanks for filing an issue!

That’s definitely looks like a problem. If you could submit a pull request that would be great! Otherwise we’ll get around to fixing this issue when we get the time available to do this.

- Jeff

**Comment by ricardopereira** [comment]
@jeffh Any tip? Is it possible to analyse this issue with Instruments? Never done that for XCTestSuite.

@ryanfitz Did you try with an `autoreleasepool`?

**Comment by jeffh** [comment]
It's possible to use instruments, although you'll probably need to tick some flags in the schema settings or manually attach to the process.

**Comment by ryanfitz** [comment]
@jeffh I finally got some time to investigate this and found the reason it is happening. The timeout DispatchSourceTimer is never properly canceled out so its [event handler](https://github.com/Quick/Nimble/blob/master/Sources/Nimble/Utils/Async.swift#L182) remains in memory indefinitely and retains a reference to itself which is an `AwaitPromiseBuilder`.

If I force cancel the `timeoutSource` timer then memory is freed as expected. However, I don't have a final solution yet, as forcing a cancel causes a few async tests to fail. This bit of a timeout code is very intricate, if someone with more experience with this area of the code has any suggestions that would be appreciated.
