### ISSUE TITLE
Intermittent "undeclared identifier 'BadInstructionException'" error on build

### ISSUE THREAD

**Issue by lazerwalker** [Quick/Nimble#406]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

When Nimble is built as part of our test suit, it often fails out with this error:

```
/Nimble/Sources/Lib/CwlPreconditionTesting/CwlPreconditionTesting/CwlBadInstructionException.swift:48:16: error: use of unresolved identifier 'bad_instruction_exception_reply_t'
                        var reply = bad_instruction_exception_reply_t(exception_port: 0, exception: 0, code: nil, codeCnt: 0, flavor: nil, old_state: nil, old_stateCnt: 0, new_state: nil, new_stateCnt: nil)
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'd say this happens 15-20% of the time on our Jenkins box, and a bit less frequently (but still non-zero) locally.

Issues such as https://github.com/mattgallagher/CwlPreconditionTesting/issues/5 suggest this was a known issue, but also that it's theoretically been fixed. Is this known to still be an issue? Is there a workaround that simply needs better documentation/visibility?

(I'm not sure whether this should be opened here or in CwlPreconditionTesting; opening there as https://github.com/mattgallagher/CwlPreconditionTesting/issues/8. My apologies if this is the wrong place, and feel free to delete/close as appropriate!)

(Also, to tag it, I assume #400 is the same core issue)

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 6.0.1
 - Xcode Version: Version 8.2.1 (8C1002)
 - Swift Version: Xcode default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Git submodules (I know, I know...)

**Comment by jeffh** [comment]
Hey @lazerwalker, thanks for filing an issue!

I think this is mostly because Nimble hasn't update CwlPreconditionTesting yet, I have a WIP branch that might have this fixed. Let me know if that branch works for you.

**Comment by lazerwalker** [comment]
Ah, awesome. I really appreciate the quick reply, and you throwing together that PR!

Working on verifying the fix, but it might take a little while longer — our project is chock-full of some incidental complexity that ultimately means pointing our Nimble at a fork or a GitHub PR branch is frustratingly harder than it should be. Hopefully will have an update soon.

**Comment by lazerwalker** [comment]
We managed to get this integrated (ugh, recursive git submodules...). Will check back with you in a day or two when it should become clear whether this has cleared up or not.

Thanks again!

**Comment by jeffh** [comment]
I've merged this PR into master. Let me know if this is a problem! 😃
