### ISSUE TITLE
Swift 3.1 SIL crash in CwlCatchException.swift

### ISSUE THREAD

**Issue by benasher44** [Quick/Nimble#412]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Build using Swift 3.1

### What did you expect to happen?

Build successfully.

### What actually happened instead?

SIL crash: https://bugs.swift.org/browse/SR-4345

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *6.0.1*
 - Xcode Version: *8.3 beta 5*
 - Swift Version: *3.1* (3.1-DEVELOPMENT-SNAPSHOT-2017-03-23-a)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.2.0* (Use `pod --version` in Terminal)

Hi! While trying out the Xcode 8.3 betas, I've seen different versions of a crash in this file. I'm not sure if you all have seen this, are aware of it, or know of a work around. I'm hoping that this will be fixed in Swift 3.1 before it's released, but we're getting pretty late into the Xcode 8.3 betas with no fix in sight. I thought it might be a good idea to bring this up in the Nimble project in case this continues into the final Swift 3.1 release. Thanks for your help/consideration!

**Comment by benasher44** [comment]
In an earlier beta, I saw this crash and reported and closed it here: https://bugs.swift.org/browse/SR-4258

**Comment by jeffh** [comment]
Hey @benasher44, Could you try the freshly cut Nimble `v6.1.0`? `6.1.0` includes an updated version of CwlPreconditionTesting that should solve this issue.

**Comment by benasher44** [comment]
@jeffh thanks for getting the update out! Somehow the compiler crash I was seeing magically disappeared. I'm unsure why the [changes that occurred since the snapshot I was using](https://github.com/apple/swift/compare/swift-3.1-DEVELOPMENT-SNAPSHOT-2017-03-24-a...swift-3.1-RELEASE) would have fixed anything, since the only change appears to be how `swift` prints the version. There's probably some gap in my understanding of how toolchain releases work. Thanks again, and sorry for the trouble!
