### ISSUE TITLE
Does Nimble support fatalError from Swift tests and Swift code?

### ISSUE THREAD

**Issue by holmes** [Quick/Nimble#413]
### What did you do?

I'm attempting to write a Swift test that is checking for a `fatalError` coming from Swift code. 

### What did you expect to happen?

I expected the test to catch the `fatalError`. The README says it should work, but the code seems to say otherwise:

* This feature is only available in Swift.
* It is only supported for x86_64 binaries, meaning you cannot run this matcher on iOS devices, only simulators.

### What actually happened instead?

I'm receiving this error:
```
The throwAssertion Nimble matcher can only run on x86_64 platforms with Objective-C (e.g. Mac, iPhone 5s or later simulators). You can silence this error by placing the test case inside an #if arch(x86_64) or _runtime(_ObjC) conditional statement: file /work/appointments/Frameworks/Nimble/Sources/Nimble/Matchers/ThrowAssertion.swift, line 51
```

### Environment

List the software versions you're using:
 - Quick: N/A
 - Nimble: 6.0.1
 - Xcode Version: `8.2.1`
 - Swift Version: `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

Using as a submodule

**Comment by holmes** [comment]
I have no idea what's going on - but a project clean and rebuild got it working. 

Ignore me

**Comment by jeffh** [comment]
Thanks for following up @holmes. I'm glad you figured out your issue 😄

**Comment by jeffh** [comment]
Thanks for filing an issue and following up!
