### ISSUE TITLE
`toEventuallyNot` passes when it should not on Nimble 7.0.0

### ISSUE THREAD

**Issue by zacharynguyen** [Quick/Nimble#424]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I created an asynchronous test:

```swift
var names: [String]? = nil
expect(names).toEventuallyNot(beNil())
```

### What did you expect to happen?

The test should have failed because `names` was never assigned to any value.

### What actually happened instead?

The test passed.

### Possible explanation

`func async<T>` times out with `.toNotMatch`while `toEventuallyNot` expects `.toNotMatch` to pass; which is what happened in this case and caused the test to pass.

### Environment

 - Quick: *1.1.0*
 - Nimble: *7.0.0*
 - Xcode Version: *8.3.2 (8E2002)*
 - Swift Version: *Xcode Default*

Package manager used:

 - Carthage: *0.22.0*

**Comment by Nandiin** [comment]
I found same behavior.

**Comment by jeffh** [comment]
Thanks @zacharynguyen for filing an issue. I can reproduce the issue and a fix will be coming shortly.
