### ISSUE TITLE
Expectations are not behaving as expected!

### ISSUE THREAD

**Issue by gavanchan-outware** [Quick/Nimble#425]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Related to #424 .

In an attempt to resolve #424, I thought to made changes to `AsyncMatcherWrapper.swift`. However, I wanted to approach this with tests written alongside / before the implementation.

As well as the (possibly) erroneous asynchronous matching that is mentioned in #424, there are other faults that I am running into.

```swift
// This assertion _correctly_ passes in Nimble 7.0.0.
expect(FooError.foo(1)).to(matchError(FooError.foo(1)))

// This assertion _incorrectly_ passes in Nimble 7.0.0,
// but does _correctly_ fail in Nimble 6.1.0.
expect(FooError.foo(1)).to(matchError(FooError.foo(2))) 
```

This _should_ have been caught by tests such as those in `BeCloseToTest.swift`, or `testMatchPositiveMessage()` in `MatchErrorTest.swift`, but (what I think is) a logical fault in `failsWithErrorMessage(_:file:line:preferOriginalSourceLocation:closure:)` inside `utils.swift` was hiding this error! 

This logical fault may be _how_ the underlying issue with #424 made it through the tests (and into the release in the first place).

Before the change to `utils.swift`, the following code would pass:

```swift
failsWithErrorMessage("expected to match error <parameterized(2)>, got <parameterized(1)>") {
  expect(EquatableError.parameterized(x: 1)).to(matchError(EquatableError.parameterized(x: 2)))
}
```

This is as you would expect (logically). __However__, bearing in mind that, in Nimble 7.0.0, it is apparent that this assertion ___incorrectly passes___ and _does not_ fail at all, this should test should have __failed__ with the error message `"expected failure message, but got none"`.

Additionally, tests that had already existed in the codebase made little sense and were signs that testing for failure with an error message was not working as expected to begin with.

```swift
// BeCloseToTest.swift

func testBeCloseToWithNSNumber() { ... }

func testBeCloseToWithCGFloat() {
  // This assertion is valid and _should_ pass.
  expect(CGFloat(1.2)).to(beCloseTo(1.2001))

  // Since '1.2' _is_ close to '1.2001', this inner assertion should _pass_,
  // meaning that the outer assertion should _fail_, citing no failure message.
  //
  // A similar test (but using 'NSNumber') is written just above this.
  // The corresponding test there (correctly) 
  // states `toNot(beCloseTo(1.2001, within: 1.0))`.
  failsWithErrorMessage("expected to not be close to <1.2001> (within 1), got <1.2>") {
    expect(CGFloat(1.2)).to(beCloseTo(1.2001, within: 1.0))
  }
}
```

A makeshift addition to `utils.swift` augments this to behave correctly for the cases that I have listed above, raising 24 test failures on Nimble. This includes an interesting case of `NSNumber` and `__NSCFNumber` being expected to satisfy `isMember(of:)`.

```swift
func failsWithErrorMessage(_ messages: [String], file: FileString = #file, line: UInt = #line, preferOriginalSourceLocation: Bool = false, closure: @escaping () throws -> Void) {
...
  // The assertion only _truly_ resulted in the failure
  // if the 'lastFailure' was _not_ a 'success'
  // __AND__
  // a matching failure message was found in the assertions.
  if foundFailureMessage, let lastFailure = lastFailure, !lastFailure.success {
    continue
  }
...
  // If the 'lastFailure' was not a success (as expected),
  // but the message was _not_ found, then this failure-assertion has
  // failed because the errors don't match.
  if let lastFailure = lastFailure, !lastFailure.success {
    message = "Got failure message: \"\(lastFailure.message.stringValue)\", but expected \"\(msg)\""
  } else {
    // In all other cases, this means that a failure was expected,
    // but a failure message was not provided.
    // (Potentially because the assertion did _not_ fail,
    // and, instead, actually passed)
    message = "expected failure message, but got none"
  }
...
}
```

### What did you expect to happen?

- As per #424, but for many _other_ matchers / `Predicate`s as well.

### What actually happened instead?

`Expressions` which should ___not___ have satisfied some `Predicate`s erroneously _did_ satisfy said predicates.

### Environment

 - Quick: *n/a*
 - Nimble: *7.0.0*
 - Xcode Version: *8.3.1 (8E1000a)*
 - Swift Version: *Xcode Default*
 - Carthage: *0.18.1*

### Project that demonstrates the issue

https://github.com/chamander/Nimble/tree/424-correctly-failing-an-async-expectation

<img width="1392" alt="nimble-tests" src="https://cloud.githubusercontent.com/assets/16008644/25889616/bbf9ac54-35ad-11e7-9026-573c6e9a4dc2.png">

**Comment by chamander** [comment]
If there are any hints as to what may be causing the predicates to misbehave, I would be keen to have a look. 🙂

**Comment by chamander** [comment]
Pinging @Quick/core

**Comment by gavanchan-outware** [comment]
Perhaps I lack context. Is there a reason why one of these would pass, but not the other:

```swift
// 1.
expect(["a", "b", "c"]).to(contain(["a", "bar"]))

// 2.
expect(["a", "b", "c"]).to(contain(["bar", "b"]))
```

I believe that these should both result in failures, but the tests written in this image seem to indicate otherwise:

<img width="1023" alt="screen shot 2017-05-12 at 9 20 54 pm" src="https://cloud.githubusercontent.com/assets/16008644/25996176/42682a20-3759-11e7-8504-62cf69fd7726.png">

**Comment by jeffh** [comment]
Hey @gavanchan-outware / @chamander, thanks for filing an issue.

I can reproduce the issue, although I can also reproduce the same failure on Nimble v6.1.0. I think this behavior regressed from a Swift compiler change when generics dispatch implementation was probably changed.

------------------------

For a little bit about the code context, `failsWithErrorMessage` is a utility helper to test failure messages in Nimble's test suite. Instead of letting the test failures bubble up to XCTest, and thus always causing the test suite to fail, `failsWithErrorMessage` expects an error from Nimble by replacing it's error reporting interface with its own to observe for errors. I'd recommend looking at the `AssertionHandler` protocol or the `NimbleAssertionHandler` global for more details of the inner workings of that layer. In short, XCTest integration is isolated to `NimbleXCTestHandler` (and it's possible to use Nimble without XCTest).

------------------------

As for your last message, `#2` is different from the code that's listed in the test suite (`toNot` instead of `to`):

```swift
expect(["a", "b", "c"]).toNot(contain("bar", "b"))
```

**Comment by jeffh** [comment]
Ah, I see the issue with `failsWithErrorMessage`. That's a good find. A better change is to modify the inner loop of `failsWithErrorMessage` to be:

```swift
for assertion in recorder.assertions {
    lastFailure = assertion
    if !assertion.success && assertion.message.stringValue == msg{
        foundFailureMessage = true
        break
    }
}
```

Which shows the same 24 failures that you're mentioning.

**Comment by jeffh** [comment]
I've left some WIP changes on my branch attached as a PR #428. I'll see if I can try and get to this tomorrow when I get some time.

**Comment by jeffh** [comment]
Hey @gavanchan-outware / @chamander,

I've merged a fix into master. I'll probably cut a patchfix release next week. Let me know if this solves the issues you've been getting.

Thanks,
Jeff

**Comment by chamander** [comment]
Hey @jeffh, it's been almost two weeks and nothing that would raise a red flag has come up, so this looks great!

Thanks for the update! 🙂
