### ISSUE TITLE
Can't compile Nimble pod for tvOS

### ISSUE THREAD

**Issue by darrarski** [Quick/Nimble#430]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Add Nimble as a dependency to tvOS unit tests target via CocoaPods

### What did you expect to happen?

Xcode should compile Nimble when compiling tvOS unit tests target it was added to

### What actually happened instead?

Xcode can't compile `Nimble-tvOS` framework added by CocoaPods. Build fails with error:

> UnderControl/Pods/Nimble/Sources/Nimble/Nimble.h:6:9: Include of non-modular header inside framework module 'Nimble.Nimble': 'UnderControl/Pods/Nimble/Sources/Lib/CwlPreconditionTesting/CwlPreconditionTesting/Mach/CwlPreconditionTesting.h'

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.0*
 - Xcode Version: *8.3.2 (8E2002)*
 - Swift Version: *3.1 (Xcode Default)*
 - Cocoapods: *1.2.1*

### Project that demonstrates the issue

[darrarski/UnderControl](https://github.com/darrarski/UnderControl)

The project contains several unit tests targets:

- UnderControlTests-iOS
- UnderControlTests-macOS
- UnderControlTests-tvOS

All tests targets have Nimble dependency added via CocoaPods. `UnderControlTests-iOS` and `UnderControlTests-macOS` compiles with Nimble and runs tests without an issue. The only problem is with `UnderControlTests-tvOS` target, which Xcode can't compile due to mentioned error.

### What I tried to do in order to solve the issue

I noticed that some files are not included in `Nimble-tvOS` framework, but are included in both `Nimble-iOS` and `Nimble-OSX` frameworks. I tried to add those files manually to `Nimble-tvOS` framework:

- CwlPreconditionTesting.h
- CwlCatchException.h
- CwlBadInstructionException.swift
- CwlDarwinDefinitions.swift
- CwlCatchBadInstruction.swift

Eventually I've got to the point where `Nimble-tvOS` can't be build because of this error:

> CwlCatchBadInstruction.swift:106:5: 'mach_msg' is unavailable

Not sure what I am doing ¯\\__(ツ)_/¯ so decided to look for help here.

**Comment by jeffh** [comment]
Hey @darrarski,

I cloned the repo you linked to and was able to build `UnderControlTests-tvOS` target:

- `git clone https://github.com/darrarski/UnderControl`
- `pod install`
- open `UnderControl.xcworkspace`
- Select `UnderControlTests-tvOS`
- ⌘U and see tests pass

Although I'm using Xcode 8.3.3 (8E3004b). Did you try cleaning your derived data?

**Comment by darrarski** [comment]
It looks like the problem was somehow connected to Xcode version. I tried cleaning up derived data and reinstalling pods several times, but on Xcode 8.3.2 build was always failing. Now I am using Xcode 8.3.3 (latest stable version at the moment) and it compiles just fine. 

I am closing this issue.

**Comment by jeffh** [comment]
Thanks for following up and closing the issue. 😀

- Jeff

**Comment by kaosdg** [comment]
Sorry to bump this but seeing this issue in XCode 9 again
