### ISSUE TITLE
Binary Builds report invalid Swift Versions. 

### ISSUE THREAD

**Issue by aaroncrespo** [Quick/Nimble#433]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Build Nimble with `carthage build --no-skip-current && carthage archive`

### What did you expect to happen?

- [X] Expect successful build
- [ ] ~Carthage can resolve the binary dependency~

### What actually happened instead?

Carthage emits an error when resolving the built binary in a project depending on Nimble
`"Incompatible Swift version - framework was built with 3.1 effective-3 and the local version is 3.1."`
And rebuilds from Source.

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.0*
 - Xcode Version: Version 8.3.3 (8E3004b)
 - Swift Version: Xcode Defaulft

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.23.0

**Comment by aaroncrespo** [comment]
Carthage/Carthage/issues/1979

**Comment by aaroncrespo** [comment]
removing 
```diff
-                               OTHER_SWIFT_FLAGS = "$(inherited) -swift-version 3";
```
And rebuilding the framework allows carthage to use the binary.

**Comment by aaroncrespo** [comment]
i think this will be fixed when 

https://github.com/Carthage/Carthage/pull/1984
https://github.com/Quick/Nimble/pull/437

make it to releases.

**Comment by jeffh** [comment]
Thanks for filing the issue. Yeah, it's a Carthage issue. I'll close this issue.
