### ISSUE TITLE
Type inference needs help under Xcode 9

### ISSUE THREAD

**Issue by aaroncrespo** [Quick/Nimble#439]
`to(contains` style matchers seem to need some type matching help when building under Xcode 9. This is with Nimble linked against test build as a Binary Framework.

I've had to manually help along the compiler by being explicit about types:
```diff
import Foundation
import XCTest
import Quick
import Nimble
@testable import MyFramework

//...
- expect(["string2", "string1"]).to(contain(MyFramework.funcReturnsString()))
+ expect(["string2", "string1"] as [String]).to(contain(MyFramework.funcReturnsString() as String))
```

Other similar Issues might exist but these are the prevailing issue in my test suite.

Nimble.framework was built straight from master with `$ carthage build`

**Comment by aaroncrespo** [comment]
Related? I get

`The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and disable Swift 3 @objc inference.` 

Emitted from my "check dependencies" step this project's only dependency are Quick and Nimble for tests and itself has only pure swift definitions not tied to NSObject or @objc

**Comment by aaroncrespo** [comment]
`+				SWIFT_SWIFT3_OBJC_INFERENCE = On;` is set

**Comment by ikesyo** [comment]
FYI this is also happening in Nimble test suites.

**Comment by ikesyo** [comment]
Seems that this is not an issue anymore in Xcode 9 beta 3: https://github.com/Quick/Nimble/pull/446#issuecomment-316564931

**Comment by Visakeswaran** [comment]
Check out this link, it clearly explains how to get rid of the error
https://youtu.be/T7TyB-R_rOk
