### ISSUE TITLE
Nimble compilation warnings

### ISSUE THREAD

**Issue by timojaask** [Quick/Nimble#444]
Whenever I use Nimble in my projects, Xcode issue navigator is flooded with Nimble build warnings. The project compiles, but having the build log full of warnings is a bad thing, especially since you might miss warnings that are actually related to your application.

### Steps to reproduce

1. Create a new Xcode project (single view application, Swift, universal, include unit tests)
2. Close Xcode, run `pod init`
3. Add `pod 'Quick'` and `pod 'Nimble'` to tests target in `Podfile`
4. Run `pod install`
5. Open .xcworkspace in Xcode
6. Build test target by selecting Product -> Test or pressing Cmd+U

### Build warnings reported by building the test target

```
Nimble/Matchers/Predicate.swift:170:22: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Expectation.swift:5:14: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Expectation.swift:23:14: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/SatisfyAnyOf.swift:67:55: 'NonNilMatcherFunc' is deprecated: Use to Predicate instead
Nimble/Matchers/SatisfyAnyOf.swift:71:49: 'MatcherFunc' is deprecated: Use to Predicate instead
Nimble/Expectation.swift:87:18: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Expectation.swift:94:18: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/ContainElementSatisfying.swift:41:21: Variable 'iterator' was never mutated; consider changing to 'let' constant
Nimble/Expectation.swift:103:18: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/Predicate.swift:199:85: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Adapters/NMBExpectation.swift:13:37: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/PostNotification.swift:45:14: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/SatisfyAnyOf.swift:6:14: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/SatisfyAnyOf.swift:12:14: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/SatisfyAnyOf.swift:13:16: 'NonNilMatcherFunc' is deprecated: Use to Predicate instead
Nimble/Matchers/AllPass.swift:22:27: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/AllPass.swift:76:21: Variable 'generator' was never mutated; consider changing to 'let' constant
Nimble/Matchers/AsyncMatcherWrapper.swift:40:44: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/AsyncMatcherWrapper.swift:41:14: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/AsyncMatcherWrapper.swift:173:18: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/AsyncMatcherWrapper.swift:197:18: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/AsyncMatcherWrapper.swift:223:18: 'Matcher' is deprecated: Use to Predicate instead
Nimble/Matchers/MatcherProtocols.swift:15:11: 'Matcher' is deprecated: Use to Predicate instead
```

### Environment

 - Quick: 1.1.0
 - Nimble: 7.0.1
 - Xcode Version: 8.3.3 (8E3004b)
 - Swift Version: 3.1

 - Cocoapods: 1.2.1

### Project that demonstrates the issue

An empty iOS project that includes Nimble in test target and produces the build warnings reported above: https://github.com/timojaask/NimbleWarnings

**Comment by timojaask** [comment]
A partial solution for those affected by the warnings is to disable warnings coming from all Cocoapods.

Add the following line to your `Podfile`:
```
inhibit_all_warnings!
```

**Comment by jeffh** [comment]
Hey @timojaask, thanks for filing an issue.

Currently the warnings are expected for Nimble as some of its public APIs are in mist of migrating starting with [v7 release](https://github.com/Quick/Nimble/releases/tag/v7.0.0). Once the migration is complete, then all these warnings/deprecations will be removed.

**Comment by gabrieloliva** [comment]
Does #445 fix all this issue?
