### ISSUE TITLE
Compiler warning in Errors.swift

### ISSUE THREAD

**Issue by ohadnav** [Quick/Nimble#451]
> Pods/Nimble/Sources/Nimble/Utils/Errors.swift:15:30: Conditional cast from 'T' to 'CustomDebugStringConvertible' always succeeds

**Comment by ikesyo** [comment]
I can't see it on that line: https://github.com/Quick/Nimble/blob/70279be/Sources/Nimble/Utils/Errors.swift#L15. Maybe you use an older version of Nimble.
