### ISSUE TITLE
UIColor matchers for different Colorspaces 

### ISSUE THREAD

**Issue by devandanger** [Quick/Nimble#454]
I've ran into a couple issues with UIColor's not matching correctly in the case they are in different colorspaces.  I put together a couple methods to implement this functionality correctly.  Would this be of interest for this project? Works fine outside of this pod, but figured it could be of use to the project.

**Comment by ikesyo** [comment]
We don't have any AppKit or UIKit specific matchers. So such matchers should be a dedicated library I think.
