### ISSUE TITLE
Xcode 9 beta 6 cannot compile Nimble

### ISSUE THREAD

**Issue by m1entus** [Quick/Nimble#459]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Installed Quick and Nimble using pods and Swift-4.0 - Xcode 9 beta 6

### What did you expect to happen?

Nimble includes DSL.h in umbrealla headers, and try to compile DSL.m which cannot be compiled because some of method is not found, i suppose it shouldn't be included in pods when building for Swift. In addition to that line PostNotification.swift:39 should be marked as public field because Xcode generate error, and BeCloseTo.swift:3 also should be marked as a public because is used in public method and Xcode generate warning.

### What actually happened instead?

Cannot compile project because of above errors.

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.1*
 - Xcode Version: *9.0 beta 6 (9M214v)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.0* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1* (Use `pod --version` in Terminal)

**Comment by ikesyo** [comment]
Hi, this is not an issue on `master` so please use `master` branch.

```
pod "Nimble", :git => "https://github.com/Quick/Nimble.git", :branch => "master"
```

**Comment by m1entus** [comment]
Could you then update Pods version poiting to a new master ?

**Comment by ikesyo** [comment]
FYI v7.0.2 has been released.
