### ISSUE TITLE
Comparing equatable structs

### ISSUE THREAD

**Issue by itsravenous** [Quick/Nimble#464]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Used `equal()` to try and compare two instances of an Enum

### What did you expect to happen?

The assertion to run

### What actually happened instead?

Got the following error
```shell
~/swift-i3s/Tests/I3sTests/Point2dSpec.swift:35:25: error: cannot invoke 'equal' with an argument list of type '(Point2d)'
          expect(p0).to(equal(p1))
                        ^
~/swift-i3s/Tests/I3sTests/Point2dSpec.swift:35:25: note: overloads for 'equal' exist with these partially matching parameter lists: (T?), ([T : C]?), ([T]?), ([T?]), (Set<T>?)
          expect(p0).to(equal(p1))
                        ^

```

I've made my Point2d struct equatable (see https://github.com/mwsrp/i3s-classic-swift/blob/master/Sources/I3s/Point2d.swift#L22-L24)

I [previously](https://github.com/mwsrp/i3s-classic-swift/commit/c5af20fd2d487b80527105729a92e202638c32b6) had `expect(p0 == p1).to(beTrue())` which worked fine, but doesn't feel quite right.

I've also tried the shorthand match:

`expect(p0) == p1`

but that threw:

`error: binary operator '==' cannot be applied to operands of type 'Expectation<Point2d>' and 'Point2d'`

This really feels like user error but I can't figure out why!

### Environment

List the software versions you're using:

 - OS: Ubuntu Linux 16.10
 - Quick: 1.1.0
 - Nimble: 7.0.0
 - Xcode Version: N/A
 - Swift Version: 3.1.1

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager 3.1.0

### Project that demonstrates the issue

https://github.com/mwsrp/i3s-classic-swift

and run `swift test`

**Comment by ikesyo** [comment]
Hi @itsravenous, you should need to add `Equatable` conformance on your types:

```swift
struct Point2d: Equatable {...}
// or
extension Point2d: Equatable {}
```

**Comment by itsravenous** [comment]
Thanks!!
