### ISSUE TITLE
Using the toEventually expectation produces a "found nil while unwrapping an optional value" error

### ISSUE THREAD

**Issue by raphaelcruzeiro** [Quick/Nimble#465]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Tried testing some async code with the `toEventually` expectation. I cannot always replicate this error. It just starts happening and the only thing that makes it go away temporarily is restarting my Mac.

### What did you expect to happen?

It should either fail or succeed but not crash.

### What actually happened instead?

Got a `fatal error: unexpectedly found nil while unwrapping an Optional value` on line 26 of `AyncMatcherWrapper.swift`:
`case .timedOut: return PredicateResult(status: .fail, message: lastPredicateResult!.message)`

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.1*
 - Xcode Version: *9.0 (9A235)*
 - Swift Version: *4.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1* (Use `pod --version` in Terminal)

**Comment by stephengazzard** [comment]
We are encountering the same issue. 

Quick: 1.1.0
Nimble: 7.0.1
Xcode Version: 9.0 (9A235)
Swift Version: 3.2
Cocoapods: 1.2.1

This is the code that's being tested:

```   
    func log(_ message: String, level: LogLevel) {
        DispatchQueue.main.async {
            self.delegate?.newLogReceived(message)
        }
    }
```

and the test:

```
                   it("the text field shows the log") {
                        expect(testContext.subject.logsTextView.text).toEventually(equal(expectedString))
                    }
```

**Comment by stephengazzard** [comment]
Pointed my podfile at master and the issue went away. I think this will be solved with #467

**Comment by ikesyo** [comment]
v7.0.2 has been released. Closing.

**Comment by jmejiaa** [comment]
Still having this issue on v7.0.2 - @stephengazzard did you change anything else that could havbe solved it?

**Comment by stephengazzard** [comment]
@jmejiaa Sorry - when I upgraded it just started working for me. If you're still encountering it on 7.0.2 probably better to raise as a new issue with repro steps

**Comment by paulthorsteinson** [comment]
This did not go away when I updated to 7.0.2 but did go away when I also updated quick to 1.2.0

**Comment by freak4pc** [comment]
Quick 1.2.0 and Nimble 7.0.2 still have this issue.
