### ISSUE TITLE
Nimble compilation fails only in Travis

### ISSUE THREAD

**Issue by adamyanalunas** [Quick/Nimble#466]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Use Travis to run tests during a build.

### What did you expect to happen?

Tests pass.

### What actually happened instead?

Tests fail because compilation of `NimbleXCTestHandler` failed.

### Environment

List the software versions you're using:

 - Quick: 1.1.0 (dafc587e21eed9f4cab3249b9f9015b0b7a7f71d)
 - Nimble: 7.0.01 (657d000e11df8aebe27cdaf9d244de7f30ed87f7)
 - Xcode Version: [9.0 (9A235)](https://travis-ci.org/adamyanalunas/Font/builds/278416676#L202)
 - Swift Version: 4.0

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.1

### Project that demonstrates the issue

I have a [PR for my project](https://github.com/adamyanalunas/Font/pull/8) that shows the [failing Travis build](https://travis-ci.org/adamyanalunas/Font/builds/278416676).

### Further detail

The command to run tests is `set -o pipefail && xcodebuild clean test -workspace Example/Font.xcworkspace -scheme Font-Example -sdk iphonesimulator -destination platform="iOS Simulator,OS=latest,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty -c` which passes locally. 

It appears that the macOS, Xcode, CocoaPods, Quick, and Nimble versions are all the same both locally and on Travis. The projects are configured to set Swift 3 `@obj` inference as “default”.

The errors experienced are:

* [BeCloseTo.swift:21:71](https://travis-ci.org/adamyanalunas/Font/builds/278416676#L707) let 'DefaultDelta' is internal and cannot be referenced from a default argument value
* [BeCloseTo.swift:31:85](https://travis-ci.org/adamyanalunas/Font/builds/278416676#L714) let 'DefaultDelta' is internal and cannot be referenced from a default argument value
* [BeCloseTo.swift:78:74](https://travis-ci.org/adamyanalunas/Font/builds/278416676#L721) let 'DefaultDelta' is internal and cannot be referenced from a default argument value
* [NimbleXCTestHandler.swift:69:98](https://travis-ci.org/adamyanalunas/Font/builds/278416676#L761) cannot convert value of type 'UInt' to expected argument type 'Int'

I doubt this is specifically a Nimble issue but hopefully someone can point me in the right direction. If so, I'm happy to open a Nimble PR as needed.

**Comment by ChrisChares** [comment]
Seeing these exact same errors building locally with 9.0 `9A235` (from the App Store)

```
PODS:
  - Nimble (7.0.1)
  - Quick (1.1.0)

DEPENDENCIES:
  - Nimble
  - Quick

SPEC CHECKSUMS:
  Nimble: 657d000e11df8aebe27cdaf9d244de7f30ed87f7
  Quick: dafc587e21eed9f4cab3249b9f9015b0b7a7f71d
```

**Comment by ChrisChares** [comment]
You can remove this error by using bleeding edge Quick/Nimble instead of the latest tagged version.  Specifically I think [#735](https://github.com/Quick/Quick/pull/735) may have fixed it

```
pod 'Quick', :git => 'https://github.com/Quick/Quick'
pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
```

**Comment by adamyanalunas** [comment]
@ChrisChares Thanks for the pointer towards edge. That solved my Travis build issues. I'll keep my eyes out for the next release. In the mean time I'll consider this issue resolved.

**Comment by ikesyo** [comment]
FYI v7.0.2 has been released.

**Comment by fahadHyder** [comment]
@ChrisChares thank you.
I had same set of errors, currently i am using bleeding edge, Its fixed my issue.
@ikesyo integrated Quick and Nimble 2 days back, the issue still exist in the latest version in swift4.
Any advice?
