### ISSUE TITLE
Release 7.0.2

### ISSUE THREAD

**Issue by ikesyo** [Quick/Nimble#467]
@Quick/core A new release which fully supports Xcode 9 should be published. See also #432 for the previous release.

And also it would be great if I could get a CocoaPods trunk access. 🙏

**Comment by edopelawi** [comment]
Folks, apologies for joining this issue, but when will the 7.0.2 be released? My library uses Nimble (and Quick) for testing, and currently using the master branch... which cannot be used in travis-ci.com due to cloning issues :( 

Thanks in advance!

**Comment by ashfurrow** [comment]
Hey @ikesyo I meant to response earlier to this, apologies. I've added you as an owner to the library in CocoaPods trunk. Would you like to do the honours and push 7.0.2?

**Comment by ikesyo** [comment]
Thanks @ashfurrow! I've just published v7.0.2 🚢 

https://github.com/Quick/Nimble/releases/tag/v7.0.2
