### ISSUE TITLE
Cannot use mutating member on immutable value: 'generator' is a 'let' constant

### ISSUE THREAD

**Issue by mludowise** [Quick/Nimble#470]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

1. Ran `pod lib create` with testing options `Quick` and view based testing:
```
$ pod lib create TestPod
Cloning `https://github.com/CocoaPods/pod-template.git` into `TestPod`.
Configuring TestPod template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > swift

Would you like to include a demo application with your library? [ Yes / No ]
 > yes

Which testing frameworks will you use? [ Quick / None ]
 > quick

Would you like to do view based testing? [ Yes / No ]
 > yes

Running pod install on your new library.

Analyzing dependencies
Fetching podspec for `TestPod` from `../`
Downloading dependencies
Installing FBSnapshotTestCase (2.1.4)
Installing Nimble (5.1.1)
Installing Nimble-Snapshots (4.4.0)
Installing Quick (1.0.0)
Installing TestPod (0.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `TestPod.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.

[!] Automatically assigning platform ios with version 8.3 on target TestPod_Example because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'TestPod/Example/TestPod.xcworkspace'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```
2. Ran `pod install` on example project.
```
cd TestPod/Example
pod install
```
3. In XCode, ran a clean and then build on the example target `TestPod-Example`

### What did you expect to happen?

Project should build.

### What actually happened instead?

Received the following error:
`/Users/mel/GitHub/TestPod/Example/Pods/Nimble/Sources/Nimble/Matchers/AllPass.swift:69:33: Cannot use mutating member on immutable value: 'generator' is a 'let' constant`

### Environment

List the software versions you're using:

 - Quick: *1.0.0*
 - Nimble: *5.1.1*
 - Xcode Version: *Version 9.0 (9A235)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.0* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

https://github.com/mludowise/TestPod

**Comment by ikesyo** [comment]
Hi @mludowise, this is already addressed in the latest version v7.0.2, so please update your installation. Closing.
