### ISSUE TITLE
Compiling fails in Xcode 9 / Swift 4 / Nimble 7.0.2

### ISSUE THREAD

**Issue by Blackjacx** [Quick/Nimble#471]
### What did you do?

Compile Nimble in Xcode 9 9A235

### What did you expect to happen?

It Compiles

### What actually happened instead?

It gives me the compilation error:

```
CwlPreconditionTesting/CwlPreconditionTesting/CwlCatchBadInstruction.swift:82:11: Overlapping accesses to 'self', but modification requires exclusive access; consider copying to a local variable
```

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.2*
 - Xcode Version: *9.0 (9A235)*
 - Swift Version: *4.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1*

### Project that demonstrates the issue

https://github.com/Blackjacx/SHSearchBar

**Comment by ikesyo** [comment]
CI builds are passing and I can't reproduce it locally. Could you try a clean build or removing `~/Library/Developer/Xcode/DerivedData`?

**Comment by Blackjacx** [comment]
I've already cleaned everything. The CI builds of 4 of my projects are not passing and show the same errors:

![screen shot 2017-09-28 at 17 57 12](https://user-images.githubusercontent.com/794372/30977036-a6ffaed8-a476-11e7-8680-791e4b90ccf0.png)

The error message `overlapping accesses to 'self', but modification requires exclusive access; consider copying to a local variable` is a Swift 4 warning that is enabled in Xcode 9 by default. I think you should fix this.

**Comment by Blackjacx** [comment]
I found out that this happens when I build my framework target with the Thread Sanitizer enabled. When I switch it off I can build without errors locally. My CI machine still delivers me that error. Maybe it uses this thread sanitizer despite I disabled it in my scheme settings...

**Comment by Blackjacx** [comment]
OK fixed this issue for me by disabling thread sanitizer... But it is still an issue for people with thread sanitizer enabled.

You can 
1. clone the project https://github.com/Blackjacx/SHSearchBar
2. enable thread sanitizer for run and test phase
3. build SHSearchBar scheme

to reproduce the failure.

**Comment by ikesyo** [comment]
Thanks for the investigation @Blackjacx! That's really helpful.

**Comment by Blackjacx** [comment]
I like the project and use it a lot :-)

**Comment by saragiotto** [comment]
pod deintegrate
pod install

Work for me just now.
