### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set 

### ISSUE THREAD

**Issue by sergd2005** [Quick/Nimble#473]
- [x ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Used Nimble (7.0.2) via CocoaPods for UnitTests target

### What did you expect to happen?

Project to compile

### What actually happened instead?

Failing to compile with error

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

### Environment

List the software versions you're using:
 - Quick: not using
 - Nimble: *7.0.2*
 - Xcode Version: *9.0 (9A235)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.0* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1* (Use `pod --version` in Terminal)

**Comment by morganchen12** [comment]
Have you tried setting this variable to the version of Swift you're using? In the Xcode Build Settings inspector it shows up as "Use Legacy Swift Version". If it's unset but Xcode still displays a value, setting it to a different value and then back again should set it properly.

**Comment by sergd2005** [comment]
Ok so this issue happens when host project is not using swift.  I can attach sample project here if you need it. But it is really easy to reproduce - just create project that uses objc as default language and try to install Nimble via CocoaPods. I use them for unit tests target.

**Comment by morganchen12** [comment]
Under Pods.xcodeproj there should be a target for Nimble--if you set this variable in that target's build settings, does the error go away?

It seems to be already set in the Nimble project (see [here](https://github.com/Quick/Nimble/blob/a5438fa5d6cfac67dc88c90423ea6c3b75995555/Nimble.xcodeproj/project.pbxproj#L1855) and [here](https://github.com/Quick/Nimble/blob/a5438fa5d6cfac67dc88c90423ea6c3b75995555/Nimble.xcodeproj/project.pbxproj#L1800)). Maybe we're missing it somewhere else, or this is a CocoaPods-related issue (don't file an issue there yet though).

If you run `pod --version` and `xcodeproj --version`, what are the outputs?

**Comment by sergd2005** [comment]
Yes error goes away if I set it manually. However it is not solution to this problem since Pods project will be regenerated on next pod install/update operation. 

I provided requested outputs initially. 

Environment

List the software versions you're using:

Quick: not using
Nimble: 7.0.2
Xcode Version: 9.0 (9A235) (Open Xcode; In menubar: Xcode > About Xcode)
Swift Version: 4.0 (Open Xcode Preferences; Components > Toolchains. If none, use Xcode Default.)
Please also mention which package manager you used and its version. Delete the
other package managers in this list:

Cocoapods: 1.3.1 (Use pod --version in Terminal)

**Comment by morganchen12** [comment]
`xcodeproj --version` is the version of the Xcodeproj Ruby gem that CocoaPods depends on, not your Xcode version. The reason I ask this is I'm wondering if there was a recent change in the Xcodeproj gem that would cause this issue--if manually downgrading the Xcodeproj gem version to a lower number makes the issue go away, then it's definitely something from CocoaPods.

**Comment by sergd2005** [comment]
oh sorry xcodeproj version is 1.5.2

**Comment by sergd2005** [comment]
I came to conclusion that problem should be fixed on CocoaPods side  and I found related topic https://github.com/CocoaPods/CocoaPods/issues/6791.

For now I think I ll fix post hooks as mentioned in post above. 

this works:

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == '<insert target name of your pod here>'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
It's not pretty but will do until they update your pods to Swift 4.

**Comment by morganchen12** [comment]
Thanks for following up. I was also able to fix this locally by downgrading Xcodeproj to v1.5.1. If you're working with a team of devs, you can ensure your CocoaPods and XcodeProj versions are all the same by including a Gemfile in your project repo.
