### ISSUE TITLE
Add @sharplet to CocoaPods trunk

### ISSUE THREAD

**Issue by phatblat** [Quick/Nimble#479]
Finally following up on #432.

Sorry for the delay. @sharplet you have been added as an owner on both the Quick and Nimble pods on CocoaPods trunk using your @me.com email. Let me know if you have any issues. Please close this issue after you've verified ownership with `pod trunk info`.

**Comment by sharplet** [comment]
@phatblat Thanks! ✨

I don't use that email anymore, but I went ahead and added my current email address as an owner.
