### ISSUE TITLE
Nimble Compilation Error with Swift 4 and Xcode 9

### ISSUE THREAD

**Issue by chenzww** [Quick/Nimble#485]
I try add Nimble to project use SPM without Quick since Quick add to project failed. 
```Swift
// Package.swift
// **only this file edited**
let package = Package(
    name: "PROJECT_NAME",
    dependencies: [
        .package(url: "https://github.com/Quick/Nimble.git", from: "7.0.2"),
    ],
    targets: [
        .target(
            name: "PROJECT_NAME",
            dependencies: [
                "Nimble",
            ]),
    ]
)
```
  Then, perform  'swift package update && swift package generate-xcodeproj' in terminal.
Final, click 'build and then run the current scheme' button in Xcode. Build succeed, and 'Nimble.framework' and be found in project.

  However, error caused when running.
```
// thread 1 message
dyld`__abort_with_payload:
    0x10003d20c <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x10003d211 <+5>:  movq   %rcx, %r10
    0x10003d214 <+8>:  syscall 
->  0x10003d216 <+10>: jae    0x10003d220               ; <+20>  <= **Thread 1: signal SIGABRT**
    0x10003d218 <+12>: movq   %rax, %rdi
    0x10003d21b <+15>: jmp    0x10003ca74               ; cerror_nocancel
    0x10003d220 <+20>: retq   
    0x10003d221 <+21>: nop    
    0x10003d222 <+22>: nop    
    0x10003d223 <+23>: nop    

```

```
// lldb console message
dyld: Library not loaded: @rpath/XCTest.framework/Versions/A/XCTest
  Referenced from: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftXCTest.dylib
  Reason: image not found
(lldb) 
```

### Environment

List the software versions you're using:

 - Quick: None
 - Nimble:  Nimble v7.0.2
 - Xcode Version: Xcode 9.1(9B55)
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: None
 - Carthage: None
 - Swift Package Manager: Apple Swift Package Manager - Swift 4.0.0-dev (swiftpm-13502)

**Comment by ikesyo** [comment]
This may be the same as https://github.com/Quick/Quick/issues/751 and unfortunately that is an issue of SwiftPM side.

**Comment by ikesyo** [comment]
> `‘.target`

Additionally you should use `.testTarget` for Nimble since this is a testing dependency which depends on XCTest framework.
