### ISSUE TITLE
Can you give me the compiled Quick and Nimble Frameworks

### ISSUE THREAD

**Issue by chenzww** [Quick/Nimble#486]
### What did you do?
I tried to manual compile Quick and Nimble frameworks. However, it caused test target not work. Can you give me work well Quick and Nimble frameworks which based macOS and Swift 4.0.2?

### Environment
Xcode Version: 9.1(9B55)
Swift Version: Apple Swift version 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)

**Comment by wongzigii** [comment]
> it caused test target not work. 
What is your trouble?
FYI @chenzww You can use [Carthage](https://github.com/Carthage/Carthage) to build frameworks base on Swift 4.0.2
