### ISSUE TITLE
Testing Textfield is active with Quick and Nimble

### ISSUE THREAD

**Issue by AdamMak** [Quick/Nimble#487]
List the software versions you're using:

 - Quick: 1.2.0
 - Nimble: 7.0.2
 - Xcode Version: 9.1
 - Swift Version: 4.0
 - Cocoapods: 1.3.1

I am trying to write a test that will determine whether a textfield has become active or not but it seems when I write the expect statement to check if a textfield is first responder, it alway returns false.

I have started a new project, just placed one text field in the middle of the screen and on viewDidLoad made the text field first responder

```
 @IBOutlet var testField : UITextField!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        testField.becomeFirstResponder()
    }
```

In my spec test, I have written this

```
  override func spec() {
      var viewController : ViewController!
        
        beforeEach {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
  
            viewController = storyboard.instantiateViewController(withIdentifier: "viewController") as! ViewController
            _ = viewController.view
        }
       
        describe("On load, text field becomes active", {
            
            it("TestField should be first responder"){
                
                expect(viewController.testField.isFirstResponder).toEventually(beTrue())
            }
        })
    }
```

However, every time, the expect test fails, as the isFirstResponder is always false. This code works fine in my view controller, I can call isFirstResponder and it returns true, however in the QuickSpec test it always returns false. Can anyone help me understand why this particular test is failing?

Thanks in advance

**Comment by jeffh** [comment]
If I recall correctly, responder chains require being attached to UIWindows.

- Jeff

**Comment by jwfriese** [comment]
@jeffh - You're 100% correct. 

@AdamMak - In order for this test to work in the way you're expecting, you'll have to host the text field in a view that itself is within a window. We had to do something like this to test the UITextView and UITextField functionality of [Fleet](https://github.com/jwfriese/Fleet). 

Here's the test that sets up the UITextField correctly: https://github.com/jwfriese/Fleet/blob/2f2ffd64d4b176d702ce8e756e0c69aeff5b448d/FleetTests/CoreExtensions/Controls/TextInput/UITextField%2BFleetSpec.swift#L19

And here's the helper method that is used within the setup of that test: https://github.com/jwfriese/Fleet/blob/2f2ffd64d4b176d702ce8e756e0c69aeff5b448d/FleetTests/Helpers/EmbedView.swift#L21

**Comment by ikesyo** [comment]
Looks like this has the correct answer. Closing.
