### ISSUE TITLE
`waitUntil` blocks do not start working immediately

### ISSUE THREAD

**Issue by mrh-is** [Quick/Nimble#501]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Wrote a nice async test with `waitUntil`, like this:

```swift
it("does the thing") {
    waitUntil { done in
        zhuLi.doTheThing { success in
            expect(success).to(beTrue()) // Zhu Li never fails
            done()
        }
    }
}
```

### What did you expect to happen?

Block is called, async method is executed (delayed response would be my own problem).

### What actually happened instead?

Async method (e.g., `zhuLi.doTheThing`) is not called immediately. In my one test case, it is called ~3 seconds later, which means `waitUntil` will always fail (with the default timeout of 1s).

### Environment

List the software versions you're using:

 - Quick: *1.2.0*
 - Nimble: *7.0.3*
 - Xcode Version: *9.2 (9C40b)*
 - Swift Version: *Xcode Default*
 - Cocoapods: *1.3.1* (Use `pod --version` in Terminal)

**Comment by nhnam** [comment]
Please try with 
```
it("does the thing") {
   waitUntil(timeout:3.0, action:{ done in
        zhuLi.doTheThing { success in
            expect(success).to(beTrue()) // Zhu Li never fails
            done()
        }
    }
}
```
// 3.0: time out in seconds

**Comment by mrh-is** [comment]
Yeah, that's a workaround! But doing that only papers over the problem. (Not to mention it tries on the delay never going above 3s, which I can't guarantee.) Better to solve the underlying bug if I can. 🤔

**Comment by wongzigii** [comment]
@mrh-is  You can wrap your own waitUntil function likes:

    private let timeOutInSecond = 5
    private func myWaitUntil(action: @escaping (@escaping () -> Void) -> Void) {
        waitUntil(timeout: timeOutInSecond) { done in
            done()
        }
    }

then call it like:

    myWaitUntil { done in 
        // ...
        // done()
    }

Feel free to reopen it if you have any further question.

**Comment by mrh-is** [comment]
Again, great workarounds, but not actually a solution to what seems to be an underlying issue.

I'll reopen if I find any better debug data.
