### ISSUE TITLE
`expect` fails to build when comparing 2 Objective-C NS_ENUM values.

### ISSUE THREAD

**Issue by manuyavuz** [Quick/Nimble#510]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Use `expect` to check equality of two Objective-C NS_ENUM values with NSUInteger type.

### What did you expect to happen?

Successfully build and check equality during testing.

### What actually happened instead?

With a very simple scenario such as the following:

```objc
#import <XCTest/XCTest.h>

typedef NS_ENUM(NSUInteger, EnumType) {
    EnumTypeA,
    EnumTypeB,
    EnumTypeC,
};

@import Nimble;
@implementation NimbleNSEnumTests

- (void)testExample {
    expect(EnumTypeC).to(equal(EnumTypeB));
}
```

The line with `expect` fails to build with `Call to 'NMB_expect' is ambiguous` error. Compiler finds the following methods in `DSL.h` as candidates:

```swift
DEFINE_NMB_EXPECT_OVERLOAD(long, @(actualBlock()))
DEFINE_NMB_EXPECT_OVERLOAD(unsigned long, @(actualBlock()))
DEFINE_NMB_EXPECT_OVERLOAD(long long, @(actualBlock()))
DEFINE_NMB_EXPECT_OVERLOAD(unsigned long long, @(actualBlock()))
```

`NS_ENUM` has type of `NSUInteger` in above case.

### Environment

List the software versions you're using:

 - Nimble: *7.0.3*
 - Xcode Version: *9.2 (9C40b)*
 - Swift Version: *Xcode Default*

 - Cocoapods: *1.4.0*

### Project that demonstrates the issue

https://github.com/manuyavuz/nimble-nsenum-bug

**Comment by ikesyo** [comment]
The enum is not the same as its underlying type (`NSUInteger`)  so Nimble could not have an overload for your enum type (`EnumType` in this case) by default. So wrapping the given values into `NSNumber` would address the issue:

```swift
expect(@(EnumTypeC)).to(equal(EnumTypeB));
```
