### ISSUE TITLE
[Proposal] Drop Xcode 8.3/Swift 3.x support with fully migrating to Xcode 9.3/Swift 4.1

### ISSUE THREAD

**Issue by ikesyo** [Quick/Nimble#514]
And let's release that change as Nimble 8.0 (with [the Deprecation Roadmap](https://github.com/Quick/Nimble#deprecation-roadmap)).

How do you think? @Quick/core

**Comment by ikesyo** [comment]
FYI Conditional Conformance is huge win for us 🎉 

https://swift.org/blog/conditional-conformance/

**Comment by phatblat** [comment]
Sounds good to me.

**Comment by phatblat** [comment]
Closing now that #515 is merged.
