### ISSUE TITLE
Add allPass matcher

### ISSUE THREAD

**Issue by modocache** [Quick/Nimble#52]
In [Jasmine](https://github.com/pivotal/jasmine), you can assert that all elements in a collection pass a specified condition:

```js
expect([1, 2, 3]).toAllPass(function (value) {
  return value > 0;
});
```

Of course, you could write an equivalent assertion using Nimble's `beTrue()`, but `toAllPass` probably has more descriptive failure messages (i.e.: which element caused the assertion to fail).

Thoughts? :raised_hands:

**Comment by rbeeger** [comment]
This was implemented in https://github.com/Quick/Nimble/pull/95 and can be closed.
