### ISSUE TITLE
Expecting an assertion, eventually

### ISSUE THREAD

**Issue by nevillco** [Quick/Nimble#520]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Wrote the following test suite:

```
func assertNotThree(_ value: Int) {
    assert(value != 3)
}

func asyncAssertNotThree(_ value: Int) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
        assertNotThree(3)
    }
}

class NimbleExperimentTests: XCTestCase {

    func testAssertion() {
        let expression = { assertNotThree(3) }
        expect(expression: expression).to(throwAssertion())
    }

    func testAssertionAsync() {
        let expression = { asyncAssertNotThree(3) }
        expect(expression: expression).toEventually(throwAssertion())
    }
    
}
```

### What did you expect to happen?

I would expect both tests to pass.

### What actually happened instead?

The assertion inside `func testAssertionAsync()` does not get caught; I get the console message:

> Assertion failed: file /Users/connorneville/Documents/Projects/NimbleExperiment/NimbleExperimentTests/NimbleExperimentTests.swift, line 14

Then, after a short delay, the test suite seems to reboot itself, and I get this console message:

> Restarting after unexpected exit or crash in NimbleExperimentTests/testAssertionAsync(); summary will include totals from previous launches.

After this, the tests complete, and `func testAssertionAsync()` fails, having not caught the assertion.

### Environment

 - Quick: *1.2.0*
 - Nimble: *7.0.3*
 - Xcode Version: *9.2 (9C40b)*
 - Swift Version: *4.0*
 - Cocoapods: *1.5.0*

**Comment by kaganriedel** [comment]
I am not seeing this issue on Xcode 9.2 / Swift 4.0, but after upgrading to Xcode 9.4 / Swift 4.1 I am experiencing the same issue described by @nevillco. Any updates on this?

**Comment by ikesyo** [comment]
`throwAssertion()` matcher expects that the given expression will throw assertion. But in the case of `let expression = { asyncAssertNotThree(3) }`, the expression which actually throws is not the closure nor `asyncAssertNotThree` function but the closure passed to `DispatchQueue.asyncAfter` API. Throwing an assertion is happening outside `expect(...)` body (context). So it seems to me that it is correct behavior.

**Comment by ikesyo** [comment]
@kaganriedel That is #478 and it's fortunate that it will be resolved in a next patch version (#545).

**Comment by kaganriedel** [comment]
Wonderful! Thank you. 👍

**Comment by ikesyo** [comment]
Closing.
