### ISSUE TITLE
Notifications from non-main queue are often go missing

### ISSUE THREAD

**Issue by ianbytchek** [Quick/Nimble#528]
I have a code that posts notification on non-main queue. In absolute majority cases Nimble doesn't catch these events. However, if I post them on the main queue everything works as expected. See below. Using the most recent versions.

![2018-05-31 01 24 56](https://user-images.githubusercontent.com/1086845/40748532-d0eff7c8-6471-11e8-9023-bdd3f1fe4296.gif)

**Comment by wongzigii** [comment]
AFAIK, [expression only evaluates on main queue](https://github.com/Quick/Nimble/blob/master/Sources/Nimble/Matchers/PostNotification.swift#L56).

**Comment by ikesyo** [comment]
Looks like this is expected behavior as @wongzigii said above.
