### ISSUE TITLE
Using satisfyAllOf with toEventually causes expression to be evaluated multiple times

### ISSUE THREAD

**Issue by iby** [Quick/Nimble#529]
Doing something like below results in expression being evaluated multiple times with `"foo"` being printed many times. With `satisfyAllOf` removed everything works as expected.

```swift
let testNotification = Notification(name: .init("Foo"), object: nil)
expect(expression: {
    print("foo")
    return DispatchQueue.global().async {
        Thread.sleep(forTimeInterval: 0.5)
        NotificationCenter.default.post(testNotification)
    }
}).toEventually(satisfyAllOf(postNotifications(equal([testNotification]))))
```

This must be happening because `postNotifications` has explicit logic for evaluating expression only once, while `satisfyAllOf` doesn't.

**Comment by ikesyo** [comment]
Async matchers (`toEventually` in this case) uses uncached expression evaluation to get a fresh result each time. And then, `satisfyAllOf` will 

- pass the given expression to the given matchers
- evaluate the given expression by itself to get an assertion message

So this is an edge case and I'm not sure if this is an expected behavior or a bug.

**Comment by ikesyo** [comment]
More correctly, the use of closure expression with `toEventually` is not an expected usage.

**Comment by ikesyo** [comment]
Maybe having a caching expression within `satisfyAllOf` matcher will mitigate the situation.

**Comment by ianbytchek** [comment]
If my memory is not letting me down this happened while attempting to create custom ReactiveSwift assertions using the same approach used by `postNotifications` with some help from `satisfyAllOf` to avoid boilerplate. So, this was the simplified case. It seemed like a legit use case, hence the issue. Can I provide any details that would be of use?

**Comment by ikesyo** [comment]
This is similar to #360.

**Comment by younata** [comment]
Bumping this to the next (major?) release in favor of getting async/await support out the door sooner.
