### ISSUE TITLE
Infinite loop crash bug using Xcode 10.

### ISSUE THREAD

**Issue by hmlongco** [Quick/Nimble#533]
### What did you do?

Ran test using Nimble using Xcode 10 beta.

### What did you expect to happen?

Test to succeed.

### What actually happened instead?

Nimble code went into infinite loop on stringify<T>(_ value: T?) -> String 

```
public func stringify<T>(_ value: T?) -> String {
    guard let unboxed = value else {
        return "nil"
    }

}
```

The following change fixes the problem.

```
public func stringify<T>(_ value: T?) -> String {
    guard let unboxed = value else {
        return "nil"
    }

    if let value = value as? TestOutputStringConvertible {
        return value.testDescription
    }

    if let value = value as? CustomDebugStringConvertible {
        return value.debugDescription
    }

    return String(describing: unboxed)
}
```

Apparently something changed in how generic optionals are mapped to functions.

### Environment

List the software versions you're using:

 - Quick: 1.3.0
 - Nimble: 7.1.1
 - Xcode Version: 10.0 beta
 - Swift Version: 4.1
 - Cocoapods: 1.5.0

**Comment by morganchen12** [comment]
This was fixed by #532, but hasn't been released.

**Comment by hmlongco** [comment]
Missed it. Any idea when it will be merged?

**Comment by morganchen12** [comment]
It'll be out in the 7.x release (see #536). I don't have an ETA for that, though.

**Comment by ikesyo** [comment]
v7.1.2 has been released 🚀 

https://github.com/Quick/Nimble/releases/tag/v7.1.2
