### ISSUE TITLE
Xcode 10 - Testing failed EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by eelbeze** [Quick/Nimble#535]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I try to run my test with Xcode 10.0 in beta

### What actually happened instead?

I have a failure in the Stringers.swift file's in ligne 162 in `return stringify(unboxed)` in this function:
`public func stringify<T>(_ value: T?) -> String {
    if let unboxed = value {
        return stringify(unboxed)
    }
    return "nil"
}`

I'm using Nimble for this method: `toEventually(_ predicate: Predicate<T>, timeout: TimeInterval = AsyncDefaults.Timeout, pollInterval: TimeInterval = AsyncDefaults.PollInterval, description: String? = nil) `
Here the failure: **Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffee4675fc8)**

### Environment

List the software versions you're using:

 - Quick: *1.3.0*
 - Nimble:  *7.1.1*
 - Xcode Version: *10.0 beta* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.1* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

 - Cocoapods: *1.5.2* (Use `pod --version` in Terminal)
 - Swift Package Manager *4.1.0 (swiftpm-14050)* (Use `swift build --version` in Terminal)

**Comment by eelbeze** [comment]
Oh it's seems this issue is a regression in Swift 4.2 and already reported: https://bugs.swift.org/browse/SR-7884 
Thanks !

**Comment by morganchen12** [comment]
This is also fixed in #532, which will likely be out before the Swift patch (and removes some redundant code anyway).

**Comment by ikesyo** [comment]
v7.1.2 has been released 🚀 

https://github.com/Quick/Nimble/releases/tag/v7.1.2

**Comment by ikesyo** [comment]
> https://bugs.swift.org/browse/SR-7884

Thanks for the info @eelbeze!
