### ISSUE TITLE
Crash when timeOut

### ISSUE THREAD

**Issue by IgnSergey** [Quick/Nimble#542]
During testing I got a crash. PrintScreen here.
reason for crash is that lastPredicateResult == nil in lastPredicateResult!.message
reproduced 2 times.
<img width="1426" alt="screen shot 2018-06-15 at 17 24 32" src="https://user-images.githubusercontent.com/40299304/41473262-6aa1e5ce-70c1-11e8-9aad-d21aa52bf972.png">

**Comment by wongzigii** [comment]
This issue is related to #508

**Comment by ikesyo** [comment]
Thanks @wongzigii, this should be addressed by #508. Closing.
