### ISSUE TITLE
Use of undeclared identifier 'NMBWait'

### ISSUE THREAD

**Issue by kleiberjp** [Quick/Nimble#551]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
before updated pod, with new nimble version, trying run tests on my project, and the build launch this error `Use of undeclared identifier 'NMBWait'`

### Environment

List the software versions you're using:
 - Nimble: *7.1.2*
 - Xcode Version: *9.4.1*
 - Swift Version: *4.2* 
 - Cocoapods: *1.5.3* 

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by ikesyo** [comment]
Please fill the template:

> Project that demonstrates the issue

or provide steps to reproduce the issue.

**Comment by ikesyo** [comment]
> - Xcode Version: 9.4.1
> - Swift Version: 4.2

Xcode 9.4.1 ships with Swift 4.1.2, so this is odd.

**Comment by ikesyo** [comment]
Closing this for now.

**Comment by kleiberjp** [comment]
i just install the last version, run test and xcode launch that error.
