### ISSUE TITLE
Various compiler errors using Xcode 9.3 and Swift 4.1

### ISSUE THREAD

**Issue by SenorWesley** [Quick/Nimble#555]
### What did you do?
I installed Quick and Nimble into my test target through Cocoapods, like done before countless times.

### What did you expect to happen?

I expected my app to compile, so I could write some tests.

### What actually happened instead?

I got 7 compiler errors when building the app. (see screenshot)
<img width="272" alt="schermafbeelding 2018-06-29 om 10 19 06" src="https://user-images.githubusercontent.com/15349051/42081668-50aaf064-7b86-11e8-9906-3f52acd3b60a.png">

### Environment

 - Quick: 1.3.0
 - Nimble: 6.0.1
 - Xcode Version:  9.3
 - Swift Version: 4.1
 - Cocoapods: 1.5.3

**Comment by SenorWesley** [comment]
Small update: I just updated to bleeding edge, which reduces the compiler errors to the following:

<img width="277" alt="schermafbeelding 2018-06-29 om 10 27 48" src="https://user-images.githubusercontent.com/15349051/42081998-2c671ca4-7b87-11e8-9627-c93b31e87758.png">

**Comment by ikesyo** [comment]
> Nimble: Latest version

Could you please note the exact version?

**Comment by SenorWesley** [comment]
@ikesyo I updated the issue. :-)

**Comment by ikesyo** [comment]
The latest version is v7.1.2 Please update to it.

**Comment by SenorWesley** [comment]
@ikesyo 

[CocoaPods could not find compatible versions for pod "Nimble":
  In Podfile:
    Nimble (~> 7.1.2)](url)

**Comment by ikesyo** [comment]
Then you should run `pod repo update` first.
