### ISSUE TITLE
Cocoapods version of the podspec file IS NOT up to date with the current version on GitHub

### ISSUE THREAD

**Issue by soberman** [Quick/Nimble#561]
I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Updated podfiles and tried to run to the project under the Xcode 10

### What did you expect to happen?

`Nimble.podspec` file to include `s.swift_version = '4.0'`

### What actually happened instead?

`Nimble.podspec` file *doesn't* include `s.swift_version = '4.0'`.
A s a result default Swift version 4.2 is being used and I get the compiler error: 'defaultRunLoopMode' has been renamed to 'RunLoop.Mode.default'.

### Environment

List the software versions you're using:

 - Quick: *1.2.0*
 - Nimble: *7.1.2*
 - Xcode Version: *10.0 beta 2 (10L177m)*
 - Swift Version: *4.2*
 - Cocoapods: *1.5.3*

**Comment by ikesyo** [comment]
That is alreasy addrssed in #549 and #554. You can use `7.x-branch` for now and we will have a new 7.x release in a few days.

**Comment by fabb** [comment]
But this issue does not need a new release, it just needs pushing the correct podspec to the Cocoapods spec repo.

**Comment by fabb** [comment]
Ok, good point. I‘ll just override the swift version build setting in my Podfile post_install until the changes you mentioned get released.

**Comment by ikesyo** [comment]
v7.1.3 has been released.
