### ISSUE TITLE
Versions 7.1.2 and above are missing commits fixing #530.

### ISSUE THREAD

**Issue by ashfurrow** [Quick/Nimble#575]
#531 was merged into master, fixing #530 as denoted in the [7.1.2 release notes](https://github.com/Quick/Nimble/releases/tag/v7.1.2), but the commit itself is missing from that tag's history. In fact, `Expectation.swift` reads on master as: 

https://github.com/Quick/Nimble/blob/471f58ee2568ca2660cf9b63fc9d39860bf6c3f2/Sources/Nimble/Expectation.swift#L74-L80

But [on the actual release tag](https://github.com/Quick/Nimble/blob/v7.1.2/Sources/Nimble/Expectation.swift#L74-L77), it reads:

https://github.com/Quick/Nimble/blob/8023e3980d91b470ad073d6da843b73f2eeb1844/Sources/Nimble/Expectation.swift#L74-L77

@ikesyo it looks like you'd done the release, could I ask you to take a look when you get a chance? Could be as simple as a forgotten `git pull`.

**Comment by ikesyo** [comment]
I'm not sure how does #531 relate to #530. Are you just saying that #531 is not cherry-picked into `7.x-branch`? `master` is now for a next major release so #531 is not included in v7.1.2. #530 was backported by #536.

**Comment by ashfurrow** [comment]
My apologies – I must have been confused. So #531 was merged but has not yet been released?

**Comment by ikesyo** [comment]
Not yet. Since #531 is purely additive change, backporting to 7.x-branch should be okay.

**Comment by ikesyo** [comment]
Submitted #576.

**Comment by ikesyo** [comment]
I'll keep it open until v7.2.0 is released.

**Comment by ikesyo** [comment]
Nimble v7.2.0 has been released, closing.
