### ISSUE TITLE
Predicates for matching (equal, contains) on [String:Any] and [Any]

### ISSUE THREAD

**Issue by pobengtsson** [Quick/Nimble#585]
I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
Based on [Working with JSON in Swift](https://developer.apple.com/swift/blog/?id=37) I have code that I want to test that deals with [Any] and [String:Any] to represent JSON list roots and JSON object roots.
To test some of that code I would like to write tests like the code example below (not an exhaustive list of combinations).

### What did you expect to happen?
I expected to be able to write tests like:

```
import Quick
import Nimble

class NimbleMatcherIssue : QuickSpec {
   override func spec() {
      describe("matching [String:Any] dictionaries and [Any] lists") {
         context("a list of [String:Any]") {
            it("should compile and pass") {
               let actual_dict : [String:Any] = ["foo": 10, "bar": "void"]
               let actual_list = [actual_dict]
               expect(actual_list).to(contain(actual_dict)) // expect this to pass
            }
         }
         context("a comparison of two [String:Any] dictionaries") {
            it("should compile and pass") {
               let one_dict : [String:Any] = ["foo": 42]
               let the_other_dict: [String:Any] = ["foo": "bar"]
               expect(one_dict).notTo(equal(the_other_dict)) // expect this to pass
            }
         }
         context("a test of an [Any] list containing another [Any] list") {
            it("should compile and pass") {
               let one_list : [Any] = [1, "two", ["foo":"bar"]]
               let the_other_list : [Any] = [1]
               expect(one_list).to(contain(the_other_list)) // expect this to pass
            }
         }
      }
   }
}
```

I expected this to compile and to perform the tests.

### What actually happened instead?
> Error:(11, 39) cannot convert value of type 'Predicate<NMBContainer>' to expected argument type 'Predicate<[[String : Any]]>'
Error:(18, 36) cannot convert value of type 'NMBMatcher' to expected argument type 'Predicate<[String : Any]>'
Error:(25, 36) cannot convert value of type 'Predicate<NMBContainer>' to expected argument type 'Predicate<[Any]>'

Please replace this with what happened instead.

### Environment

List the software versions you're using:

 - Quick: 1.3.1
 - Nimble:   7.1.3
 - Xcode Version: 9.4.1 (9F2000)
 - Swift Version: 4.1

Please also mention which package manager you used and its version. Delete the
other package managers in this list:
 - Cocoapods: 1.5.3

### Project that demonstrates the issue
https://www.dropbox.com/s/f4y8mmjqvejfv8d/NimbleMatcherIssue.zip?dl=0

**Comment by ikesyo** [comment]
`Any` is not `Equatable` so that can't do equality checks.

**Comment by pobengtsson** [comment]
Yes, but does that mean that the case I describe is an invalid use case and should not be supported by Nimble?

**Comment by ikesyo** [comment]
You may want a type something like this: 
https://github.com/thoughtbot/Argo/blob/ceb3775cfb22a3f0bf7f5aac1d71e3a89627ba36/Sources/Argo/Types/JSON.swift#L4

**Comment by pobengtsson** [comment]
Wrapping or converting like you suggest is not desirable, since I work with other frameworks (e.g. Alamofire) that follows the Apple way of using `Any`, `[Any]`, `[String:Any]` for representing the JSON object. Wrapping or converting for the sake of being compatible with Nimble-matchers in tests seems to like a detour to me.

What would be the problem with supporting the examples in Nimble?

What requires the matcher/predicate to use the Equatable protocol, and not other comparison code?
If there is a problem with using the matcher function name ```equal```, then another name could be chosen, perhaps ```equivalent```?

**Comment by ikesyo** [comment]
How do we compare those untyped objects correctly? The logic and included types will be different in each circumstances, so I think Nimble will not be able to provide a fits-all matcher.

You can still implement your custom `equivalent` matcher locally which meets your needs. Another direction is casting such data to `NSDictionary`/`NSArray`, then you can use a matcher for Objective-C types (`NSObject` subclasses).

**Comment by pobengtsson** [comment]
Hi, I checked your suggestion on using `NSDictionary` / `NSArray` and from the first quick initial tests it seems to help me do what I want.  I changed my example into:
```
import Quick
import Nimble

class NSCounterPartsSpec : QuickSpec {
   override func spec() {
      describe("matching [String:Any] dictionaries and [Any] lists") {
         context("a list of [String:Any]") {
            it("should compile and pass") {
               let actual_dict : [String:Any] = ["foo": 10, "bar": "void"]
               let actual_list = [actual_dict]
               expect(actual_list as NSArray).to(contain(actual_dict as NSDictionary)) // expect this to pass
            }
         }
         context("a comparison of two [String:Any] dictionaries") {
            it("should compile and pass") {
               let one_dict : [String:Any] = ["foo": 42]
               let the_other_dict: [String:Any] = ["foo": "bar"]
               expect(one_dict as NSDictionary).notTo(equal(the_other_dict as NSDictionary)) // expect this to pass
            }
         }
         context("a test of an [Any] list containing another [Any] list") {
            it("should compile and pass") {
               let one_list : [Any] = [1, "two", ["foo":"bar"]]
               let the_other_list : [Any] = [1,"two"]
               expect(one_list as NSArray).to(contain(the_other_list)) // expect this to pass
            }
         }
      }
   }
}
``` 
But when I run this the last test fails. But this could be me misunderstanding the contains predicate, because it works, after I change the last expect into:
```expect(one_list as NSArray).to(contain(1,"two")) // expect this to pass```

So, for now, I don't see any problems for me to go with your suggestion and cast to `NSDictionary` or `NSArray`.

Thanks for your instant and helpful replys!

**Comment by revolter** [comment]
![image](https://user-images.githubusercontent.com/5748627/44721768-a9e55300-aad3-11e8-9712-a873864365f5.png)
