### ISSUE TITLE
Allow custom messages in expect()

### ISSUE THREAD

**Issue by clayreimann** [Quick/Nimble#596]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```swift
for (tag, title) in defaultRows {
    let row = entryForm.row(tag: tag)
    expect(row.exists) == true
    expect(row.staticTexts["title"].label) == title
}
```

### What did you expect to happen?

I would like to be able to provide custom message to `expect` so that I can see which loop iteration failed.

```swift
for (tag, title) in defaultRows {
    let row = entryForm.row(tag: tag)
    expect(row.exists, message: "\(tag) exists") == true
// or maybe more briefly
//    expect(row.exists, "\(tag) exists") == true
    expect(row.staticTexts["title"].label) == title
}
```

I'd be willing to submit a PR if this feature fits with the project

### Environment

List the software versions you're using:

 - Quick: Nope
 - Nimble: *7.1.3*
 - Xcode Version: *9.4.1 (9F2000)*
 - Swift Version: *Xcode Default* 
 - Carthage: *0.30.1*

**Comment by clayreimann** [comment]
@ikesyo Any comment on this? Would such a PR be accepted?

**Comment by ikesyo** [comment]
It seems that this would be important with regard to #493.

**Comment by ikesyo** [comment]
I'm now working on this in relation to #742.
