### ISSUE TITLE
[Coredump]I ssue while running example appliaction of Linux

### ISSUE THREAD

**Issue by gladborn** [Quick/Nimble#603]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

. Path: mynewt-nimble-master/porting/examples/linux/
. Have built the application using make command. (Successful)
. Inserted a BLE dongle verified the interface using hciconfig command
. Was trying run the application which is compiled.(command:  sudo ./nimble-linux)
. I can see below logs 
nimble-linux: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Aborted (core dumped)

### What did you expect to happen?

I was expecting it will run successfully and then I was planning to run unit test application provided in the same repo.

### What actually happened instead?

CORE DUMP.

### Environment

List the software versions you're using:

- Kernel version: 4.4.0-119-generic

I am blocked. Please let me know ASAP

**Comment by ikesyo** [comment]
Nimble is a testing library used for test targets (within XCTests), it is not for application targets.

**Comment by ikesyo** [comment]
Looks like you confuse this and https://github.com/apache/mynewt-nimble. That is completely different and unrelated project. Closing.
