### ISSUE TITLE
Xcode 10 issue for Nimble while update carthage

### ISSUE THREAD

**Issue by balichowdry** [Quick/Nimble#608]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Hi

I am using Xcode10
Carthage 0.29.0
Swift version 4.2
Nimble "v7.0.3"

when I update Carthage I get this error, can you please help me I am not sure is Carthage issue with latest Xcode or Nimble issue

Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/NMBExceptionCapture.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### What did you expect to happen?

I am expecting it work same as Xcode9.3

### What actually happened instead?

Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/NMBExceptionCapture.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### Environment

 - Quick: *v1.1.0*
 - Nimble: *v7.0.3*
 - Xcode Version: *10.0* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.2* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.5.3* 
 - Carthage: *0.29.0* 
 - Swift Package Manager *Swift 4.2.0 (swiftpm-14248)*

**Comment by balichowdry** [comment]
I have updated to 7.3.0 still the same issue :(

**Comment by ikesyo** [comment]
Could you please paste the actual error log? 

> Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/NMBExceptionCapture.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

is insufficient.

**Comment by ragaisis** [comment]
I have problems too. Can't build using carthage 0.29, Swift 4.2,  xCode 10, Nimble v7.3.1

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/jonas/Projects/CGI/ios/ios-statistika/Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-iOS -configuration Release -derivedDataPath /Users/jonas/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/Nimble/v7.3.1 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=AED494DB-1977-40E2-B9A3-A13440ED6E8A -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/jonas/Projects/CGI/ios/ios-statistika/Carthage/Checkouts/Nimble)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/wz/r9m4vxx11hs45gqcxblmx54c0000gq/T/carthage-xcodebuild.DIaEpR.log

**Comment by ikesyo** [comment]
That is just an carthage output, please check the actual `xcodebuild` log in `/var/folders/wz/r9m4vxx11hs45gqcxblmx54c0000gq/T/carthage-xcodebuild.DIaEpR.log`.

**Comment by ragaisis** [comment]
[carthage-xcodebuild.DIaEpR.log](https://github.com/Quick/Nimble/files/2410068/carthage-xcodebuild.DIaEpR.log)

**Comment by ragaisis** [comment]
I've found out that updating carthage by using "master" solves the problem

Carthage file
```
github "Quick/Quick" "master"
github "Quick/Nimble" "master"

```
when i run `carthage update --platform ios` i see

```
*** Checking out Nimble at "a14526900f79402de46779ba4e6929112b6a34d5"
*** Checking out Quick at "044ea18d202369e33e1fc1849498a7824b89f1c4"

```
Pointing to master is not the best practise, so could you release new version that is currently in master

**Comment by ikesyo** [comment]
The fix for that is https://github.com/Quick/Nimble/pull/605 (which is in `master`) and the same fix is already applied to 7.3.1 (https://github.com/Quick/Nimble/pull/606). You may be hitting a build cache issue, so it may be good to remove DerivedData folder (`/Users/jonas/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/Nimble/v7.3.1`).

**Comment by ikesyo** [comment]
And also current `master` is heading to Nimble v8 which has some breaking changes but we are not ready to release the new major version yet.

**Comment by doancea** [comment]
I've been experiencing this issue in 8.0.1, swift version 4.2, Carthage 0.33 For the last few weeks.  clearing the Carthage cache fixes this for a build or 2 and then it starts failing again.  Has anyone else seen this as an issue?

**Comment by spesic** [comment]
@doancea Yes, we've been seeing the same with v8.0.1, xc 10.2.1_10E1001 and Carthage 0.33

**Comment by spesic** [comment]
This issue seems related: https://github.com/Quick/Nimble/issues/614
