### ISSUE TITLE
No such module 'Nimble' with Xcode 10 / Swift 4.2

### ISSUE THREAD

**Issue by NeverwinterMoon** [Quick/Nimble#610]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Switched to Xcode 10 and Swift 4.2. I found a few similar closed issues but they were related to using Swift 4 while Quick/Nimble only supported 3. Now, as I see, Nimble supports 4.2, so everything should work fine, but it doesn't.

### What did you expect to happen?

Tests to run

### What actually happened instead?

Tests do not run with error `No such module 'Nimble'`

### Environment

List the software versions you're using:

 - Quick: *1.3.2*
 - Nimble: *7.3.1*
 - Xcode Version: *10.0 (10A255)*
 - Swift Version: *4.2*

 - Cocoapods: *1.5.3*

**Comment by NeverwinterMoon** [comment]
Looks like a14526900f79402de46779ba4e6929112b6a34d5 fixes that problem. But none of the released versions work.

**Comment by abhilashdonepudi** [comment]
We have the same issue. Any workaround for this issue ?

**Comment by NeverwinterMoon** [comment]
> We have the same issue. Any workaround for this issue ?

I managed to fix this by using a yet unreleased version, like so:
`pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :commit => 'a14526900f79402de46779ba4e6929112b6a34d5'`

**Comment by abhilashdonepudi** [comment]
Thanks for the quick reply. That fixed the issue.

**Comment by ikesyo** [comment]
a145269 seems totally unrelated. The error should mean the framework is not build yet. So I think running a clean build or clearing derives data folder would address your errors. Closing.
