### ISSUE TITLE
Noescape Nimble crash in XCode 10.0 GM

### ISSUE THREAD

**Issue by zbencz3** [Quick/Nimble#611]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

When using XCode Version 10.0 (10A255), the test suite crashes with the following error:
`closure argument passed as @noescape to Objective-C has escaped`

see the sample project attached below
e.g. 
```
waitUntil(^(void (^done)(void)) {
    [subject db_presentForTest:^{
    done();
  }];
})
```

### What did you expect to happen?

The code mentioned should not crash on XCode 10.0. I expected this to be fixed since XCode 10 beta 3 or the workaround to be applied (https://github.com/Quick/Nimble/pull/537).

### What actually happened instead?

The code mentioned above still crashes on XCode 10.0.

### Environment

List the software versions you're using:

```
    pod "OCMock", '3.2.2'
    pod "Foundry", git: "https://github.com/hirad/Foundry", branch: 'master'
    pod "Quick", '~> 1.3'
    pod "Nimble", '~> 7.1
```
 - Cocoapods: 1.5.3 terminal

### Project that demonstrates the issue

[Escaping.zip](https://github.com/Quick/Nimble/files/2454693/Escaping.zip)

**Comment by zbencz3** [comment]
note: 
https://github.com/Quick/Nimble/pull/612

**Comment by ikesyo** [comment]
Okay, so I now understand that this issue is a different from #537 (which was a compiler regression) and #612 actually fix this.
