### ISSUE TITLE
[Nimble/Tinycrypt]:  Public and Private key generated by EC-DH method is mandatory to have size of 64 and 32 bytes respectively for BLE host stack of nimble? 

### ISSUE THREAD

**Issue by gladborn** [Quick/Nimble#616]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

[1]  I am trying to know about size of Private, Public and Shared key size being used in Nimble code.
ble_sm_alg_gen_key_pair -> uECC_make_key

[2] On what basis "curve_secp256r1" is decided to generate Public and Private key ?

### What did you expect to happen?

I am trying to use openssl in place of tinycrypt . For Public and Private key generation I am trying to use EC-DH calls of openssl in place of tinycrypt which generates 64 bytes of public key and 64 bytes of private key for similar curve.  Using that key if I am trying to connect to peer device it is not successful.

Do Nimble expects 64 bytes of Public and 32 bytes of private key ?

Note: I observed that debug key available for testing has key size of 64 and 32 bytes for Public and Private key respectively.

### What actually happened instead?

If I am using same curve(256r1) & same method(EC-DH) irrespective to key length device should connect to peer device.

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by ikesyo** [comment]
You are filing an issue on a wrong repository. Maybe you assume this https://github.com/apache/mynewt-nimble.

**Comment by ikesyo** [comment]
@gladborn This is the second time that you created an issue on this repisotory: https://github.com/Quick/Nimble/issues/603. 🙃

**Comment by ikesyo** [comment]
https://github.com/apache/mynewt-nimble as I suggested above. What you use is **Nim BLE** and this is **Nimble**.
