### ISSUE TITLE
`waitUntil` blocks indefinitely

### ISSUE THREAD

**Issue by vladiulianbogdan** [Quick/Nimble#617]
I've noticed that sometimes `waitUntil` blocks and doesn't return at all if the `done()` block is called from a block dispatched by global queue. I could not find in the documentation anywhere that the "done()" block needs to be called from main thread. Is this expected behavior? And if so, can you point me to where this is mentioned in the documentation?

### What did you do?

`                waitUntil { done in
                    DispatchQueue.global().async {
                        print("done")
                        done()
                    }
                }`

### What did you expect to happen?

The waitUntil should finish

### What actually happened instead?

Sometimes the test blocks indefinitely.

### Environment

List the software versions you're using:

 - Quick: v1.3.1
 - Nimble: v7.3.0
 - Xcode Version: 9.4.1
 - Swift Version: 4.1

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.28.0

**Comment by wongzigii** [comment]
@vladiulianbogdan You can find this in the index README.

> Note: waitUntil triggers its timeout code on the main thread. Blocking the main thread will cause Nimble to stop the run loop to continue. This can cause test pollution for whatever incomplete code that was running on the main thread. Blocking the main thread can be caused by blocking IO, calls to sleep(), deadlocks, and synchronous IPC.

> In some cases (e.g. when running on slower machines) it can be useful to modify the default timeout and poll interval values. This can be done as follows:

    // Swift

    // Increase the global timeout to 5 seconds:
    Nimble.AsyncDefaults.Timeout = 5

    // Slow the polling interval to 0.1 seconds:
    Nimble.AsyncDefaults.PollInterval = 0.1
