### ISSUE TITLE
Compiler is failing with ambiguous use of beEmpty()

### ISSUE THREAD

**Issue by ianbytchek** [Quick/Nimble#638]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Just updated the latest framework version from 7.x to 8x and getting a compilation error that seems to be related to #496. This must be caused caused by an `IndexSet`, which conforms to both `Collection` and `SetAlgebra`:

```log
Test.Renderer.swift:18:57: error: ambiguous use of 'beEmpty()'
            expect(renderer.pendingFrames).toEventually(beEmpty())
                                                        ^
Nimble.beEmpty:1:13: note: found this candidate
public func beEmpty<S>() -> Nimble.Predicate<S> where S : Sequence
            ^
Nimble.beEmpty:1:13: note: found this candidate
public func beEmpty<S>() -> Nimble.Predicate<S> where S : SetAlgebra
            ^
```

**Comment by ikesyo** [comment]
Looks like the reduced condition is `Sequence` and `SetAlgebra`.

**Comment by ianbytchek** [comment]
Hmm, didn't look deeply at the source, but assume there's either a separate predicate for `Collection`? [Doesn't look](https://developer.apple.com/documentation/foundation/indexset#relationships) like `IndexSet` has anything to do with `Sequence`. Can I help with any other info?

**Comment by anayini** [comment]
Just ran into this as well.  I think because of `Sequence` and `SetAlgebra`.  Quick client side patch can be to write a function generic over `Sequence & SetAlgebra` so that swift chooses that one, or to wrap an ambiguous value into an `AnySequence`.

**Comment by anayini** [comment]
One fix @ikesyo could be to add:

`
public func beEmpty<S: Sequence & SetAlgebra>() -> Predicate<S> 
`

So that Swift has a more specific implementation to choose.

**Comment by ollitapa** [comment]
I'm getting this with "contain" on even a simple sets
```swift
let a = Set([1, 2, 4])
expect(a).to(contain(1)) // Ambiguous
```
Looks like a major usablity issue to me 😅

**Comment by ikesyo** [comment]
We already recognized the issue, so locked this.

**Comment by ikesyo** [comment]
> Doesn't look like IndexSet has anything to do with Sequence.

IndexSet is BidirectionalCollection, BidirectionalCollection is Collection, Collection is Sequence.

**Comment by ikesyo** [comment]
@ianbytchek

> Doesn't look like IndexSet has anything to do with Sequence.

IndexSet is BidirectionalCollection, BidirectionalCollection is Collection, Collection is Sequence.

**Comment by ikesyo** [comment]
Hey forks, I submitted a PR to fix this. So you could use `fix-beempty-and-contain-matcher-ambiguity ` branch for now.
