### ISSUE TITLE
CRITICAL: Unsupported Version of Swift (3.0) in Xcode 10.2

### ISSUE THREAD

**Issue by hmlongco** [Quick/Nimble#644]
The minimum Swift Language Version (3.0) for the current version of Nimble fails to build on Xcode 10.2 as 3.0 is unsupported. The minimum Swift Language Version for all targets to be at least 4.0.

### What did you do?

Build Nimble using Xcode 10.2 on a project converted to Xcode 5.

### What did you expect to happen?

Project to test and build correctly.

### What actually happened instead?

Build system failed with error: 
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Nimble-iOS')

### Environment

 - Quick: 1.3.4
 - Nimble: 7.3.3
 - Xcode Version: 10.2
 - Swift Version: 5
 - Carthage: 0.32.0

**Comment by ikesyo** [comment]
Please upgrade to Nimble 8.0 which supports Swift 4.2 or later.

**Comment by hmlongco** [comment]
Ummmm. Okay. But slightly confused. Wouldn't the Carthage file pull the latest versions if no version is specified?

github "Quick/Quick"
github "Quick/Nimble"

**Comment by ikesyo** [comment]
You should run `carthage update`  but not `carthage bootstrap`; the latter will checkout the resolved version which is recorded in `Cartfile.resolved` if it's not first run.
