### ISSUE TITLE
How can test a function without return statement?

### ISSUE THREAD

**Issue by krishnaSoni2113** [Quick/Nimble#655]
Hello Team,

I want to test a function which is not having any kind of return statement.
So when a function has no return statement that means my test case would be that this function has called or not.
EX:-

func printLogStatement(_ message: String?) {
     print(message)
}

I just want to test that this function is calling or not, How can I create a test case for same?

Thanks.

**Comment by ikesyo** [comment]
Looks like what you want is a mock, which will be achievable by 

- Sourcery's AutoMockable: https://github.com/krzysztofzablocki/Sourcery/blob/master/guides/Mocks.md
_
-SwiftyMocky: https://github.com/MakeAWishFoundation/SwiftyMocky
- Cuckoo: https://github.com/Brightify/Cuckoo

which is not directly related to Nimble.

**Comment by krishnaSoni2113** [comment]
@ikesyo Thanks for response.

But I don't want to create any mock code to just check that function is calling or not.
Is there any way to check this case with Quick/Nimble?

func printLogStatement(_ message: String?) {
print(message)
.
.
.
// My Code
}

In above function I just want to test that print statement is executing or not or we can say whatever code written in this function are executing or not.

**Comment by ikesyo** [comment]
Unfortunately no.

**Comment by krishnaSoni2113** [comment]
@ikesyo 

https://github.com/Brightify/Cuckoo
Did you ever face this kind of error while using Cuckoo?

![Screenshot 2019-05-22 at 5 01 38 PM](https://user-images.githubusercontent.com/25579674/58172878-682ab700-7cb7-11e9-9384-7445a546edea.png)

**Comment by ikesyo** [comment]
I've never used Cuckoo so I'm not sure.

**Comment by krishnaSoni2113** [comment]
Seems there is no way to test a function without mock.

As @ikesyo suggest below libraries are for mock.

- Sourcery's AutoMockable: https://github.com/krzysztofzablocki/Sourcery/blob/master/guides/Mocks.md
- SwiftyMocky: https://github.com/MakeAWishFoundation/SwiftyMocky
- Cuckoo: https://github.com/Brightify/Cuckoo
- Or writing a mock by your hand

I am closing the issue but if anyone found other best way plz share here.

Thanks.
