### ISSUE TITLE
Demystifying beAnInstanceOf

### ISSUE THREAD

**Issue by MortyMerr** [Quick/Nimble#657]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```swift
let expectation = expect(1)
expectation.to(beAnInstanceOf(Int.self))
```
### What did you expect to happen?

Code compiles.

### What actually happened instead?

Code doesn't compile.
`Instance method 'to(_:description:)' requires the types 'Int' and 'Any' be equivalent`

### Environment

List the software versions you're using:

 - Quick: v2.1.0
 - Nimble: v8.0.1
 - Xcode Version: 10.2.1 (10E1001)
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.33.0

**Comment by MortyMerr** [comment]
Hi team! Thank you for your great job. Please allow me to ask you some questions.
I guess this even should not compile, but I can't explain why. Maybe, you will help?
I also don't understand how `beAnInstanceOf` work at all.
```swift
print(type(of: beAnInstanceOf(Int.self))) // Predicate<Any>
expect(1).to(*requires Predicate<Int>*)
expect(1).to(predicate) // works ok
```
I tried to dig into sources, but still can't understand how it works.
Will appreciate any answer, thanks!

**Comment by ikesyo** [comment]
`beAnInstanceOf` returns `Predicate<Any>` because the matcher takes _any value_ to execute _runtime type checking_. If the matcher is `Predicate<T>` that only accepts `Expectation<T> so the two types are known to be equivalent at compile time, then there is no need to execute _runtime type checking_.

> `expect(1).to(*requires Predicate<Int>*)`

That's not true. If you pass `beAnInstanceOf` matcher here, `expect(1)` is type-inferenced as `Expectation<Any>`.

**Comment by ikesyo** [comment]
> `let expectation = expect(1)`

So if you want to separate expectation declaration and running matcher into two expressions, you need to type the declaration as `Expectation<Any>`: `let expectation: Expectation<Any> = expect(1)`

**Comment by MortyMerr** [comment]
Yeah, now i see. Thank you very much for the clarification  :)
