### ISSUE TITLE
Notification userInfo

### ISSUE THREAD

**Issue by zbencz3** [Quick/Nimble#671]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

I was looking at the notifications support in quick/nimble, e.g.:
```
expect {
    NotificationCenter.default.postNotification(testNotification)
}.to(postNotifications(equal([testNotification]))
```

Is there a way to get my hands on the notification I am looking for(using the notification name for example) to inspect the `userInfo`?
My goal is to invoke a method that posts a notification, and then inspect that notification userInfo and make sure that the key/value pairs are correct.

### Environment

List the software versions you're using:

 - Quick: *2.1.0*
 - Nimble: *8.0.1*
 - Xcode Version: *10.2 (10E125)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.2* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.6.1* (Use `pod --version` in Terminal)

**Comment by zbencz3** [comment]
I ended up writing my own matcher like this:
```
func equalName(_ expectedName: Notification.Name, condition: @escaping (([AnyHashable: Any]) -> Bool)) -> Predicate<[Notification]> {
    return Predicate.define("equal <\(stringify(expectedName))>") { actualExpression, msg in
        guard let actualValue = try actualExpression.evaluate() else {
            return PredicateResult(status: .fail, message: msg)
        }

        let actualNames = actualValue
            .filter { $0.name == expectedName }
            .filter { notification in
                guard let userInfo = notification.userInfo else {
                    return false
                }

                return condition(userInfo)
            }
            .compactMap { $0.name }
        let matches = actualNames.contains(expectedName)
        return PredicateResult(bool: matches, message: msg)
    }
}
```

**Comment by ikesyo** [comment]
Looks like you can also use `containElementSatisfying` matcher.
