### ISSUE TITLE
SourceLocation init is internal

### ISSUE THREAD

**Issue by Megal** [Quick/Nimble#672]
Could we have init method of `SourceLocation` to be public?

- [ ✅] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I was trying to add fail assert if my code that reports an error, using provided information about source location.
```
describe("keychain") {
    beforeEach {
        keychain = QKeychain(errorHandler: { (msg, _ file: String, _ function: String, _ line: Int) in
            fail(msg, location: SourceLocation(file: file, line: UInt(line)))
        })
    }

    // Tests for keychain
}
```

### What did you expect to happen?

Have an ability to initialize `SourceLocation` with custom file and line.

### What actually happened instead?

Compilation error. 
> 'SourceLocation' initializer is inaccessible due to 'internal' protection level

### Environment

List the software versions you're using:

 - Quick: *2.1.0*
 - Nimble: *8.0.2*
 - Xcode Version: *Version 10.2.1 (10E1001)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.0.1* 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.7.2* (Use `pod --version` in Terminal)

**Comment by ikesyo** [comment]
Looks like you can use `fail(msg, file: file, line: UInt(line))` overload.
