### ISSUE TITLE
Nimble does't stop for breakpoint in test

### ISSUE THREAD

**Issue by texuf** [Quick/Nimble#673]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
I love this framework! But...
I want to place a breakpoint in my code, then run a test, but nimble is failing the test.

```
func testTest() {
   var didComplete = false
   doSomethingAsync {
      didComplete = true
   }
   expect(didComplete).toEventually(beTrue())
}
```

If I run this test, and place a breakpoint in my doSomethingAsync function, the `expect(didComplete)...` will fail and kill my test

### What did you expect to happen?

breakpoints should halt all execution, I should be able to stay on a breakpoint for as long as I want without Nimble killing my session.

### What actually happened instead?

Nimble stopped my test execution.

### Environment

github "Quick/Nimble" "v8.0.2"

 - Carthage: 0.33.0

### Project that demonstrates the issue

provided upon request.

**Comment by younata** [comment]
Hey @texuf! I'm really sorry about the nearly-3-year delay! Is this still an issue you're seeing now?

**Comment by texuf** [comment]
Thanks for following up! I have moved on to other things. I'll close this issue since it doesn't seem to be affecting anyone else.
