### ISSUE TITLE
Release Nimble v9 for bumping Swift version requirement (to 5.2) and adjust the deprecation roadmap

### ISSUE THREAD

**Issue by ikesyo** [Quick/Nimble#685]
Refs:
- #623
- #674 
- #681

**Comment by danielsaidi** [comment]
Any idea when this could be released? Would adding more maintainers help? I'd be happy to help in any way I can, since discussions regarding critical errors go uncommented and prs are not merged.

**Comment by ikesyo** [comment]
Just published [v9.0.0-beta.1](https://github.com/Quick/Nimble/releases/tag/v9.0.0-beta.1).

**Comment by ikesyo** [comment]
[v9.0.0-beta.2](https://github.com/Quick/Nimble/releases/tag/v9.0.0-beta.2) was released on May 16.

**Comment by ikesyo** [comment]
[v9.0.0-beta.3](https://github.com/Quick/Nimble/releases/tag/v9.0.0-beta.3) has been released.

**Comment by ikesyo** [comment]
[v9.0.0-rc.1](https://github.com/Quick/Nimble/releases/tag/v9.0.0-rc.1) has been released.

**Comment by rutgerfarry** [comment]
Just curious what else is standing in the way of the 9.0.0 release? Would be happy to help if I can!

**Comment by fdiaz** [comment]
Now that Xcode 12 is GM it'd be nice to have a release version here if there's nothing else missing!

**Comment by spydercapriani** [comment]
Same question as above, it looks like without `v9.0.0-rc.1` any use of `expect { }` results in swift compiler errors of `illegal instruction 4` in Xcode 12. 

Hopefully this helps anyone out there searching (and as lost as I was) trying to solve for this error after switching to GM version of Xcode 12. After switching to this release, all my headaches disappeared 🥳

**Comment by fdiaz** [comment]
@spydercapriani you can use rc.3. We've updated to use that in the meantime and it seems to be working quite well.

**Comment by ikesyo** [comment]
Finally published [v9.0.0](https://github.com/Quick/Nimble/releases/tag/v9.0.0)! 🎉
