### ISSUE TITLE
Build failed with 8.0.3

### ISSUE THREAD

**Issue by Wassmd** [Quick/Nimble#686]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
github "Quick/Nimble" ~>  8.0.2
Carthage update --platform iOS

### What did you expect to happen?
Generate build

### What actually happened instead?
Error 

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mwasim/gcx/gitProjects/_Personal/RxMVVMC/Carthage/Checkouts/Nimble/Nimble.xcodeproj -scheme Nimble-iOS -configuration Release -derivedDataPath /Users/mwasim/Library/Caches/org.carthage.CarthageKit/DerivedData/10.3_10G8/Nimble/v8.0.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_c/8tpvf47n2cjgm2gbl6c85jxc0000gn/T/Nimble SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mwasim/gcx/gitProjects/_Personal/RxMVVMC/Carthage/Checkouts/Nimble)

### Environment
Mac OS X Majave
List the software versions you're using:

 - Quick: *?.?.?*
 - Nimble: 8.0.3
 - Xcode Version: *?.? (????)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *?.?* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *?.?.?* (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by dt7-ford** [comment]
I am also facing the same issue, please look into the following error log

 <img width="1659" alt="Screenshot 2019-09-10 at 12 17 41 PM" src="https://user-images.githubusercontent.com/45350184/64590377-06589f00-d3c5-11e9-8195-438af0a11b3f.png">

**Comment by danielsaidi** [comment]
We're also facing the same issue. Downgrading to `8.0.2` works.

**Comment by ikesyo** [comment]
I'm sorry for the trouble, I'm aware of this so please stay tuned.

**Comment by ikesyo** [comment]
[v8.0.4](https://github.com/Quick/Nimble/releases/tag/v8.0.4) has been released.
