### ISSUE TITLE
Create a new release to include Package.swift update

### ISSUE THREAD

**Issue by marmelroy** [Quick/Nimble#714]
25 days ago there was an update to Packages.swift to bump CwlPreconditionTesting to 2.0.0 - which fixes a Swift Package Manager bug. 

Since then, there were no releases of nimble which means that projects that depend on Nimble through Swift Package Manager are not getting that fix. 

Is it possible to create a new release tag?

**Comment by danielsaidi** [comment]
@ikesyo Has created a 9.0 milestone (https://github.com/Quick/Nimble/issues/685), which had to be a major bump due to breaking changes on their end. However, it seems to be halting, which is a shame since Nimble with SPM makes some parts fail, like `toEventually`.

**Comment by ikesyo** [comment]
Looks like you are referring to #720 and that was resolved in the latest 8.0.7 release. Closing.
