### ISSUE TITLE
Nimble 8.0.4+ crashes due to CwlPreconditionTesting being "damaged or missing necessary resources"

### ISSUE THREAD

**Issue by danielsaidi** [Quick/Nimble#720]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Upgraded Nimble from 8.0.2 to 8.0.5 in an SPM package ().

### What did you expect to happen?

The tests would continue to run successfully.

### What actually happened instead?

The test suite crashes due to problems with CwlPreconditionTesting:

```
Showing All Messages
xctest (27033) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “SheeeeeeeeetTests” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(/Users/admin/Library/Developer/Xcode/DerivedData/Sheeeeeeeeet-bpdwemkusvsybpefrvxivlepzywu/Build/Products/Debug-iphonesimulator/SheeeeeeeeetTests.xctest/SheeeeeeeeetTests): Library not loaded: @rpath/CwlPreconditionTesting.framework/CwlPreconditionTesting
  Referenced from: /Users/admin/Library/Developer/Xcode/DerivedData/Sheeeeeeeeet-bpdwemkusvsybpefrvxivlepzywu/Build/Products/Debug-iphonesimulator/SheeeeeeeeetTests.xctest/SheeeeeeeeetTests
  Reason: image not found))
```

### Environment

 - Quick: *2.2.0*
 - Nimble: *8.0.5*
 - Xcode Version: *11.3*
 - Swift Version: *5.1.3*
 - Swift Package Manager *5.1.0*

### Project that demonstrates the issue

https://github.com/danielsaidi/Sheeeeeeeeet

If you download this, open the package and updates SPM to use Nimble 8.0.5, you should see this problem as well.

**Comment by zac** [comment]
I'm having the same issue 🙁

**Comment by rudedogdhc** [comment]
Until it is fixed, you can work around this issue by adding CwlPreconditionTesting as a package dependency and explicitly linking it into your test bundle.

**Comment by gilroykilroy** [comment]
Same.

**Comment by donnywdavis** [comment]
I'm having the same issue here as well. I changed the package to point to `master` and that seemed to resolve the issue. Looks like the update of `CwlPreconditionTesting` to version 2.0.0 fixes this issue.

**Comment by honghaoz** [comment]
Use version 8.0.2, which is still good to use

**Comment by sacOO7** [comment]
It was also breaking for me, using version 8.0.2 quickly fixed it :)

**Comment by dwhitla** [comment]
8.0.2 rolls back to another show stopping bug where **toEventually** hangs when you build with SPM - (basically the compiler optimizes away a required code path)

**Comment by danielsaidi** [comment]
@ikesyo Since you seem to be the only one maintaining this repository and commits/replies are few and far between, do you think we should discuss the future of this project? It's such a wonderful tool and it would be a shame if people stop using it because of these problems going on for too long. At least, the roadmap should be clear so that people know that the tool will still be around a year from now.

**Comment by ikesyo** [comment]
Looks like this doesn't happen on Xcode 11.4 but should be addressed anyway for Xcode 11.3 users. I submitted a fix in #729.

**Comment by ikesyo** [comment]
[v8.0.7](https://github.com/Quick/Nimble/releases/tag/v8.0.7) has been released, please try it.

**Comment by danielsaidi** [comment]
Wow, I will try it out asap!

**Comment by danielsaidi** [comment]
@ikesyo Really strange - I can't bump Nimble above 8.0.2. It doesn't matter if I use `from: "8.0.7"` or `.exact("8.0.7")` - it's stuck at 8.0.2. Any ideas?

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/429927/77880125-35990580-725c-11ea-9e4e-10160ede6778.png">
