### ISSUE TITLE
Provide Github Release Artifacts for Carthage

### ISSUE THREAD

**Issue by Blackjacx** [Quick/Nimble#724]
I recognized that when switching between different Swift versions carthage needs to build the framework again which is, as we all know, time intensive. A way that makes this much better is to provide a framework bundle in the respective Github Release of this framework. This is automatically downloaded by Carthage which avoids building. The bundle can be created by e.g. Fastlane in the following easy steps:

https://github.com/Blackjacx/Scripts/blob/48aa814b1ff510b177951c197ce40a4dda566383/frameworks/Fastfile#L143-L145

**Comment by ikesyo** [comment]
> I recognized that when switching between different Swift versions carthage needs to build the framework again which is, as we all know, time intensive.

Carthage's prebuilt binary is not a direct solution for the situation; We can't ship multiple frameworks built by different Swift versions in a zip. I'd rather utilize module stability feature implemented in Swift 5.1 (`BUILD_LIBRARY_FOR_DISTRIBUTION=YES`).

**Comment by ikesyo** [comment]
Closing this in favor of #731. Thanks for filling the issue though!

**Comment by Blackjacx** [comment]
Ah nice thx 👍
