### ISSUE TITLE
Don't compile in tvOS: "Use of undeclared type 'BadInstructionException"

### ISSUE THREAD

**Issue by diogot** [Quick/Nimble#736]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Integrate Nimble in a tvOS Framework target with native SPM or CocoaPods.

### What did you expect to happen?

Work the same as in iOS targets.

### What actually happened instead?

Nimble don't compile for tvOS targets. Errors with `Use of undeclared type 'BadInstructionException'` in [`ThrowAssertion.swift:13`](https://github.com/Quick/Nimble/blob/7fd118ec8795888bcbbebc1a41f6984454c4cd6f/Sources/Nimble/Matchers/ThrowAssertion.swift#L13).

Although the `master` works without problem. Can we cut a new release?

### Environment

 - Nimble: 8.0.7
 - Xcode Version: 11.4.1 (11E503a) or 11.4
 - Swift Version: none

Happen with both:
 - Cocoapods: 1.9.1
 - Swift Package Manager: Xcode builtin

### Project that demonstrates the issue

https://github.com/diogot/nimble-8.0.7-tvos-bug

**Comment by ikesyo** [comment]
Just published [v9.0.0-beta.1](https://github.com/Quick/Nimble/releases/tag/v9.0.0-beta.1).

**Comment by diogot** [comment]
Thanks!
