### ISSUE TITLE
Already merged in Generic ThrowError matcher is not included in latest release

### ISSUE THREAD

**Issue by CassiusPacheco** [Quick/Nimble#737]
Hello,

I've noticed that the [Generic ThrowError Matcher](https://github.com/Quick/Nimble/blob/master/Sources/Nimble/Matchers/ThrowError.swift#L14) was merged into `master` over seven months ago (28 Sep 2019), but for some reason it hasn't be included in Nimble's latest releases (v8.0.7) for some reason.

This is required to solve a problem in this framework https://github.com/RxSwiftCommunity/RxNimble/issues/49.

Is there anything missing to get that out soon? If so, how can I help?

Thank you for your work!

**Comment by ikesyo** [comment]
Current `master` is aiming next major release (v9) and the latest release is cut from `8.x-branch` (maintenance branch). That is the reason.
