### ISSUE TITLE
Failing tests throw NSInternalInconsistencyException when using AppCode

### ISSUE THREAD

**Issue by mark-anders** [Quick/Nimble#740]
I've been using Nimble successfully for years with Xcode and JetBrains' AppCode. However, with recent versions of AppCode that support Swift 5 (which use Xcode 11.4), any test failure throws an NSInternalInconsistencyException right after reporting the error that occurred.

I filed a bug with JetBrains and they narrowed it down to the use of swizzling in the `+load` method `XCTestObservationCenter+Register`. You can see that bug here: 

https://youtrack.jetbrains.com/issue/OC-19997. 

The solution was to  replace the swizzling code with the following, which I tried and it worked.

      [[XCTestObservationCenter sharedTestObservationCenter] addTestObserver:[CurrentTestCaseTracker sharedInstance]];

The comment for `+load` indicates that the swizzling was done due an issue with Xcode 7.3. However, Nimble 9.0.0 now requires 11.4 and it could be that the issue no longer exists.  In my fork, I ran all tests for all platforms and everything passed, so it may not be required any longer.

I have a fix and could submit a pull request.

**Comment by ikesyo** [comment]
Thanks for filing the issue. I confirmed the followings:

- `-[XCTestObservationCenter _addLegacyTestObserver:]` is no longer called on Xcode 10.1 or later (it's okay to apply the fix on v8.x as well)
- An `XCTestLog` instance is already added to `XCTestObservationCenter` when calling `sharedTestObservationCenter` initially

That means that we should be able to register `CurrentTestCaseTracker` safely by `+load` method or using C function with `__attribute__((constructor))`. I'll use the later way.

**Comment by ikesyo** [comment]
@mark-anders Could you try the branch `avoid-method-swizzling` of #741?

**Comment by ikesyo** [comment]
[v8.0.8](https://github.com/Quick/Nimble/releases/tag/v8.0.8) has been released.

**Comment by mark-anders** [comment]
Hi @ikesyo, sorry for the delay. I was traveling and wasn't able to test previously. Thank you so much for the quick fix. It works great.
