### ISSUE TITLE
expect({ _ }).to(throwError()) does not seem to be working

### ISSUE THREAD

**Issue by eMdOS** [Quick/Nimble#747]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I am unit testing a piece of code. It seems like `Nimble` is not handling a scenario that is throwing an error.

I did double-check it by running the same test using `XCTests`. It is properly handling the error thrown.

Using `XCTests`:
```swift
let nil_string: String? = nil
XCTAssertThrowsError(
    try nil_string.orThrow(FakeError())
)
```

Using `Nimble`:
```swift
let nil_string: String? = nil
expect({
    try nil_string.orThrow(FakeError())
}).to(throwError())
```

### What did you expect to happen?

I would expect `Nimble` to handle the error thrown as same as `XCTest` does.

### What actually happened instead?

Instead, it is showing me what seems to be a false-positive. It is showing the message:

`failed - expected to throw any error, got no error`

As I mentioned above. I did double-check this by writing the same test using `XCTest`.

### Environment

List the software versions you're using:

- Quick: *2.2.0*
- Nimble: *8.0.7*
- Xcode Version: *11.3 (11C29)*
- Swift Version: *5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager *Swift 5.1.0 (swiftpm-15502)*

### Project that demonstrates the issue

Unfortunately, this isn't a public project.

**Comment by eMdOS** [comment]
I am closing the defect because it seems like if I remove the "parentheses" from the function it just works.

This works:
```swift
expect {
    try nil_string.orThrow(FakeError())
}.to(throwError())
```

This **does not** work:
```swift
expect({
    try nil_string.orThrow(FakeError())
}).to(throwError())
```

Apparently, the signature of these 2 functions is different, but it looks the same. Personally, I find this confusing.

**Comment by ikesyo** [comment]
Nimble uses `@autoclosure` so `expect({ try nil_string.orThrow(FakeError()) })` is automatically wrapped in a closure:

```swift
{ { try nil_string.orThrow(FakeError()) } }
```

When the expression is passed to the matcher, the outer closure (created by `@autoclosure`) is evaluated and returns the inner closure as a result. The inner closure is not evaluated so no error is thrown. That is the reason why.

**Comment by eMdOS** [comment]
I know how the `@autoclosure` works - after reading the code and realizing there 2 almost-equal function signature, then is when I made the change on my end in order to make it work.

But... My point here is that the API results confusing - at least to me.

i.e.: Swift functors, when do `map`, in most of the cases (with a couple of exceptions) developers can do `.map {}` or `.map({})` and the result is the same - here, it isn't the case for `expect {}` and `expect({})`.
