### ISSUE TITLE
Attempted to report a test failure to XCTest while no test case was running on 8.1.0

### ISSUE THREAD

**Issue by wassil** [Quick/Nimble#795]
I've added 8.1.0 to a new project with just one test.
Running the test that is expected to fail produces `caught "NSInternalInconsistencyException", "Attempted to report a test failure to XCTest while no test case was running.`

I tried lowering versions of Nimble, the first one to correctly report test failure is 8.0.7

I'm on XCode 11.4.1

**Comment by ikesyo** [comment]
I can't reproduce it. Please fill the [issue template](https://github.com/Quick/Nimble/blob/master/.github/ISSUE_TEMPLATE) first.

**Comment by wassil** [comment]
It's a react native project with a whole bunch of dependencies. We plan on releasing it as open source soon. I'll close this for now and re-open once the repo is publicly available so you can reproduce.

**Comment by esteluk** [comment]
I'm also seeing this, will see if I can make a reproducible issue.

**Comment by esteluk** [comment]
I'm confident that this issue is related to https://github.com/Quick/Nimble/commit/28d79788ecd17ea6875dda56aba8df5c3ccd088e because I can pretty clearly see that the `CurrentTestCaseTracker` instance methods are never being fired, which results in methods falling through.

**Comment by esteluk** [comment]
I'm pretty confident that this issue happens for users who are linking Nimble statically 👍 . I managed to fix it locally by changing to dynamic linking, but the ` __attribute__((constructor)) ` annotation means that `registerCurrentTestCaseTracker` is being optimised out by the linker.

**Comment by LarsPetersHH** [comment]
I see the same problem in a project where the pods (including Nimble) are linked statically. Is there a way to re-open this ticket?

**Comment by mokagio** [comment]
I experienced this just now, too. Nimble was added via CocoaPods and as @LarsPetersHH said, it was using static libs. The failure occurred on an async expectation, `expect(foo).toEventuallyNot(beNil())`.

Luckily, I had no reason for not using frameworks, adding `use_frameworks!` to the `Podfile` fixed it 👍 

_My test's still failing, though, but that's got nothing to do with Nimble_ 😅

**Comment by wassil** [comment]
My project is in React Native and I'm also using static libs which seem to be the problem here.

Reopening

**Comment by ikesyo** [comment]
Sorry for the inconvenience, could you try #802?

**Comment by ikarishinjigao** [comment]
@esteluk 
> I'm also seeing this (in a Swift/Obj-c iOS project), will see if I can make a reproducible issue.

Same problem here.

@ikesyo 
And just tried #802, problem solved.

**Comment by LarsPetersHH** [comment]
> Sorry for the inconvenience, could you try #802?

Works for me too, thanks!
