### ISSUE TITLE
Provide option to silence all non-essential output

### ISSUE THREAD

**Issue by alexeypetrushin** [Quick/Nimble#810]
Currently there's no way to silence non-essential output from the `nimble`, the code 

```
echo "Hi"
```

produces

```
$ nimble --hints:off run test
  Verifying dependencies for nim@1
      Info: Dependency on yaml@any version already satisfied
  Verifying dependencies for yaml@0.14.0
   Building nim/test using c backend
Hi
```

It's possible to silence nim with `nim c -r --hints:off test.nim` but not `nimble`

### What did you expect to happen?

Have an option for nimble to silence non essential output with `--quiet` so that the output will be

```
$ nimble --quiet run test
Hi
```

**Comment by ikesyo** [comment]
This repository is an assertion library for Cocoa development (Apple platforms) written in Swift and Objective, not a command line tool. Closing.

**Comment by ikesyo** [comment]
Looks like https://github.com/nim-lang/nimble is what you want.

**Comment by alexeypetrushin** [comment]
+1 Sorry, I didn't noticed it's the different one.
