### ISSUE TITLE
Xcode 12 warns about deprecated XCTest API usage

### ISSUE THREAD

**Issue by arangato** [Quick/Nimble#829]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Build Nimble for testing with Xcode12.

### What did you expect to happen?

No warnings.

### What actually happened instead?

NimbleXCTestHandler.swift:81:18: warning: 'recordFailure(withDescription:inFile:atLine:expected:)' is deprecated: Replaced by 'record(_:)'

**Comment by paulz** [comment]
now Xcode 26 have the same warning for me while running tests in Quick
