### ISSUE TITLE
allPass + beCloseTo(Date) produces a compilation error on Swift 5.3

### ISSUE THREAD

**Issue by sjmadsen** [Quick/Nimble#831]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Using `allPass` in combination with `Date`s and the `beCloseTo` matcher produces a compilation error: `Global function 'allPass' requires the types 'Date' and 'NMBDoubleConvertible' be equivalent`.

Specifically, I have an assertion that looks like this:

```let date = ...
expect(objects.map { $0.createDate }).to(allPass(beCloseTo(date, within: 1)))
```

### What did you expect to happen?

I expected this to compile and assert that each date in the result from the `map` is within 1 second of the local `date`. Taking a wild guess, perhaps the change in #764 is related?

### What actually happened instead?

`Global function 'allPass' requires the types 'Date' and 'NMBDoubleConvertible' be equivalent`

### Environment

List the software versions you're using:

- Quick: *n/a*
- Nimble: *9.0.0-rc.3*
- Xcode Version: *12.0*
- Swift Version: *5.3*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager *Swift Package Manager - Swift 5.3.0*

**Comment by ikesyo** [comment]
📝 This doesn't occur on Xcode 11.7 (Swift 5.2).
