### ISSUE TITLE
Memory leak when using expect { ... }.to(throwAssertion())

### ISSUE THREAD

**Issue by RafaelPlantard** [Quick/Nimble#854]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I was trying to test a fatalErrror, it worked correctly (its function) but it's generating a memory leak that only occurs when trying to throwAssertion()
```
func testInitializationFromNSCoderShouldThrowFatalError() {
    expect { _ = SetupViewController(coder: NSCoder()) }.to(throwAssertion())
}
```

### What did you expect to happen?

Check if a fatalError occurred without generating a memory leak.

### What actually happened instead?

Checked if a fatalError occurred generating a memory leak.

### Environment

List the software versions you're using:

- Quick: *3.0.0*
- Nimble: *9.0.0*
- Xcode Version: *12.3 (12C33)* (Open Xcode; In menubar: Xcode > About Xcode)
- Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.10.1* (Use `pod --version` in Terminal)
- Carthage: *0.36.1* (Use `carthage version` in Terminal)
- Swift Package Manager *Swift Package Manager - Swift 5.3.0* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

Reproduceable project: https://github.com/RafaelPlantard/NimbleBug

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by winkelsdorf** [comment]
I would say that's as designed. Nimble uses `CwlPreconditionTesting` to convert the assertion to an exception which is caught (very simplified, under the hood Cwl uses a Mach-O Exception Handler).

See the comment in:
https://github.com/Quick/Nimble/blob/57ed10eddd18a6d2f4ab76caedffc572eddaadd9/Carthage/Checkouts/CwlPreconditionTesting/Sources/CwlPreconditionTesting/CwlCatchBadInstruction.swift#L141

> If a "BAD_INSTRUCTION" exception is raised, the block will be exited before completion via Objective-C exception. The risks associated with an Objective-C exception apply here: most Swift/Objective-C **functions are *not* exception-safe**. **Memory may be leaked** and the program will not necessarily be left in a safe state.

It's used in the ThrowAssertion Matcher from here:
https://github.com/Quick/Nimble/blob/57ed10eddd18a6d2f4ab76caedffc572eddaadd9/Sources/Nimble/Matchers/ThrowAssertion.swift#L13
