### ISSUE TITLE
Test with Custom Validation is not compiled

### ISSUE THREAD

**Issue by pavel-primachek** [Quick/Nimble#862]
### What did you do?

I have updated Nimble from 8.1.2 to 9.0.0.

I have tests with Custom Validation like this

`expect({`
`guard false else { return .failed(reason: "some reason") }`
`return .succeeded`
`}).to(succeed())`

This test is not compiled. Errors: 
`Type '(() -> ToSucceedResult)?` has no member 'failed'
`Type '(() -> ToSucceedResult)?` has no member 'succeeded'

At the same time test below is compiled successfully:
`expect({
return .succeeded
}).to(succeed())`

I suppose it's related to changes in `expect...` methods signature regarding @autoclosure modifier.

Note:
I have tried to change signature of `succeed` function.
from:
`public func succeed() -> Predicate<() -> ToSucceedResult>`
to
`public func succeed() -> Predicate<ToSucceedResult>`

In this case tests are compiled successfully.

### What did you expect to happen?

Test is compiled successfully

### What actually happened instead?

I've got errors:
`Type '(() -> ToSucceedResult)?` has no member 'failed'
`Type '(() -> ToSucceedResult)?` has no member 'succeeded'

### Environment

List the software versions you're using:

- Quick: *3.1.2*
- Nimble: *9.0.0*
- Xcode Version: *12.1 (12A7403)*
- Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.10.1*
-  
### Project that demonstrates the issue

<img width="1212" alt="Screen Shot 2021-02-15 at 16 41 54" src="https://user-images.githubusercontent.com/34301106/107956605-68e99d80-6fb0-11eb-91a0-bda7e1b613fa.png">

**Comment by Capotasto** [comment]
Completely similar situation.

**Comment by JonnyBeeGod** [comment]
Same problem, the error msg helps here however. 
This works:

```
expect({
                    let result: (() -> ToSucceedResult)? = {
                        guard case let .loaded(questions) = subject.state else {
                            return .failed(reason: "wrong enum case")
                        }
                        
                        if questions == [] {
                            return .succeeded
                        } else {
                            return .failed(reason: "wrong questions")
                        }
                    }
                    
                    return result
                }).toEventually(succeed())
```

**Comment by ikesyo** [comment]
Now it is expected to use trailing closure syntax for the `succeed` matcher to make type inference work correctly:

```swift
expect {
    guard false else { return .failed(reason: "some reason") }
    return .succeeded
}.to(succeed())
```

**Comment by acecilia** [comment]
@ikesyo Could you elaborate? Im using trailing closure with Xcode 12.3, but the errors keep appearing:

<img width="996" alt="Screenshot 2021-06-29 at 16 10 00" src="https://user-images.githubusercontent.com/7938671/123812662-8e8a9a00-d8f4-11eb-9cde-4d2185f6bf35.png">

**Comment by huang-jiafeng** [comment]
expect {{
    guard false else { return .failed(reason: "some reason") }
    return .succeeded
}}.to(succeed())

should use {{}}

**Comment by bohdanpodvirnyi** [comment]
@huang-jiafeng thank you, it actually helped!
