### ISSUE TITLE
`==` can't match `.init` on Xcode 12.5

### ISSUE THREAD

**Issue by serges147** [Quick/Nimble#867]
- [ x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```
struct Xxx: Equatable {
    let value: Int
}
let xxx = Xxx(value: 123)
expect(xxx) == .init(value: 123)
```

### What did you expect to happen?

Successfuly compile and pass expect, as it used to with XCode 12.4 & Swift 5.3.

### What actually happened instead?

```
/Tests.swift:128:25: error: binary operator '==' cannot be applied to operands of type 'Expectation<Xxx>' and '_'
            expect(xxx) == .init(value: 123)
            ~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
/Tests.swift:128:29: error: cannot infer contextual base in reference to member 'init'
            expect(xxx) == .init(value: 123)
                           ~^~~~
```

### Environment

List the software versions you're using:

- Nimble: 9.0.1
- Xcode Version: Version 12.5 (12E262)
- Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: 1.10.1

### Project that demonstrates the issue

https://github.com/serges147/nimble_report

**Comment by ikesyo** [comment]
It might be an effect of 

> Extend implicit member syntax (SE-0287)

https://swift.org/blog/swift-5-4-released/

I recommend you to file a ticket on https://bugs.swift.org.

**Comment by serges147** [comment]
I can file a ticket but I'm not sure what would be the "simplest" example to compose for "swift.org" - it definitely should be without Nimble entities (like `Expectation` and so on)...

**Comment by acecilia** [comment]
I am working on updating a big codebase from `Xcode 12.3` to `Xcode 12.5.1`, and experiencing hundreds of these errors. After looking around for a while, found this issue. 

Updating `Nimble` from  `9.2.0` to version `9.2.1` (which includes [the PR above](https://github.com/Quick/Nimble/pull/897)) did not fix the problem

**Comment by acecilia** [comment]
Thanks @ikesyo 🙌 Do you have any ETA for the maintenance release?

**Comment by acecilia** [comment]
The PR above seems to solve just part of the issue. If using `expect(X).to(equal(.init(X)))`, compiler complains in both Xcode 12.5.1 and Xcode 13:

<img width="1133" alt="Screenshot 2021-09-22 at 11 45 43" src="https://user-images.githubusercontent.com/7938671/134330496-7935a4ee-2d24-4571-a2e6-97413baef8cb.png">

<img width="1166" alt="Screenshot 2021-09-22 at 11 46 39" src="https://user-images.githubusercontent.com/7938671/134330499-ca99a072-2565-4288-bc5c-9f73137a2919.png">
:
