### ISSUE TITLE
Result matchers not being included in xcframework

### ISSUE THREAD

**Issue by drekka** [Quick/Nimble#911]
### Environment

- Nimble: *9.2.0
- Xcode Version: 12.5
- Swift Version: 5.3
- Carthage: *0.38.0*

### Problem

Building Nimble for unit testing using `carthage --no-use-binaries --use-xcframeworks --platform iOS`.

Noticed that the `Result` matchers are not being included: `beSuccess(...)` and `beFailure(...)`.

Not sure why these matchers are not present. The doco indicates they should be.

**Comment by ikesyo** [comment]
That is merged into `main` branch but is not released yet.

**Comment by vikdenic** [comment]
Are there any plans to include the Result matching into an official release soon? (Not just **/main**)
