### ISSUE TITLE
Xcode 13 Beta 1 Archive Error

### ISSUE THREAD

**Issue by adamtharani** [Quick/Nimble#913]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

`Carthage bootstrap` or Archive the Nimble-macOS scheme for Apple Silicon, Intel

### What did you expect to happen?

Carthage and Archiving to complete successfully

### What actually happened instead?
Build Failure

```
uplicate symbol '_NDR_record' in:
    /Users/adamtharani/Library/Developer/Xcode/DerivedData/Nimble-axqdeefwusmvxqglfhxhyotpbetj/Build/Intermediates.noindex/ArchiveIntermediates/Nimble-macOS/IntermediateBuildFilesPath/Nimble.build/Release/Nimble-macOS.build/Objects-normal/x86_64/CwlDarwinDefinitions.o
    /Users/adamtharani/Library/Developer/Xcode/DerivedData/Nimble-axqdeefwusmvxqglfhxhyotpbetj/Build/Intermediates.noindex/ArchiveIntermediates/Nimble-macOS/IntermediateBuildFilesPath/Nimble.build/Release/Nimble-macOS.build/Objects-normal/x86_64/CwlCatchBadInstruction.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

### Environment

List the software versions you're using:

- Quick: *?.?.?*
- Nimble: Main Branch
- Xcode Version: Version 13.0 beta (13A5154h)
- Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Carthage: 0.38.0
- Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by ikesyo** [comment]
Thanks for reporting this! I submitted a potential fix in #915. Could you try that branch?

**Comment by tattn** [comment]
@ikesyo Thank you for your quick fix!
I tried #915, and then `carthage bootstrap` was successful :tada:

**Comment by nmccann** [comment]
I've unfortunately run into the same issue using Xcode 13 Beta 2, and the latest from the `main` branch, however in my case I'm using Quick/Nimble as a Swift Package Manager dependency. Upon building and running my XCUI tests for an iOS app, I get the following error:

```
duplicate symbol '_NDR_record' in:
    /Users/USER/Library/Developer/Xcode/DerivedData/PROJECT/Build/Intermediates.noindex/CwlPreconditionTesting.build/Release-iphonesimulator/CwlPreconditionTesting.build/Objects-normal/x86_64/CwlBadInstructionException.o
    /Users/USER/Library/Developer/Xcode/DerivedData/PROJECT/Build/Intermediates.noindex/CwlPreconditionTesting.build/Release-iphonesimulator/CwlPreconditionTesting.build/Objects-normal/x86_64/CwlCatchBadInstruction.o
ld: 1 duplicate symbol for architecture x86_64
```

I was able to bypass the issue by creating a local copy of Nimble, and commenting out it's dependency on `CwlPreconditionTesting` (and any usages of it). I then tried to narrow things down further by modifying a local copy of `CwlPreconditionTesting` - if I comment out [this line](https://github.com/mattgallagher/CwlPreconditionTesting/blob/master/Sources/CwlPreconditionTesting/CwlCatchBadInstruction.swift#L112) - I no longer get the build error. I haven't yet figured out how to resolve it without commenting out what I assume is a necessary line.

Any suggestions would be much appreciated - thanks!

**Comment by ikesyo** [comment]
> Release-iphonesimulator

I'm not sure why your UI test target and it's dependencies are built in Release configuration 🤔

**Comment by nmccann** [comment]
🤦  That's a good catch - I'll have to see if changing to debug makes a difference.

I've recently moved from Debug builds to Release builds for my UI tests because of the significant decrease in run time - I've noticed with Debug builds, the tests spend a lot of time "waiting for app to idle" - in Release mode they run almost 4-5 times faster. I would have preferred to have them in Debug, but the time savings were hard to ignore.

**Comment by nmccann** [comment]
Switching to a Debug configuration resolved the issue I was having - I also remembered that it wasn't the Debug configuration that was resulting in the "waiting for app to idle" issues, instead those were due to having the debugger attached. So with a Debug configuration and the debugger disabled, it built fine and ran at the same speeds I was seeing before.

Thank you for the help!

**Comment by ElieJacquelin** [comment]
I seem to be hitting the same issue on simulator build only, let me know if you want me to create a brand new issue.

### What did you do?
Trying to build unit tests for simulator using XCode 13 Beta 3 and using commit `ae8b0845230da664025e471c92a8b2d0621350c3` of Nimble

### What did you expect to happen?

Nimble can be successfully compiled.

### What actually happened instead?

Build fails with the following error

```
duplicate symbol '_NDR_record' in:
    /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-ecpvoacgdbonzagbvaxvtiddtnvl/Build/Intermediates.noindex/Pods.build/UnitTest-iphonesimulator/Nimble.build/Objects-normal/x86_64/AdapterProtocols.o
    /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-ecpvoacgdbonzagbvaxvtiddtnvl/Build/Intermediates.noindex/Pods.build/UnitTest-iphonesimulator/Nimble.build/Objects-normal/x86_64/CwlDarwinDefinitions.o
ld: 1 duplicate symbol for architecture x86_64
```

**Note** This happens only when trying to build for the **simulator**, running tests on a physical device does not trigger the error

### Environment

List the software versions you're using:

- Quick: *4.0.0*
- Nimble: *9.2.0 Commit ae8b0845230da664025e471c92a8b2d0621350c3* (I confirm that my local copy in the pods folder does contain the changes of that commit)
- Xcode Version: *13.0 beta 3 (13A5192j)*
- Swift Version: *Xcode Default*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.10.1*

**Comment by serges147** [comment]
Still exactly the same problem (with xcode 13.beta4, and Nimble `main` branch).

**Comment by serges147** [comment]
@ikesyo :point_up_2:

**Comment by freddiebo** [comment]
@serges147 i created new issue https://github.com/Quick/Nimble/issues/919
