### ISSUE TITLE
Custom matcher won't compile

### ISSUE THREAD

**Issue by drekka** [Quick/Nimble#914]
I've checked out the `main` branch (via Swift package in Xcode 12.5 beta) and trying to use a custom matcher like this

```swift
expect {
            guard case StateMachineError.illegalTransition = error else {
                return .failed(reason: "Incorrect error")
            }
            return .succeeded
        }.to(succeed())
``` 

But it won't compile (Nor will it in the release Xcode when I initially tried it using Carthage to include Nimble). 

<img width="854" alt="Screen Shot 2021-06-09 at 22 47 37" src="https://user-images.githubusercontent.com/153837/121356954-b7aeaf00-c974-11eb-99b7-d10f5ee9d363.png">

Any idea what I've done wrong?

**Comment by LSWarss** [comment]
Same in my case, cannot compile after updating Nimble from 8.0.2 to latest

**Comment by drekka** [comment]
Solved it. Don't have the code available but I think I converted the responses to closures. ie `return { .succeed() }` instead of `return .succceed()`.

**Comment by LSWarss** [comment]
@drekka Yeah it helper, apparently right now it returns closure ;) thanks for the tip I think we can close this issue

**Comment by phlippieb** [comment]
The readme should probably be updated to show compiling code before this issue is closed, no? I'd submit a PR, but I don't understand the reasoning behind the change, so someone who does should probably take that on.

**Comment by ikesyo** [comment]
ref: #963
