### ISSUE TITLE
`beTruthy` and `beFalsey` looks suspitious

### ISSUE THREAD

**Issue by amomchilov** [Quick/Nimble#917]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

I was browsing around the source code, and the definitions of the `beTruthy` and `beFalsey` matchers caught my eye:

## `beTruthy()`

https://github.com/Quick/Nimble/blob/92dd63d2dbd9bf5ef733e83febc94f035004573e/Sources/Nimble/Matchers/BeLogical.swift#L98-L107

It seems like line 105 is equivalent to `PredicateStatus(bool: false)`. The value will always be `nil` by that point, since if it were non-nil, it would have hit the `if let` branch above.

If I'm not mistaken, I think line 102-105 can be replaced with simply `return PredicateStatus(bool: actualValue == (true as T))`. Only equivalence to `true` will make the status `true`, and only the `false` and `nil` cases will both cause it to be false.

## `beFalsey()`

https://github.com/Quick/Nimble/blob/92dd63d2dbd9bf5ef733e83febc94f035004573e/Sources/Nimble/Matchers/BeLogical.swift#L109-L119

Similarly line 117 is equivalent to `PredicateStatus(bool: true)`. The value will always be `nil` by that point, since if it were non-nil, it would have hit the `if let` branch above.

For this case, I think lines 114-117 can be replaced with simply `return PredicateStatus(bool: actualValue != (true as T))`. The `false` and `nil` cases will both make the status `true`, and only equivalence to `true` would make the status `false`.

The only caveat I see here is that it assumes that the conformance of `T` to `ExpressibleByBooleanLiteral` and `Equatable` is such that `x == (true as T) ≡ x != (false as T)`. We might actually want to add some assertions that this is the case, to help users spot incorrect implementations of these protocols.

Thoughts?

**Comment by younata** [comment]
This is resolved now in #978.
