### ISSUE TITLE
Xcode 13 Beta 4 error build

### ISSUE THREAD

**Issue by freddiebo** [Quick/Nimble#919]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Trying to build unit tests for simulator using XCode 13 Beta 4 and using version 9.2.0 of Nimble

### What did you expect to happen?

Nimble can be successfully compiled.

### What actually happened instead?

Build fails with the following error

> duplicate symbol '_NDR_record' in:
>     /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-ecpvoacgdbonzagbvaxvtiddtnvl/Build/Intermediates.noindex/Pods.build/UnitTest-iphonesimulator/Nimble.build/Objects-normal/x86_64/AdapterProtocols.o
>     /Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-ecpvoacgdbonzagbvaxvtiddtnvl/Build/Intermediates.noindex/Pods.build/UnitTest-iphonesimulator/Nimble.build/Objects-normal/x86_64/CwlCatchBadInstruction.o
> ld: 1 duplicate symbol for architecture x86_64

### Environment

List the software versions you're using:

- Quick: *4.0.0*
- Nimble: *9.2.0*
- Xcode Version: 13.0 beta 4 (13A5201i)
- Swift Version: *Xcode Default*

- Cocoapods: *1.10.1*

**Comment by shepting** [comment]
We are seeing this as well.

**Comment by jnes92** [comment]
So, just to add a small detail:
Im also running Xcode 13 beta 5 - tried using the fix, so I'm using the latest commit from main branch (0fd4ba405699eb8ca939aefa34babf988f4ff9ff).

Still the Same error appears for me: 
`duplicate symbol '_NDR_record' in: [...] AdapterProtocols.o `

**Comment by stevelandeyasana** [comment]
It also seems possible this bug in the Swift compiler, manifesting in CwlPreconditionTesting, is the root cause: https://github.com/mattgallagher/CwlPreconditionTesting/issues/22

**Comment by stevelandeyasana** [comment]
Someone on the Swift bug tracker suggested switching from CwlPreconditionTesting to https://github.com/norio-nomura/XCTAssertCrash.
