### ISSUE TITLE
Build error for `watchOS` target. `BadInstructionException`

### ISSUE THREAD

**Issue by Juanpe** [Quick/Nimble#922]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Built a test target for `watchOS` using `Nimble`. Set 'Debug Executable' to false in my scheme.

### What actually happened instead?

Compiler Error. Target will not build.

`Use of undeclared type 'BadInstructionException.`

### Environment

List the software versions you're using:

- Nimble: *9.2.0*
- Xcode Version: *12.5.1*
- Swift Version: `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager *5.4.0*

**Comment by younata** [comment]
Hey @Juanpe! Thanks for the issue! This issue was duplicated by https://github.com/Quick/Nimble/issues/954, and I'm going to close this one in favor of #954.

**Comment by Juanpe** [comment]
Thanks! 👍🏼
