### ISSUE TITLE
Installation errors:

### ISSUE THREAD

**Issue by ssherar** [Quick/Nimble#94]
Hi,

I am currently trying to utilise Quick, but hitting a brick wall when it comes to installing nimble. At the moment I have just included Nimble to try and isolate the issue. It is currently cloned as a submodule (using the 0.4.0 hash) as I can see on travis that last couple of commits have failed on travis ci - again to try and isolate the issue

Currently I have included the XCodeProj into the Tests (FormularyTests) object within Xcode, but when I try and link the framework with the binary, or when it is being inspected, the build will fail with 224 errors across a lot of the swift files. An example of this can be found here - https://gist.github.com/ssherar/768004cf60fc6671c39e

Have you seen this before and is there anything I can do to resolve this?

Sam

**Comment by modocache** [comment]
@ssherar Are you using Swift 1.1 or prior? :point_up: :bulb:

v0.4.0 of Nimble supports Swift 1.2--you'll need to build using Xcode 6.3 in order for it to work. If you'd like to use Swift 1.1 (available on Xcode 6.2 or prior), use v0.3.0.

Let me know if that resolves your issue!

**Comment by ssherar** [comment]
Well apparently I can't read. Thank you very much @modocache!
