### ISSUE TITLE
Expectation `beCloseTo` hang compilation when optional chaining is present

### ISSUE THREAD

**Issue by odisei369** [Quick/Nimble#949]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I wrote simple test:
```swift
import Nimble
import Quick

class HangingSpec: QuickSpec {
    override func spec() {
        context("it should not hanging") {
            it("should compile") {
                let expectedWidth: Double = 375
                let elem: CGSize? = CGSize(width: 374, height: 200)
                expect(elem?.width).to(beCloseTo(expectedWidth, within: 2))
            }
        }
    }
}
```

### What did you expect to happen?

I'm expecting it to successfully compile and pass.

### What actually happened instead?

Swift compiler is hanging indefinitely.

If I change this code so `elem` is not optional, then everything compiles normally.
Replacing `.to(beCloseTo(expectedWidth, within: 1))` with `== expectedWidth` also allow program to compile, but then test didn't pass.

### Environment

- Quick: *3.1.2*
- Nimble: *9.2.1*
- Xcode Version: *13.1 (13A1030d)*
- Swift Version: *5.5.1* (`Xcode Default`)

- Carthage: *0.38.0*

**Comment by ikesyo** [comment]
It seems that this is related to [SE-0307](https://github.com/apple/swift-evolution/blob/main/proposals/0307-allow-interchangeable-use-of-double-cgfloat-types.md).

**Comment by younata** [comment]
I agree with @ikesyo. This is a swift bug, not a nimble bug. I found [SR-15218](https://bugs.swift.org/browse/SR-15218) which describes the behavior as reported. According to swift bugs, this is being addressed.

I'm going to close this bug. It'll get fixed whenever Apple fixes it.
