### ISSUE TITLE
Make Nimble compile for watchOS.

### ISSUE THREAD

**Issue by danielsaidi** [Quick/Nimble#954]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

Nimble doesn't compile for watchOS, since `throwAssertion` uses an exception type that isn't available for watchOS. This has been a problem for a long time and makes it hard to use Quick and Nimble in projects and packages that target watchOS.

While a real solution may be larger undertaking (one such PR already exists), I have created a [pull request](https://github.com/Quick/Nimble/pull/953) that disables the part that doesn't compile. Since only `throwAssertion` is affected, it's a very small tweak to a single place in the library.

With this tweak, developers will get a descriptive message and have the choice to either just not unit test on watchOS or to disable tests that rely on `throwAssertion`. This will at least make the code compile, which will be a huge improvement.

**Comment by danielsaidi** [comment]
@ikesyo Any progress on this? I'd love to get my PR merged and released, so that I don't have to use my own forks in my various watchOS supporting projects. Lmk if I can help in any way.

**Comment by younata** [comment]
Hey @danielsaidi, I merged your linked PR. I'd like to see CI building/running on watchOS, as well as the watchOS targets added to the xcodeproj before we actually release watchOS support. If you're able to, I'd love to see a PR for those.

I'll leave this open as we don't yet have watchOS support.

**Comment by danielsaidi** [comment]
That's great - thank you! I'd love to take a look at it if I get some time on my hands. If so, I'll write more here. 👍

**Comment by younata** [comment]
In the interest of getting v10 out the door sooner, I'm going to move watchOS support to the next major release.

**Comment by younata** [comment]
This was done a few months ago, but forgot to close this. Closing it now!
