### ISSUE TITLE
Matchers for raiseException() name and reason

### ISSUE THREAD

**Issue by modocache** [Quick/Nimble#96]
The `raiseException()` matcher uses strict equality for the name and reason of an exception:

```swift
// Passes if actual raises an exception with the given name and reason:
expect(actual).to(raiseException(named: name, reason: reason))
```

I think that strict equality on things like `reason` leads to brittle tests--in reality, I usually just want to make sure that the `reason` of an exception contains a specific term. It'd be great if, instead, I could use matchers for each:

```swift
expect(actual).to(raiseException(
    name: equal(NSInternalInconsistencyException),
    localizedDescription: match("cannot be nil")
))
```

Thoughts? :raised_hands:

**Comment by mkauppila** [comment]
I think this would be a great enhancement. This would certainly reduce the brittleness of matching exception in specs. So I'd be all :+1:  for this.

**Comment by jeffh** [comment]
Agreed!


— Sent from my iPhone

**Comment by modocache** [comment]
I played around with this concept in a custom matcher I'm writing, and came across an interesting problem: what if I want to make a *negative* assertion? For example:

```swift
expect(actual).to(raiseException(
    name: equal(NSInternalInconsistencyException),
    localizedDescription: doesNotMatch("wtf")
))
```

The `doesNotMatch()` matcher, of course, doesn't exist. Instead, Nimble allows users to write `notTo.match()`. Would it be worth trying to accomplish something similar here? Like a `not()` matcher that returns the negative of the given matcher?

```
expect(actual).to(not(equal("value")))
expect(actualClosure).to(raiseException(
    name: equal(NSInternalInconsistencyException),
    localizedDescription: not(match("wtf"))
))
```

I think the `not()` matcher is an interesting idea, but it may also be overkill. Maybe we should just focus on non-negative assertions here?

**Comment by rbeeger** [comment]
This can be closed as it was implemented in https://github.com/Quick/Nimble/pull/99

**Comment by jeffh** [comment]
Closed. Thanks @rbeeger!
