### ISSUE TITLE
Maintenance status of this repository

### ISSUE THREAD

**Issue by acecilia** [Quick/Nimble#968]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

Hi 👋 

First of all, thanks for the library. It is very useful and I have been already using it for several years at work and also personal projects.

The goal of this issue is to provide some context and information to consumers about the current maintenance status of this repository, so they can make the decision of continue using Nimble, or otherwise start removing it from their codebases. The reasons are:
* This library is a very important component of many huge swift projects. I personally use it at work and have thousands of lines of code that depend on this library
* Since the M1 updates, I have been observing a lack of feedback, releases and commits in the repository. There are some long standing issues opened that seem critical to me, as they block adoption of the new M1 machines. Some of them:
    * Assertion testing: https://github.com/Quick/Nimble/issues/961
    * Equality failures: https://github.com/Quick/Nimble/pull/962
* In some cases, the community is fixing bugs and adding features, but a release is not being created by maintainers (see for example https://github.com/Quick/Nimble/pull/948#issuecomment-1007281648)

Would be very useful to have some more information about current status and future plans for this library.
Thanks!

**Comment by acecilia** [comment]
@ikesyo Would very much appreciate your comment here 🙏

**Comment by bbreslin1** [comment]
FlightAware uses this repo extensively for Apple and Android mobile automation testing.  We love it and pray support continues!

**Comment by jessesquires** [comment]
Please see https://github.com/Quick/Nimble/discussions/979
