### ISSUE TITLE
Matchers for NSError

### ISSUE THREAD

**Issue by modocache** [Quick/Nimble#97]
Let me know if this sort of thing would be better left as an external custom matcher outside of the Quick org, but I think it'd be nifty to be able to write:

```swift
let error = NSError()
expect(error).to(beAnError(
    domain: equal("io.modocache.Gift"),
    localizedDescription: match("Could not resolve path")
))
```

Note that I can use matchers for the `domain` and `localizedDescription`. This is different than how Nimble's `NSException` matcher currently works, and is more in line with #96.

**Comment by mkauppila** [comment]
I think this would be even more useful than #96. At least I tend to use `NSerror` more often than `NSException` so to me this would make sense. Tought I can't really comment whether this matcher should be part of Nimble or not. Though I'd like see this implemented :)

Just wondering should the `beAnError` also optionally include the error code of `NSError` too?

**Comment by modocache** [comment]
Yep, being able to match on `code` would be great, too! Thanks for the feedback, @mkauppila! :+1: 

My biggest dilemma at the moment: what to call the matcher? Is there a better name than `beAnError()`?

**Comment by jeffh** [comment]
Out of curiosity, what is the difference between this and just matching against the properties? It seems like it's conveying the same meaning as

```swift
expect(error.domain).to(equal("io.modocache.Gift"))
expect(error.localizedDescription).to(match("Could not resolve path"))
```

with some more API surface area to maintain. Maybe for future consideration, but I'm not particularly sold on it's value in Nimble. Outside of Nimble seems fine.

Although it would be valuable to build a list of external nimble matchers. It would be nice to have a place to find some ;)

**Comment by mkauppila** [comment]
Semantically it's the same. To me the difference is just cleaner, a bit more readable syntax. Though the difference is quite minor.

**Comment by modocache** [comment]
> Out of curiosity, what is the difference between this and just matching against the properties?

Oh, good call! Now that you mention it, I think you're absolutely right, @jeffh. And I *hate* widening API surface area! :japanese_goblin: :zap:

Thanks for the insight!
