### ISSUE TITLE
Build Errors in Latest Version

### ISSUE THREAD

**Issue by kglee79** [Quick/Nimble#98]
I cloned the latest version from the repo and am not able to get the project to build.  I just cloned it, opened the project in XCode 6.1.1 and am trying to build it, but seeing around 38 errors.  Haven't done anything else to it.  One is in DSL.m, where it references <Nimble/Nimble-Swift.h>, however Nimble-Swift.h doesn't appear to exist anywhere.  In addition, there are a lot of places where casting with "expected as! String" is being used and Xcode is complaining that it's expecting a type after "as".  In Equal.swift, the class "Set" is being used, however the class does not appear to exist.  Perhaps I'm doing something incorrectly because it's showing as build passing on Github.

**Comment by jeffh** [comment]
master of Nimble is tracking Swift 1.2 (Xcode 6.3 beta). Checkout the swift-1.1 branch for Xcode 6.1.1




—

**Comment by kglee79** [comment]
My mistake, working after checking out the correct branch.  Thanks for pointing me in the right direction!
